///////////////////////////////////////////////////////////////////////
NOTE TO WRITERS:
This is a list of software required in addition to the TCK and a Compatible Implementation(CI).
For many Jakarta EE APIs, a Jakarta EE CI will be required, as described below.
For standalone technologies, no other software may be required, and the
below line can be removed.

This is used in intro.adoc in section 1.3 and install.adoc in section 3.2.
///////////////////////////////////////////////////////////////////////

* A Jakarta EE 10 Compatible Implementation
