///////////////////////////////////////////////////////////////////////
NOTE TO WRITERS:
This is included at the tail end of the Title page.
The following section should be customized for the technology.
This is provided to allow each technology to customize legacy acronym names
that are used in this TCK. 
Be sure to customize LegacyAcronym in attributes.conf
Add additional lines as needed for acronyms found in your TCK user guide.
///////////////////////////////////////////////////////////////////////

References in this document to {LegacyAcronym} refer to the {TechnologyFullName}, unless otherwise noted.

References in this document to JWS refer to Jakarta Web Services Metadata, unless otherwise noted.

Reference in this document to SAAJ refer to Jakarta SOAP Attachments, unless otherwise noted.

References in this document to JAXWS refer to Jakarta XML Web Services, unless otherwise noted.

References in this document to JACC refer to Jakarta Authorization, unless otherwise noted.


