ALTER TABLE ADDRESSEJB_TABLE drop constraint FK5FOR_CUSTOMEREJB_TABLE !
ALTER TABLE ADDRESSEJB_TABLE drop constraint FK6FOR_CUSTOMEREJB_TABLE !
ALTER TABLE PHONEEJB_TABLE drop constraint FKFOR_ADDRESSEJB_TABLE !
ALTER TABLE ALIASEJB_TABLE drop constraint FK1FOR_CUSTOMEREJB_TABLE !
ALTER TABLE ALIASEJB_TABLE drop constraint FK2FOR_CUSTOMEREJB_TABLE !
ALTER TABLE FKS_FOR_ALIAS_CUSTOMER drop constraint FKFOR_CUSTOMEREJB_TABLE !
ALTER TABLE FKS_FOR_ALIAS_CUSTOMER drop constraint FKFOR_ALIASEJB_TABLE !
ALTER TABLE CREDITCARDEJB_TABLE drop constraint FK3FOR_CUSTOMEREJB_TABLE !
ALTER TABLE CREDITCARDEJB_TABLE drop constraint FKFOR_ORDEREJB_TABLE !
ALTER TABLE ORDEREJB_TABLE drop constraint FK4FOR_CUSTOMEREJB_TABLE !
ALTER TABLE ORDEREJB_TABLE drop constraint FK0FOR_LINEITEMEJB_TABLE !
ALTER TABLE LINEITEMEJB_TABLE drop constraint FKFOR_PRODUCTEJB_TABLE !
ALTER TABLE LINEITEMEJB_TABLE drop constraint FK1FOR_ORDEREJB_TABLE !
ALTER TABLE TABLER5_DELETE drop constraint FK1FOR_TABLER6_DELETE_ID !
ALTER TABLE TABLER5_DELETE drop constraint FK2FOR_TABLER6_DELETE_ID !
ALTER TABLE TABLER5_DELETE drop constraint FK1FOR_TABLER7_DELETE_ID !
ALTER TABLE TABLER5_DELETE drop constraint FK2FOR_TABLER7_DELETE_ID !
ALTER TABLE TABLER7_DELETE drop constraint FKFOR_TABLER6_DELETE_ID !


ALTER TABLE COMPLEXPK_TABLE1 drop constraint FKFOR_LINEITEMS !
ALTER TABLE COMPLEXPK_LINEITEM_TABLE1 drop constraint FKFOR_ID !
ALTER TABLE FKS_ALIASNOOP_CUSTNOOP  drop constraint FK2FOR_ALIASEJB_TAB !
ALTER TABLE FKS_ALIASNOOP_CUSTNOOP  drop constraint FK8FOR_CUSTOMEREJB_TAB!
ALTER TABLE SPOUSEEJB_TABLE drop constraint FK7FOR_CUSTOMEREJB_TAB !
ALTER TABLE SPOUSEEJB_TABLE drop constraint FKFOR_INFOEJB_TAB !
ALTER TABLE INFOEJB_TABLE drop constraint FKFOR_SPOUSEEJB_TAB !

ALTER TABLE EMPLOYEEEJB drop constraint FK_MANAGER !
ALTER TABLE EMPLOYEEEJB drop constraint FK_DEPARTMENT !

drop table COMMON_TABLE !
create table COMMON_TABLE(ID  INTEGER NOT NULL, BRANDNAME  varchar(25), PRICE  REAL, constraint COM_TAB1 primary key(ID)) !

drop table COMMON_TABLE2 !
create table COMMON_TABLE2(ID  INTEGER NOT NULL, BRANDNAME  varchar(25), PRICE  REAL, constraint COM_TAB2 primary key(ID)) !

drop table COMMON_TABLE3 !
create table COMMON_TABLE3(ID  INTEGER NOT NULL, BRANDNAME  varchar(25), PRICE  REAL, constraint COM_TAB3 primary key(ID)) !

drop table LOCALACCESSTEST_TABLE1 !
create table LOCALACCESSTEST_TABLE1 (ID  INTEGER NOT NULL, NAME  varchar(25), VALUE  REAL, constraint LOCALACCESSTESTTABLE1 primary key(ID)) !

drop table EBACCESSTEST_TABLE2 !
create table EBACCESSTEST_TABLE2 (ID  INTEGER NOT NULL, NAME  varchar(25), VALUE REAL, constraint EBACCESSTESTTABLE2 primary key(ID))    !

drop table ENTITY_BEAN_TABLE1 !
create table ENTITY_BEAN_TABLE1 (KEY_ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE  REAL, constraint ENTITY_BEANTABLE1 primary key(KEY_ID)) !

drop table CMP_COMPLEXPK_TABLE1 !
create table CMP_COMPLEXPK_TABLE1 (ID  INTEGER NOT NULL, BRAND_NAME  varchar(25) NOT NULL, PRICE REAL, PRODUCT IMAGE , constraint CMPCOMPLEXPK_TABLE1 primary key(ID,BRAND_NAME)) !

drop table COMPLEXPK_TABLE1 !
create table COMPLEXPK_TABLE1 (ID INTEGER NOT NULL, BRANDNAME varchar(25) NOT NULL, PRICE REAL, PRODUCT IMAGE, FK_FOR_LINEITEMS varchar(25), constraint COMPLEXPKTABLE1 primary key(ID,BRANDNAME)) !

DROP table COMPLEXPK_LINEITEM_TABLE1 !
CREATE table COMPLEXPK_LINEITEM_TABLE1(ID varchar(25) NOT NULL, QUANTITY INTEGER, FK_FOR_ID INTEGER, FK_FOR_BRANDNAME varchar(25), constraint pk_LineItem_Table1 primary key(ID)) !

drop table CMP20_ENTITYCMP_TABLE1 !
create table CMP20_ENTITYCMP_TABLE1 (KEY_ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL,  B IMAGE, constraint CMP20_ENTITYCMPTABLE1 primary key(KEY_ID)) !

DROP  table CMP20_ENTITY_CTX_TABLE1 !
CREATE TABLE CMP20_ENTITY_CTX_TABLE1 (KEY_ID VARCHAR(255) NOT NULL, BRAND_NAME VARCHAR(255) , CONSTRAINT CMP20ENTITY_CTX_TABLE1 primary key (KEY_ID)) !

drop table CMP20_HOMEM_TABLE1 !
create table CMP20_HOMEM_TABLE1 (NAME VARCHAR(25) , STATE VARCHAR(25) , CODE VARCHAR(25) , ZIP INTEGER , ID INTEGER NOT NULL , EXPIRES VARCHAR(25) , STREET VARCHAR(25) , CARDBALANCE double precision , CITY VARCHAR(25) , HOMEPHONE VARCHAR(25) , WORKPHONE  VARCHAR(25) , LASTNAME VARCHAR(25) , PAYMENTTYPE VARCHAR(25) , CREDITCARDNUMBER VARCHAR(25) , ACCOUNTNUMBER VARCHAR(25) , MIDDLENAME VARCHAR(25) , FIRSTNAME VARCHAR(25) , CONSTRAINT CMP20_HOMEMTABLE1 PRIMARY KEY(ID)) !

drop table  UNKNOWNPK_TABLE1 !
create table UNKNOWNPK_TABLE1 (MIDDLENAME VARCHAR(255), LASTNAME VARCHAR(25), FIRSTNAME VARCHAR(25), STREET VARCHAR(25), CITY VARCHAR(25), STATE VARCHAR(25), ZIP INTEGER, ACCOUNTNUMBER VARCHAR(25), ABC NUMERIC(29) NOT NULL, constraint UNKNOWNPKTABLE1 primary key(ABC)) !

drop table ADDRESSEJB_TABLE !
CREATE TABLE ADDRESSEJB_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, STREET VARCHAR(255) , CITY VARCHAR(255) , STATE VARCHAR(255) , ZIP VARCHAR(255) , FK5_FOR_CUSTOMEREJB_TABLE VARCHAR(255) , FK6_FOR_CUSTOMEREJB_TABLE VARCHAR(255)) !

drop table CUSTOMEREJB_TABLE !
CREATE TABLE CUSTOMEREJB_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255) , COUNTRY IMAGE ) !

drop table PHONEEJB_TABLE !
CREATE TABLE PHONEEJB_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, AREA VARCHAR(255) , PHONE_NUMBER VARCHAR(255) , FK_FOR_ADDRESSEJB_TABLE VARCHAR(255) ) !

drop table ALIASEJB_TABLE !
CREATE TABLE ALIASEJB_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, ALIAS VARCHAR(255) , FK1_FOR_CUSTOMEREJB_TABLE  VARCHAR(255) , FK2_FOR_CUSTOMEREJB_TABLE  VARCHAR(255) ) !

drop table FKS_FOR_ALIAS_CUSTOMER !
CREATE TABLE FKS_FOR_ALIAS_CUSTOMER ( FK_FOR_CUSTOMEREJB_TABLE VARCHAR(255) , FK_FOR_ALIASEJB_TABLE VARCHAR(255)) !

drop table CREDITCARDEJB_TABLE !
CREATE TABLE CREDITCARDEJB_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, TYPE VARCHAR(255) , EXPIRES VARCHAR(255) , APPROVED NUMERIC , CREDITCARD_NUMBER VARCHAR(255) , BALANCE DOUBLE PRECISION, FK3_FOR_CUSTOMEREJB_TABLE VARCHAR(255) , FK_FOR_ORDEREJB_TABLE VARCHAR(255)) !

drop table ORDEREJB_TABLE !
CREATE TABLE  ORDEREJB_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, TOTALPRICE DOUBLE PRECISION, FK4_FOR_CUSTOMEREJB_TABLE VARCHAR(255) , FK0_FOR_LINEITEMEJB_TABLE VARCHAR(255)) !

drop table PRODUCTEJB_TABLE !
CREATE TABLE PRODUCTEJB_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), PRICE DOUBLE PRECISION, QUANTITY INTEGER, PNUM INTEGER ) !

drop table LINEITEMEJB_TABLE !
CREATE TABLE LINEITEMEJB_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, QUANTITY INTEGER , FK_FOR_PRODUCTEJB_TABLE VARCHAR(255) , FK1_FOR_ORDEREJB_TABLE VARCHAR(255)) !




ALTER TABLE ADDRESSEJB_TABLE add constraint FK5FOR_CUSTOMEREJB_TABLE Foreign Key (FK5_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(ID) !

ALTER TABLE ADDRESSEJB_TABLE add constraint FK6FOR_CUSTOMEREJB_TABLE Foreign Key (FK6_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(ID) !
ALTER TABLE PHONEEJB_TABLE add constraint FKFOR_ADDRESSEJB_TABLE Foreign Key (FK_FOR_ADDRESSEJB_TABLE) references ADDRESSEJB_TABLE(ID) !

ALTER TABLE ALIASEJB_TABLE add constraint FK1FOR_CUSTOMEREJB_TABLE Foreign Key (FK1_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(ID) !

ALTER TABLE ALIASEJB_TABLE add constraint FK2FOR_CUSTOMEREJB_TABLE Foreign Key (FK2_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(ID) !


ALTER TABLE FKS_FOR_ALIAS_CUSTOMER add constraint FKFOR_CUSTOMEREJB_TABLE Foreign Key (FK_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(ID) !

ALTER TABLE FKS_FOR_ALIAS_CUSTOMER add constraint FKFOR_ALIASEJB_TABLE Foreign Key (FK_FOR_ALIASEJB_TABLE) references ALIASEJB_TABLE(ID) !

ALTER TABLE CREDITCARDEJB_TABLE add constraint FK3FOR_CUSTOMEREJB_TABLE Foreign Key (FK3_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(ID) !

ALTER TABLE CREDITCARDEJB_TABLE add constraint FKFOR_ORDEREJB_TABLE Foreign Key (FK_FOR_ORDEREJB_TABLE) references ORDEREJB_TABLE(ID) !

ALTER TABLE ORDEREJB_TABLE add constraint FK4FOR_CUSTOMEREJB_TABLE Foreign Key (FK4_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(ID) !

ALTER TABLE ORDEREJB_TABLE add constraint FK0FOR_LINEITEMEJB_TABLE Foreign Key (FK0_FOR_LINEITEMEJB_TABLE) references LINEITEMEJB_TABLE(ID) !


ALTER TABLE LINEITEMEJB_TABLE add constraint FKFOR_PRODUCTEJB_TABLE Foreign Key (FK_FOR_PRODUCTEJB_TABLE) references PRODUCTEJB_TABLE(ID) !

ALTER TABLE LINEITEMEJB_TABLE add constraint FK1FOR_ORDEREJB_TABLE Foreign Key (FK1_FOR_ORDEREJB_TABLE) references ORDEREJB_TABLE(ID) !

drop table LRAPITEST_TABLE1 !
create table LRAPITEST_TABLE1 (ID  INTEGER NOT NULL, NAME varchar(25), VALUE  REAL, constraint LRAPITESTTABLE1 primary key(ID)) !

drop table LRAPITEST_TABLE2 !
create table LRAPITEST_TABLE2 (ID  INTEGER NOT NULL, NAME varchar(25), VALUE REAL, constraint LRAPITESTTABLE2 primary key(ID)) !

drop table LRAPITEST_TABLE3 !
create table LRAPITEST_TABLE3 (ID  varchar(25) NOT NULL, NAME  varchar(25), VALUE REAL, constraint LRAPITESTTABLE3 primary key(ID)) !

drop table COMPAT_ENTITYCMP_TABLE1 !
create table COMPAT_ENTITYCMP_TABLE1 (KEY_ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE  REAL, constraint COMPAT_ENTITYCMP_TAB1 primary key(KEY_ID))  !

drop table TX_NOT_TABLE3 !
create table TX_NOT_TABLE3 (KEY_ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE  REAL, constraint TX_NOTTABLE3 primary key(KEY_ID)) !

drop table TX_NOT_TABLE4 !
create table TX_NOT_TABLE4 (KEY_ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE  REAL, constraint TX_NOTTABLE4 primary key(KEY_ID)) !

drop table CMP11PK_TABLE1 !
create table CMP11PK_TABLE1 ( CMPID varchar(25) NOT NULL, CMPBRANDNAME  varchar(25), CMPPRICE REAL, constraint CMP11PKTABLE1 primary key(CMPID)) !

drop table CMP11PK_TABLE2 !
create table CMP11PK_TABLE2 ( CMPID INTEGER NOT NULL, CMPBRANDNAME  varchar(25), CMPPRICE REAL, constraint CMP11PKTABLE2 primary key(CMPID)) !

drop table CMP11PK_TABLE3 !
create table CMP11PK_TABLE3 ( CMPID REAL NOT NULL, CMPBRANDNAME  varchar(25), CMPPRICE REAL, constraint CMP11PKTABLE3 primary key(CMPID)) !

drop table CMP11PK_TABLE4 !
create table CMP11PK_TABLE4 ( PMIDINTEGER INTEGER NOT NULL, PMIDSTRING  varchar(25) NOT NULL, PMIDFLOAT  REAL NOT NULL, CMPBRANDNAME VARCHAR(25), CMPPRICE REAL, constraint CMP11PKTABLE4  primary key(PMIDINTEGER,PMIDSTRING,PMIDFLOAT)) !
   
drop table CMP20_DEP_PKEY_TABLE1 !
create table CMP20_DEP_PKEY_TABLE1 ( KEY_ID  numeric NOT NULL, BRAND_NAME  varchar(25), PRICE  real, constraint CMP20_DEPPKEY_TABLE1 primary key(KEY_ID)) !

drop table  CMP20_DEP_PKEY_TABLE2 !
create table CMP20_DEP_PKEY_TABLE2 ( KEY_ID  REAL NOT NULL, BRAND_NAME  varchar(25), PRICE  real, constraint CMP20_DEPPKEY_TABLE2 primary key(KEY_ID)) !

drop table CMP20_DEP_PKEY_TABLE3 !
create table CMP20_DEP_PKEY_TABLE3 ( KEY_ID varchar(50) NOT NULL, BRAND_NAME  varchar(25), PRICE  real, constraint CMP20_DEPPKEY_TABLE3 primary key(KEY_ID)) !

drop table CMP20_DEP_PKEY_TABLE4 !
create table CMP20_DEP_PKEY_TABLE4 ( PMIDINTEGER INTEGER NOT NULL, PMIDSTRING  varchar(25) NOT NULL, PMIDFLOAT  REAL NOT NULL, BRANDNAME VARCHAR(25), PRICE REAL, constraint CMP20_DEPPKEY_TABLE4 primary key(PMIDINTEGER,PMIDSTRING,PMIDFLOAT)) !
    

drop table TABLER5_DELETE !
CREATE TABLE TABLER5_DELETE ( ID VARCHAR(255)  NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC , FK1_FOR_TABLER6_DELETE_ID VARCHAR(255) , FK2_FOR_TABLER6_DELETE_ID VARCHAR(255) , FK1_FOR_TABLER7_DELETE_ID VARCHAR(255) , FK2_FOR_TABLER7_DELETE_ID VARCHAR(255), constraint TABLER5DELETE primary key(ID) ) !

drop table TABLER6_DELETE !
CREATE TABLE  TABLER6_DELETE ( ID VARCHAR(255)  NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC, constraint TABLER6DELETE primary key(ID)) !

drop table TABLER7_DELETE !
CREATE TABLE TABLER7_DELETE ( ID  VARCHAR(255) NOT NULL, NAME VARCHAR(255), VALUE NUMERIC , FK_FOR_TABLER6_DELETE_ID VARCHAR(255), constraint TABLER7DELETE primary key(ID)) !

ALTER TABLE TABLER5_DELETE add constraint FK1FOR_TABLER6_DELETE_ID Foreign Key (FK1_FOR_TABLER6_DELETE_ID) references TABLER6_DELETE(ID) !
ALTER TABLE TABLER5_DELETE add constraint FK2FOR_TABLER6_DELETE_ID Foreign Key (FK2_FOR_TABLER6_DELETE_ID) references TABLER6_DELETE(ID) !
ALTER TABLE TABLER5_DELETE add constraint FK1FOR_TABLER7_DELETE_ID Foreign Key (FK1_FOR_TABLER7_DELETE_ID) references TABLER7_DELETE(ID) !
ALTER TABLE TABLER5_DELETE add constraint FK2FOR_TABLER7_DELETE_ID Foreign Key (FK2_FOR_TABLER7_DELETE_ID) references TABLER7_DELETE(ID) !
ALTER TABLE TABLER7_DELETE add constraint FKFOR_TABLER6_DELETE_ID Foreign Key (FK_FOR_TABLER6_DELETE_ID) references TABLER6_DELETE(ID) !



drop table CMP20_LSECP_TABLE1 !
create table CMP20_LSECP_TABLE1 ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20LSECP_TABLE1 primary key(ID) ) !

drop table CMP20_LSECP_TABLE2 !
create table CMP20_LSECP_TABLE2  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20LSECP_TABLE2 primary key(ID)) !

drop table CMP20_LSECP_TABLE3 !
create table CMP20_LSECP_TABLE3  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20LSECP_TABLE3 primary key(ID)) !

drop table  CMP20_LSECR_TABLE1 !
create table CMP20_LSECR_TABLE1 ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20LSECR_TABLE1 primary key(ID)) !

drop table CMP20_LSECR_TABLE2 !
create table CMP20_LSECR_TABLE2  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20LSECR_TABLE2 primary key(ID)) !

drop table CMP20_LSECR_TABLE3 !
create table CMP20_LSECR_TABLE3  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20LSECR_TABLE3 primary key(ID)) !

drop table CMP20_SEC_TABLE1 !
create table CMP20_SEC_TABLE1 ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20SEC_TABLE1 primary key(ID)) !

drop table CMP20_SEC_TABLE2 !
create table CMP20_SEC_TABLE2  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20SEC_TABLE2 primary key(ID)) !


drop table CMP20_SECP_TABLE1 !
create table CMP20_SECP_TABLE1 ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20SECP_TABLE1 primary key(ID)) !

drop table CMP20_SECP_TABLE2 !
create table CMP20_SECP_TABLE2  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20SECP_TABLE2 primary key(ID)) !

drop table CMP20_SECP_TABLE3  !
create table CMP20_SECP_TABLE3  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20SECP_TABLE3 primary key(ID)) !

drop table CMP_SEC_TABLE1 !
create table CMP_SEC_TABLE1 ( ID INTEGER  NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP_SECTABLE1 primary key(ID) ) !

drop table CMP_SEC_TABLE2 !
create table CMP_SEC_TABLE2  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP_SECTABLE2  primary key(ID)) !

drop table  CMP_SECP_TABLE1 !
create table CMP_SECP_TABLE1 ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP_SECPTABLE1 primary key(ID)) !

drop table CMP_SECP_TABLE2 !
create table CMP_SECP_TABLE2  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP_SECPTABLE2 primary key(ID)) !

drop table CMP_SECP_TABLE3 !
create table CMP_SECP_TABLE3  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP_SECPTABLE primary key(ID) ) !

drop table CMP20_SECRASP_TABLE1 !
create table CMP20_SECRASP_TABLE1 ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20SECRASP_TABLE1 primary key(ID)) !

drop table CMP20_SECRASP_TABLE2 !
create table CMP20_SECRASP_TABLE2  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20SECRASP_TABLE2 primary key(ID)) !

drop table CMP20_SECRASP_TABLE3 !
create table CMP20_SECRASP_TABLE3  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMP20SECRASP_TABLE3 primary key(ID)) !

drop table CMP_SECRASP_TABLE1 !
create table CMP_SECRASP_TABLE1 ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMPSECRASP_TABLE1 primary key(ID)) !

drop table CMP_SECRASP_TABLE2 !
create table CMP_SECRASP_TABLE2  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMPSECRASP_TABLE2 primary key(ID) ) !

drop table CMP_SECRASP_TABLE3  !
create table CMP_SECRASP_TABLE3  ( ID INTEGER NOT NULL, BRAND_NAME  varchar(25), PRICE REAL, constraint CMPSECRASP_TABLE3 primary key(ID) ) !

DROP table TIMER_TABLE1!
CREATE TABLE TIMER_TABLE1 (KEY_ID INTEGER NOT NULL,  BRAND_NAME VARCHAR(255), PRICE REAL NOT NULL, CONSTRAINT TIMERTABLE1 PRIMARY KEY (KEY_ID)) !

DROP table TIMER_FLAGSTORE!
CREATE TABLE TIMER_FLAGSTORE (KEY_ID INTEGER NOT NULL, BRAND_NAME VARCHAR(255) , PRICE REAL NOT NULL, REQUIRESNEWACCESSED SMALLINT NOT NULL, REQUIREDACCESSED SMALLINT NOT NULL , CONSTRAINT TIMERFLAGSTORE PRIMARY KEY (KEY_ID)) !

DROP table CMP20_JACC_TABLE1!
CREATE TABLE CMP20_JACC_TABLE1 (ARG1 VARCHAR(255) NOT NULL, ARG2 INTEGER NOT NULL,  ARG3 INTEGER NOT NULL, CONSTRAINT CMP20JACC_TABLE1 PRIMARY KEY (ARG1,ARG2,ARG3)) !

DROP table FKS_ALIASNOOP_CUSTNOOP !
CREATE TABLE FKS_ALIASNOOP_CUSTNOOP( FK8_FOR_CUSTOMEREJB_TABLE VARCHAR(255) , FK2_FOR_ALIASEJB_TABLE VARCHAR(255)) !


DROP table SPOUSEEJB_TABLE!
CREATE TABLE SPOUSEEJB_TABLE(ID VARCHAR(255) PRIMARY KEY NOT NULL,  FIRSTNAME VARCHAR(255), MAIDENNAME VARCHAR(255), LASTNAME VARCHAR(255), SOCSECNUM VARCHAR(255), FK7_FOR_CUSTOMEREJB_TABLE VARCHAR(255), FK_FOR_INFOEJB_TABLE VARCHAR(255))!

DROP table INFOEJB_TABLE!
CREATE TABLE INFOEJB_TABLE(ID VARCHAR(255) PRIMARY KEY NOT NULL, INFOSTREET VARCHAR(255), INFOCITY VARCHAR(255), INFOSTATE VARCHAR(255), INFOZIP VARCHAR(255), FK_FOR_SPOUSEEJB_TABLE VARCHAR(255)) !

ALTER TABLE COMPLEXPK_TABLE1 add constraint FKFOR_LINEITEMS  Foreign Key (FK_FOR_LINEITEMS) references COMPLEXPK_LINEITEM_TABLE1(ID) !

ALTER TABLE COMPLEXPK_LINEITEM_TABLE1 add constraint FKFOR_ID Foreign Key (FK_FOR_ID, FK_FOR_BRANDNAME) references COMPLEXPK_TABLE1(ID,BRANDNAME) !

ALTER TABLE FKS_ALIASNOOP_CUSTNOOP  add constraint FK2FOR_ALIASEJB_TAB Foreign Key (FK2_FOR_ALIASEJB_TABLE) references ALIASEJB_TABLE(ID) !

ALTER TABLE FKS_ALIASNOOP_CUSTNOOP  add constraint FK8FOR_CUSTOMEREJB_TAB Foreign Key (FK8_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(ID) !


ALTER TABLE SPOUSEEJB_TABLE add constraint FK7FOR_CUSTOMEREJB_TAB Foreign Key (FK7_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(ID) !

ALTER TABLE SPOUSEEJB_TABLE add constraint FKFOR_INFOEJB_TAB Foreign Key (FK_FOR_INFOEJB_TABLE) references INFOEJB_TABLE(ID) !

ALTER TABLE INFOEJB_TABLE add constraint FKFOR_SPOUSEEJB_TAB Foreign Key (FK_FOR_SPOUSEEJB_TABLE) references SPOUSEEJB_TABLE(ID) !

DROP TABLE EMPLOYEEEJB !
CREATE TABLE EMPLOYEEEJB (HIREDATE DATETIME NULL, ID INTEGER NOT NULL, FIRSTNAME VARCHAR(256) NULL, SALARY REAL NOT NULL, LASTNAME VARCHAR(256) NULL, EMPLOYEEEJB_ID INTEGER NULL, DEPARTMENTEJB_ID INTEGER NULL, CONSTRAINT PK_EMPLOYEEEJB PRIMARY KEY (ID)) !

DROP TABLE DEPARTMENTEJB !
CREATE TABLE DEPARTMENTEJB (NAME VARCHAR(256) NULL, ID INTEGER NOT NULL, CONSTRAINT PK_DEPARTMENTEJB PRIMARY KEY (ID)) !

ALTER TABLE EMPLOYEEEJB ADD CONSTRAINT FK_MANAGER FOREIGN KEY (EMPLOYEEEJB_ID) REFERENCES EMPLOYEEEJB (ID) !
ALTER TABLE EMPLOYEEEJB ADD CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEPARTMENTEJB_ID) REFERENCES DEPARTMENTEJB (ID) !

