*{techID}10* The functional programmatic behavior of any tag must be
that defined by the Specifications.

*{techID}11* The Product must contain the full set of Tag Libraries
defined by the specification for the Technology Under Test. No
subsetting, supersetting, or modifications of the Tag Libraries within
the defined URI Namespace are allowed except only as specifically
exempted by these Rules.

*{techID}11.1* If a Product includes Technologies in addition to the
Technology Under Test, then it must contain the full set of combined
Tag Libraries. The Tag Libraries supported by the Product must contain
the union of the included Technologies. No further subsetting,
supersetting, or modifications to the Tag Libraries of the included
Technologies are allowed.
