<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<definitions
  name="IntraModuleService"
  targetNamespace="http://IntraModuleService.org/wsdl"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:types="http://IntraModuleService.org/types"
  xmlns:tns="http://IntraModuleService.org/wsdl">
  
  <types>
    <xsd:schema
        targetNamespace="http://IntraModuleService.org/types"
        attributeFormDefault="qualified"
        elementFormDefault="qualified">

      <xsd:element name="IntraRequest">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="argument" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name="IntraResponse">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="argument" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </types>

  <message name="IntraRequest">
    <part name="parameters" element="types:IntraRequest"/>
  </message>
  
  <message name="IntraResponse">
    <part name="parameters" element="types:IntraResponse"/>
  </message>  

  <portType name="IntraModuleSei">
    <operation name="sayIntra">
      <input message="tns:IntraRequest"/>
      <output message="tns:IntraResponse"/>
    </operation>  
  </portType>
  
  <binding name="IntraModuleSeiBinding" type="tns:IntraModuleSei">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="sayIntra">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>      
  </binding>
    
  <service name="IntraModuleService">
    <port name="IntraModuleSeiPort" binding="tns:IntraModuleSeiBinding">
      <soap:address location="http://foo:9999/bar"/>
    </port>
  </service>
  
</definitions>
