DROP TABLE ctstable1!
CREATE TABLE ctstable1 ( TYPE_ID INT NOT NULL, TYPE_DESC VARCHAR(32) NOT NULL, PRIMARY KEY (TYPE_ID))!

DROP TABLE ctstable2!
CREATE TABLE ctstable2 ( KEY_ID INT NOT NULL, COF_NAME VARCHAR(32) NOT NULL, PRICE DOUBLE NOT NULL, TYPE_ID INT NOT NULL, PRIMARY KEY (KEY_ID), FOREIGN KEY (TYPE_ID) REFERENCES ctstable1 )!

DROP TABLE concurrencetable!
CREATE TABLE concurrencetable ( TYPE_ID INT NOT NULL, TYPE_DESC VARCHAR(32) NOT NULL, PRIMARY KEY (TYPE_ID))!

DROP TABLE Numeric_Tab!
CREATE TABLE Numeric_Tab ( MAX_VAL DECIMAL(30,15) NOT NULL, MIN_VAL DECIMAL(30,15) NOT NULL, NULL_VAL DECIMAL(30,15))!

DROP TABLE Decimal_Tab!
CREATE TABLE Decimal_Tab ( MAX_VAL DECIMAL(30,15) NOT NULL, MIN_VAL DECIMAL(30,15) NOT NULL, NULL_VAL DECIMAL(30,15))!

DROP TABLE Double_Tab!
CREATE TABLE Double_Tab ( MAX_VAL DOUBLE NOT NULL, MIN_VAL DOUBLE NOT NULL, NULL_VAL DOUBLE)!

DROP TABLE Float_Tab!
CREATE TABLE Float_Tab ( MAX_VAL DOUBLE NOT NULL, MIN_VAL DOUBLE NOT NULL, NULL_VAL DOUBLE)!

DROP TABLE Real_Tab!
CREATE TABLE Real_Tab ( MAX_VAL REAL NOT NULL, MIN_VAL REAL NOT NULL, NULL_VAL REAL)!

DROP TABLE Bit_Tab!
CREATE TABLE Bit_Tab ( MAX_VAL SMALLINT NOT NULL, MIN_VAL SMALLINT NOT NULL, NULL_VAL SMALLINT)!

DROP TABLE Smallint_Tab!
CREATE TABLE Smallint_Tab ( MAX_VAL SMALLINT NOT NULL, MIN_VAL SMALLINT NOT NULL, NULL_VAL SMALLINT)!

DROP TABLE Tinyint_Tab!
CREATE TABLE Tinyint_Tab ( MAX_VAL SMALLINT NOT NULL, MIN_VAL SMALLINT NOT NULL, NULL_VAL SMALLINT)!

DROP TABLE Integer_Tab!
CREATE TABLE Integer_Tab ( MAX_VAL INT NOT NULL, MIN_VAL INT NOT NULL, NULL_VAL INT)!

DROP TABLE Bigint_Tab!
CREATE TABLE Bigint_Tab ( MAX_VAL DECIMAL(20,0) NOT NULL, MIN_VAL DECIMAL(20,0) NOT NULL, NULL_VAL DECIMAL(20,0))!

DROP TABLE Char_Tab!
CREATE TABLE Char_Tab ( COFFEE_NAME CHAR(30) NOT NULL, NULL_VAL VARCHAR(30))!

DROP TABLE Varchar_Tab!
CREATE TABLE Varchar_Tab ( COFFEE_NAME VARCHAR(30) NOT NULL, NULL_VAL VARCHAR(30))!

DROP TABLE Longvarchar_Tab!
CREATE TABLE Longvarchar_Tab ( COFFEE_NAME VARCHAR(448) NOT NULL)!

DROP TABLE Longvarcharnull_Tab!
CREATE TABLE Longvarcharnull_Tab ( NULL_VAL VARCHAR(448))!

DROP TABLE Date_Tab!
CREATE TABLE Date_Tab ( MFG_DATE DATE , NULL_VAL DATE )!

DROP TABLE Time_Tab!
CREATE TABLE Time_Tab ( BRK_TIME TIME NOT NULL, NULL_VAL TIME)!

DROP TABLE Timestamp_Tab!
CREATE TABLE Timestamp_Tab ( IN_TIME TIMESTAMP NOT NULL, NULL_VAL TIMESTAMP)!

DROP TABLE Binary_Tab!
CREATE TABLE Binary_Tab ( BINARY_VAL VARCHAR(24) FOR BIT DATA)!

DROP TABLE Varbinary_Tab!
CREATE TABLE Varbinary_Tab ( VARBINARY_VAL VARCHAR(255) FOR BIT DATA)!

DROP TABLE Longvarbinary_Tab!
CREATE TABLE Longvarbinary_Tab ( LONGVARBINARY_VAL VARCHAR(255) FOR BIT DATA)!

DROP TABLE ctstable3!
CREATE TABLE ctstable3 ( STRING1 VARCHAR(20) NOT NULL, STRING2 VARCHAR(20) NOT NULL, STRING3 VARCHAR(20) NOT NULL, NUMCOL INTEGER NOT NULL, FLOATCOL DOUBLE NOT NULL, DATECOL DATE NOT NULL, TIMECOL TIME NOT NULL, TSCOL1 TIMESTAMP NOT NULL, TSCOL2 TIMESTAMP NOT NULL)!

DROP TABLE ctstable4!
CREATE TABLE ctstable4 ( STRING4 VARCHAR(20) NOT NULL, NUMCOL DECIMAL(18,0) NOT NULL)!

DROP TABLE TxBean_Tab1!
CREATE TABLE TxBean_Tab1 ( KEY_ID INT NOT NULL, TABONE_NAME VARCHAR(32) NOT NULL, PRICE DOUBLE NOT NULL)!

DROP TABLE TxBean_Tab2!
CREATE TABLE TxBean_Tab2 ( KEY_ID INT NOT NULL, TABTWO_NAME VARCHAR(32) NOT NULL, PRICE DOUBLE NOT NULL)!

DROP TABLE TxEBean_Tab!
CREATE TABLE TxEBean_Tab ( KEY_ID INT NOT NULL, BRAND_NAME VARCHAR(32) NOT NULL, PRICE DOUBLE NOT NULL, PRIMARY KEY (KEY_ID))!

DROP TABLE Integration_Tab!
CREATE TABLE Integration_Tab ( ACCOUNT INT NOT NULL, BALANCE DOUBLE NOT NULL, PRIMARY KEY (ACCOUNT))!

DROP TABLE Integration_Sec_Tab!
CREATE TABLE Integration_Sec_Tab ( LOG_NO INT NOT NULL, LINE_NO INT NOT NULL, MESSAGE VARCHAR(255) NOT NULL)!

DROP TABLE BB_Tab!
CREATE TABLE BB_Tab ( KEY_ID INT NOT NULL, BRAND_NAME VARCHAR(32) NOT NULL, PRICE DOUBLE NOT NULL, PRIMARY KEY (KEY_ID))!

DROP TABLE JTA_Tab1!
CREATE TABLE JTA_Tab1 ( KEY_ID INT NOT NULL, COF_NAME VARCHAR(32) NOT NULL, PRICE DOUBLE NOT NULL)!

DROP TABLE JTA_Tab2!
CREATE TABLE JTA_Tab2 ( KEY_ID INT NOT NULL, CHOC_NAME VARCHAR(32) NOT NULL, PRICE DOUBLE NOT NULL)!

DROP TABLE Deploy_Tab1!
CREATE TABLE Deploy_Tab1 ( KEY_ID INT NOT NULL, BRAND_NAME VARCHAR(32) NOT NULL, PRICE DOUBLE NOT NULL, PRIMARY KEY (KEY_ID))!

DROP TABLE Deploy_Tab2!
CREATE TABLE Deploy_Tab2 ( KEY_ID VARCHAR(100) NOT NULL, BRAND_NAME VARCHAR(32) NOT NULL, PRICE DOUBLE NOT NULL, PRIMARY KEY (KEY_ID))!


DROP TABLE Deploy_Tab3!
CREATE TABLE Deploy_Tab3 ( KEY_ID INT NOT NULL, BRAND_NAME VARCHAR(32) NOT NULL, PRICE DOUBLE NOT NULL, PRIMARY KEY (KEY_ID))!

DROP TABLE Deploy_Tab4 !
CREATE TABLE Deploy_Tab4 (KEY_ID FLOAT NOT NULL, BRAND_NAME varchar(32), PRICE FLOAT, primary key(KEY_ID)) !

DROP TABLE Deploy_Tab5 !
CREATE TABLE Deploy_Tab5 (KEY_ID1 int NOT NULL, KEY_ID2 varchar(100) NOT NULL, KEY_ID3 float NOT NULL, BRAND_NAME varchar(32), PRICE float, primary key(KEY_ID1, KEY_ID2, KEY_ID3)) !

DROP TABLE Xa_Tab1!
CREATE TABLE Xa_Tab1 ( col1 INT NOT NULL, col2 VARCHAR(32) NOT NULL, col3 VARCHAR(32) NOT NULL, PRIMARY KEY (col1))!

DROP TABLE Xa_Tab2!
CREATE TABLE Xa_Tab2 ( col1 INT NOT NULL, col2 VARCHAR(32) NOT NULL, col3 VARCHAR(32) NOT NULL, PRIMARY KEY (col1))!

DROP TABLE SEC_Tab1!
CREATE TABLE SEC_Tab1 ( KEY_ID INT NOT NULL, PRICE DOUBLE NOT NULL, BRAND VARCHAR(32) NOT NULL, PRIMARY KEY (KEY_ID))!

DROP TABLE Connector_Tab!
CREATE TABLE Connector_Tab ( KEY_ID INT NOT NULL, PRODUCT_NAME VARCHAR(32) NOT NULL, PRICE DOUBLE NOT NULL)!

drop table Coffee_Table !
create table Coffee_Table (KEY_ID INTEGER NOT NULL, BRAND_NAME varchar(32) NOT NULL, PRICE float NOT NULL, primary key(KEY_ID)) !

drop table Coffee_StringPK_Table !
create table Coffee_StringPK_Table (KEY_ID VARCHAR(100) NOT NULL, BRAND_NAME varchar(32) NOT NULL, PRICE float NOT NULL, primary key(KEY_ID)) !

drop table Coffee_LongPK_Table !
create table Coffee_LongPK_Table (KEY_ID NUMERIC(28) NOT NULL, BRAND_NAME varchar(32) NOT NULL, PRICE float NOT NULL, primary key(KEY_ID)) !

drop table Coffee_FloatPK_Table !
create table Coffee_FloatPK_Table (KEY_ID FLOAT NOT NULL, BRAND_NAME varchar(32) NOT NULL, PRICE float NOT NULL, primary key(KEY_ID)) !

drop table Coffee_CompoundPK_Table !
create table Coffee_CompoundPK_Table (KEY_ID1 int NOT NULL, KEY_ID2 varchar(100) NOT NULL, KEY_ID3 float NOT NULL, BRAND_NAME varchar(32) NOT NULL, PRICE float NOT NULL, primary key(KEY_ID1, KEY_ID2, KEY_ID3)) !

DROP TABLE COFFEEEJBLITE !
CREATE TABLE COFFEEEJBLITE (ID INT PRIMARY KEY NOT NULL, BRANDNAME VARCHAR(25), PRICE REAL ) !

DROP TABLE EJB_AUTOCLOSE_TAB !
CREATE TABLE EJB_AUTOCLOSE_TAB (NAME VARCHAR(25) NOT NULL, MESSAGE VARCHAR(25) NOT NULL)!