/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

// This class was generated by the JAXRPC RI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Reference Implementation (1.1, build EA-R15)

package com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest;

public class Base64BinaryTest {
  protected byte[] base64Binary_1;

  public Base64BinaryTest() {
  }

  public Base64BinaryTest(byte[] base64Binary_1) {
    this.base64Binary_1 = base64Binary_1;
  }

  public byte[] getBase64Binary_1() {
    return base64Binary_1;
  }

  public void setBase64Binary_1(byte[] base64Binary_1) {
    this.base64Binary_1 = base64Binary_1;
  }
}
