/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

// This class was generated by the JAXRPC RI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Reference Implementation (1.1, build EA-R15)

package com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest;

public class JavaBean2 {
  protected java.math.BigDecimal myBigDecimal;

  protected double myDouble;

  protected long myLong;

  protected short myShort;

  protected int myInt;

  protected java.util.Calendar myCalendar;

  protected byte myByte;

  protected boolean myBoolean;

  protected java.lang.String myString;

  protected java.math.BigInteger myBigInteger;

  protected float myFloat;

  public JavaBean2() {
  }

  public JavaBean2(java.math.BigDecimal myBigDecimal, double myDouble,
      long myLong, short myShort, int myInt, java.util.Calendar myCalendar,
      byte myByte, boolean myBoolean, java.lang.String myString,
      java.math.BigInteger myBigInteger, float myFloat) {
    this.myBigDecimal = myBigDecimal;
    this.myDouble = myDouble;
    this.myLong = myLong;
    this.myShort = myShort;
    this.myInt = myInt;
    this.myCalendar = myCalendar;
    this.myByte = myByte;
    this.myBoolean = myBoolean;
    this.myString = myString;
    this.myBigInteger = myBigInteger;
    this.myFloat = myFloat;
  }

  public java.math.BigDecimal getMyBigDecimal() {
    return myBigDecimal;
  }

  public void setMyBigDecimal(java.math.BigDecimal myBigDecimal) {
    this.myBigDecimal = myBigDecimal;
  }

  public double getMyDouble() {
    return myDouble;
  }

  public void setMyDouble(double myDouble) {
    this.myDouble = myDouble;
  }

  public long getMyLong() {
    return myLong;
  }

  public void setMyLong(long myLong) {
    this.myLong = myLong;
  }

  public short getMyShort() {
    return myShort;
  }

  public void setMyShort(short myShort) {
    this.myShort = myShort;
  }

  public int getMyInt() {
    return myInt;
  }

  public void setMyInt(int myInt) {
    this.myInt = myInt;
  }

  public java.util.Calendar getMyCalendar() {
    return myCalendar;
  }

  public void setMyCalendar(java.util.Calendar myCalendar) {
    this.myCalendar = myCalendar;
  }

  public byte getMyByte() {
    return myByte;
  }

  public void setMyByte(byte myByte) {
    this.myByte = myByte;
  }

  public boolean isMyBoolean() {
    return myBoolean;
  }

  public void setMyBoolean(boolean myBoolean) {
    this.myBoolean = myBoolean;
  }

  public java.lang.String getMyString() {
    return myString;
  }

  public void setMyString(java.lang.String myString) {
    this.myString = myString;
  }

  public java.math.BigInteger getMyBigInteger() {
    return myBigInteger;
  }

  public void setMyBigInteger(java.math.BigInteger myBigInteger) {
    this.myBigInteger = myBigInteger;
  }

  public float getMyFloat() {
    return myFloat;
  }

  public void setMyFloat(float myFloat) {
    this.myFloat = myFloat;
  }
}
