/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

// This class was generated by the JAXRPC RI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Reference Implementation (1.1, build EA-R13)

package com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest;

public interface MarshallTest extends java.rmi.Remote {
  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.BigDecimalArrayTestResponse bigDecimalArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.BigDecimalArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.BigDecimalTestResponse bigDecimalTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.BigDecimalTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.BigIntegerArrayTestResponse bigIntegerArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.BigIntegerArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.BigIntegerTestResponse bigIntegerTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.BigIntegerTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.BooleanArrayTestResponse booleanArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.BooleanArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.BooleanTestResponse booleanTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.BooleanTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.ByteArrayTestResponse byteArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.ByteArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.ByteTestResponse byteTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.ByteTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.QNameTestResponse qnameTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.QNameTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.Base64BinaryTestResponse base64BinaryTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.Base64BinaryTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.HexBinaryTestResponse hexBinaryTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.HexBinaryTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.QNameArrayTestResponse qnameArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.QNameArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.CalendarArrayTestResponse calendarArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.CalendarArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.CalendarTestResponse calendarTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.CalendarTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.DoubleArrayTestResponse doubleArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.DoubleArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.DoubleTestResponse doubleTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.DoubleTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.FloatArrayTestResponse floatArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.FloatArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.FloatTestResponse floatTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.FloatTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.IntArrayTestResponse intArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.IntArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.IntTestResponse intTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.IntTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.JavaBeanArrayTestResponse javaBeanArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.JavaBeanArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.JavaBeanTestResponse javaBeanTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.JavaBeanTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.LongArrayTestResponse longArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.LongArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.LongTestResponse longTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.LongTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.ShortArrayTestResponse shortArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.ShortArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.ShortTestResponse shortTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.ShortTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.StringArrayTestResponse stringArrayTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.StringArrayTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.StringTestResponse stringTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.StringTest parameters)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.VoidTestResponse voidTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.marshalltest.VoidTest parameters)
      throws java.rmi.RemoteException;
}
