/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

// This class was generated by the JAXRPC RI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Reference Implementation (1.1, build EA-R15)

package com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest;

public class FooAnonymous {
  protected boolean fooC;

  protected java.lang.String fooA;

  protected int fooB;

  public FooAnonymous() {
  }

  public FooAnonymous(boolean fooC, java.lang.String fooA, int fooB) {
    this.fooC = fooC;
    this.fooA = fooA;
    this.fooB = fooB;
  }

  public boolean isFooC() {
    return fooC;
  }

  public void setFooC(boolean fooC) {
    this.fooC = fooC;
  }

  public java.lang.String getFooA() {
    return fooA;
  }

  public void setFooA(java.lang.String fooA) {
    this.fooA = fooA;
  }

  public int getFooB() {
    return fooB;
  }

  public void setFooB(int fooB) {
    this.fooB = fooB;
  }
}
