/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R55)

package com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest;

public class FooAnyURIType {
  protected java.net.URI fooAnyURIType;

  public FooAnyURIType() {
  }

  public FooAnyURIType(java.net.URI fooAnyURIType) {
    this.fooAnyURIType = fooAnyURIType;
  }

  public java.net.URI getFooAnyURIType() {
    return fooAnyURIType;
  }

  public void setFooAnyURIType(java.net.URI fooAnyURIType) {
    this.fooAnyURIType = fooAnyURIType;
  }
}
