/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

// This class was generated by the JAXRPC RI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Reference Implementation (1.1, build EA-R15)

package com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest;

public class FooVariousSchemaTypes {
  protected int fooA;

  protected java.math.BigInteger fooB;

  protected java.lang.String fooC;

  protected java.lang.String fooD;

  protected long fooE;

  protected short fooF;

  public FooVariousSchemaTypes() {
  }

  public FooVariousSchemaTypes(int fooA, java.math.BigInteger fooB,
      java.lang.String fooC, java.lang.String fooD, long fooE, short fooF) {
    this.fooA = fooA;
    this.fooB = fooB;
    this.fooC = fooC;
    this.fooD = fooD;
    this.fooE = fooE;
    this.fooF = fooF;
  }

  public int getFooA() {
    return fooA;
  }

  public void setFooA(int fooA) {
    this.fooA = fooA;
  }

  public java.math.BigInteger getFooB() {
    return fooB;
  }

  public void setFooB(java.math.BigInteger fooB) {
    this.fooB = fooB;
  }

  public java.lang.String getFooC() {
    return fooC;
  }

  public void setFooC(java.lang.String fooC) {
    this.fooC = fooC;
  }

  public java.lang.String getFooD() {
    return fooD;
  }

  public void setFooD(java.lang.String fooD) {
    this.fooD = fooD;
  }

  public long getFooE() {
    return fooE;
  }

  public void setFooE(long fooE) {
    this.fooE = fooE;
  }

  public short getFooF() {
    return fooF;
  }

  public void setFooF(short fooF) {
    this.fooF = fooF;
  }
}
