/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Reference Implementation (1.1, build EA-R18)

package com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest;

public interface NewSchemaTest extends java.rmi.Remote {
  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.IncludedStringResponse echoIncludedStringTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.IncludedStringRequest params)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooStatusType sendFoo1Test(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooType foo1Request)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooType sendFoo2Test(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooType foo2Request)
      throws java.rmi.RemoteException;

  public java.lang.String echoNormalizedStringTypeTest(
      java.lang.String fooITypeRequest) throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooVariousSchemaTypes echoVariousSchemaTypesTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooVariousSchemaTypes fooVariousSchemaTypesRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooVariousSchemaTypesListType echoVariousSchemaTypesListTypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooVariousSchemaTypesListType fooVariousSchemaTypesListTypeRequest)
      throws java.rmi.RemoteException;

  public java.math.BigInteger echoIntegerRangeTypeTest(
      java.math.BigInteger fooIntegerRangeTypeRequest)
      throws java.rmi.RemoteException;

  public java.lang.String[] echoStringListTypeTest(
      java.lang.String[] fooStringListTypeRequest)
      throws java.rmi.RemoteException;

  public float[] echoFloatListTypeTest(float[] fooFloatListTypeRequest)
      throws java.rmi.RemoteException;

  public int[] echoIntListTypeTest(int[] fooIntListTypeRequest)
      throws java.rmi.RemoteException;

  public java.math.BigDecimal[] echoDecimalListTypeTest(
      java.math.BigDecimal[] fooDecimalListTypeRequest)
      throws java.rmi.RemoteException;

  public double[] echoDoubleListTypeTest(double[] fooDoubleListTypeRequest)
      throws java.rmi.RemoteException;

  public java.math.BigInteger[] echoIntegerListTypeTest(
      java.math.BigInteger[] fooIntegerListTypeRequest)
      throws java.rmi.RemoteException;

  public long[] echoLongListTypeTest(long[] fooLongListTypeRequest)
      throws java.rmi.RemoteException;

  public short[] echoShortListTypeTest(short[] fooShortListTypeRequest)
      throws java.rmi.RemoteException;

  public byte[] echoByteListTypeTest(byte[] fooByteListTypeRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooStringEnumType echoStringEnumTypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooStringEnumType fooStringEnumTypeRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooByteEnumType echoByteEnumTypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooByteEnumType fooByteEnumTypeRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooShortEnumType echoShortEnumTypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooShortEnumType fooShortEnumTypeRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooIntegerEnumType echoIntegerEnumTypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooIntegerEnumType fooIntegerEnumTypeRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooIntEnumType echoIntEnumTypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooIntEnumType fooIntEnumTypeRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooLongEnumType echoLongEnumTypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooLongEnumType fooLongEnumTypeRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooDecimalEnumType echoDecimalEnumTypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooDecimalEnumType fooDecimalEnumTypeRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooFloatEnumType echoFloatEnumTypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooFloatEnumType fooFloatEnumTypeRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooDoubleEnumType echoDoubleEnumTypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooDoubleEnumType fooDoubleEnumTypeRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooAnonymousType echoAnonymousTypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooAnonymousType fooAnonymousTypeRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooAnnotationType echoAnnotationTypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooAnnotationType fooAnnotationTypeRequest)
      throws java.rmi.RemoteException;

  public java.lang.String echoAnySimpleTypeTest(
      java.lang.String fooAnySimpleTypeRequest) throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooAnyURIType echoAnyURITypeTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooAnyURIType fooAnyURITypeRequest)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooStringResponse fooFaultTest(
      com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooStringRequest fooStringRequest)
      throws com.sun.ts.tests.jaxrpc.ee.wsi.document.literal.marshalltest.FooFaultException,
      java.rmi.RemoteException;

  public java.lang.String echoLanguageTypeTest(java.lang.String body)
      throws java.rmi.RemoteException;

  public java.lang.String echoTokenTypeTest(java.lang.String body)
      throws java.rmi.RemoteException;

  public java.lang.String echoNameTypeTest(java.lang.String body)
      throws java.rmi.RemoteException;

  public java.lang.String echoNCNameTypeTest(java.lang.String body)
      throws java.rmi.RemoteException;

  public java.lang.String echoIDTypeTest(java.lang.String body)
      throws java.rmi.RemoteException;

  public int echoUnsignedShortTest(int body) throws java.rmi.RemoteException;

  public long echoUnsignedIntTest(long body) throws java.rmi.RemoteException;

  public short echoUnsignedByteTest(short body) throws java.rmi.RemoteException;

  public java.math.BigInteger echoUnsignedLongTest(java.math.BigInteger body)
      throws java.rmi.RemoteException;

  public java.math.BigInteger echoNonPositiveIntegerTest(
      java.math.BigInteger body) throws java.rmi.RemoteException;

  public java.math.BigInteger echoNonNegativeIntegerTest(
      java.math.BigInteger body) throws java.rmi.RemoteException;

  public java.math.BigInteger echoPositiveIntegerTest(java.math.BigInteger body)
      throws java.rmi.RemoteException;

  public java.math.BigInteger echoNegativeIntegerTest(java.math.BigInteger body)
      throws java.rmi.RemoteException;

  public java.util.Calendar echoTimeTest(java.util.Calendar body)
      throws java.rmi.RemoteException;

  public java.util.Calendar echoDateTest(java.util.Calendar body)
      throws java.rmi.RemoteException;

  public java.lang.String echoFooStringTypeTest(
      java.lang.String fooStringTypeRequest) throws java.rmi.RemoteException;

  public java.math.BigInteger echoFooIntegerTypeTest(
      java.math.BigInteger fooIntegerTypeRequest)
      throws java.rmi.RemoteException;

  public int echoFooIntTypeTest(int fooIntTypeRequest)
      throws java.rmi.RemoteException;

  public long echoFooLongTypeTest(long fooLongTypeRequest)
      throws java.rmi.RemoteException;

  public short echoFooShortTypeTest(short fooShortTypeRequest)
      throws java.rmi.RemoteException;

  public java.math.BigDecimal echoFooDecimalTypeTest(
      java.math.BigDecimal fooDecimalTypeRequest)
      throws java.rmi.RemoteException;

  public float echoFooFloatTypeTest(float fooFloatTypeResponse)
      throws java.rmi.RemoteException;

  public double echoFooDoubleTypeTest(double fooDoubleTypeResponse)
      throws java.rmi.RemoteException;

  public boolean echoFooBooleanTypeTest(boolean fooBooleanTypeResponse)
      throws java.rmi.RemoteException;

  public byte echoFooByteTypeTest(byte fooByteTypeResponse)
      throws java.rmi.RemoteException;

  public javax.xml.namespace.QName echoFooQNameTypeTest(
      javax.xml.namespace.QName fooQNameTypeResponse)
      throws java.rmi.RemoteException;
}
