/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

package com.sun.ts.tests.rmiiiop.ee.objecttests;

/**
 * com/sun/ts/tests/rmiiiop/ee/objecttests/HelloJAVAIDLObjectIntfHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.1" from
 * hello.idl Tuesday, August 27, 2002 3:28:00 PM PDT
 */

public final class HelloJAVAIDLObjectIntfHolder
    implements org.omg.CORBA.portable.Streamable {
  public com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntf value = null;

  public HelloJAVAIDLObjectIntfHolder() {
  }

  public HelloJAVAIDLObjectIntfHolder(
      com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntf initialValue) {
    value = initialValue;
  }

  public void _read(org.omg.CORBA.portable.InputStream i) {
    value = com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntfHelper
        .read(i);
  }

  public void _write(org.omg.CORBA.portable.OutputStream o) {
    com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntfHelper
        .write(o, value);
  }

  public org.omg.CORBA.TypeCode _type() {
    return com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntfHelper
        .type();
  }

}
