/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

package com.sun.ts.tests.rmiiiop.ee.objecttests;

/**
 * com/sun/ts/tests/rmiiiop/ee/objecttests/HelloJAVAIDLObjectIntfHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.1" from
 * hello.idl Tuesday, August 27, 2002 3:28:00 PM PDT
 */

abstract public class HelloJAVAIDLObjectIntfHelper {
  private static String _id = "IDL:com/sun/ts/tests/rmiiiop/ee/objecttests/HelloJAVAIDLObjectIntf:1.0";

  public static void insert(org.omg.CORBA.Any a,
      com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntf that) {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
    a.type(type());
    write(out, that);
    a.read_value(out.create_input_stream(), type());
  }

  public static com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntf extract(
      org.omg.CORBA.Any a) {
    return read(a.create_input_stream());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;

  synchronized public static org.omg.CORBA.TypeCode type() {
    if (__typeCode == null) {
      __typeCode = org.omg.CORBA.ORB.init().create_interface_tc(
          com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntfHelper
              .id(),
          "HelloJAVAIDLObjectIntf");
    }
    return __typeCode;
  }

  public static String id() {
    return _id;
  }

  public static com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntf read(
      org.omg.CORBA.portable.InputStream istream) {
    return narrow(istream.read_Object(_HelloJAVAIDLObjectIntfStub.class));
  }

  public static void write(org.omg.CORBA.portable.OutputStream ostream,
      com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntf value) {
    ostream.write_Object((org.omg.CORBA.Object) value);
  }

  public static com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntf narrow(
      org.omg.CORBA.Object obj) {
    if (obj == null)
      return null;
    else if (obj instanceof com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntf)
      return (com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntf) obj;
    else if (!obj._is_a(id()))
      throw new org.omg.CORBA.BAD_PARAM();
    else {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
          ._get_delegate();
      com.sun.ts.tests.rmiiiop.ee.objecttests._HelloJAVAIDLObjectIntfStub stub = new com.sun.ts.tests.rmiiiop.ee.objecttests._HelloJAVAIDLObjectIntfStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
