/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

package com.sun.ts.tests.rmiiiop.ee.objecttests;

/**
 * com/sun/ts/tests/rmiiiop/ee/objecttests/HelloJAVAIDLObjectIntfPOA.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.1" from
 * hello.idl Tuesday, August 27, 2002 3:27:59 PM PDT
 */

public abstract class HelloJAVAIDLObjectIntfPOA
    extends org.omg.PortableServer.Servant implements
    com.sun.ts.tests.rmiiiop.ee.objecttests.HelloJAVAIDLObjectIntfOperations,
    org.omg.CORBA.portable.InvokeHandler {

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable();
  static {
    _methods.put("hello", java.lang.Integer.valueOf(0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke(String $method,
      org.omg.CORBA.portable.InputStream in,
      org.omg.CORBA.portable.ResponseHandler $rh) {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION(0,
          org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue()) {
    case 0: // com/sun/ts/tests/rmiiiop/ee/objecttests/HelloJAVAIDLObjectIntf/hello
    {
      String $result = null;
      $result = this.hello();
      out = $rh.createReply();
      out.write_string($result);
      break;
    }

    default:
      throw new org.omg.CORBA.BAD_OPERATION(0,
          org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
      "IDL:com/sun/ts/tests/rmiiiop/ee/objecttests/HelloJAVAIDLObjectIntf:1.0" };

  public String[] _all_interfaces(org.omg.PortableServer.POA poa,
      byte[] objectId) {
    return (String[]) __ids.clone();
  }

  public HelloJAVAIDLObjectIntf _this() {
    return HelloJAVAIDLObjectIntfHelper.narrow(super._this_object());
  }

  public HelloJAVAIDLObjectIntf _this(org.omg.CORBA.ORB orb) {
    return HelloJAVAIDLObjectIntfHelper.narrow(super._this_object(orb));
  }

} // class HelloJAVAIDLObjectIntfPOA
