type=page
status=published
title=Setup and Configuration
next=using.html
prev=install.html
~~~~~~
Setup and Configuration
=======================

[[TCPER00005]][[GBFVV]]


[[setup-and-configuration]]
4 Setup and Configuration
-------------------------

This chapter describes how to set up the JTA TCK and JavaTest harness
software and how to configure. Before proceeding with the instructions
in this chapter, be sure to install all required software, as described
in .

After completing the instructions in this chapter, proceed to , for
instructions on running the JTA TCK.

This chapter includes the following topics:

* link:#GBFWN[Configuring Your Environment to Run the JTATCK Against JTA
1.3 Reference Implementation]
* link:#GJLIB[Configuring Your Environment to Run the JTATCK Against
Your JTA 1.3 Implementation]
* link:#GJLHU[Using the JavaTest Harness Software]
* link:#CEGJIACF[Using the JavaTest Harness Configuration GUI]

[[GBFWN]][[TCPER00012]][[configuring-your-environment-to-run-the-jtatck-against-jta-1.3-reference-implementation]]

4.1 Configuring Your Environment to Run the JTATCK Against JTA 1.3 Reference Implementation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

After configuring your environment as described in this section,
continue with the instructions in link:#GJLHU[Using the JavaTest Harness
Software].


[NOTE]
=======================================================================

* In these instructions, variables in angle brackets need to be expanded
for each platform. For example, `<TS_HOME>` becomes $TS_HOME on
Solaris/Linux and %TS_HOME% on Windows. In addition, the forward
slashes (/) used in all of the examples need to be replaced with
backslashes (\) for Windows. Finally, be sure to use the
appropriate separator for your operating system when specifying multiple
path entries (; on Windows, : on UNIX/Linux).
* On Windows, you must escape any backslashes with an extra backslash in
path separators used in any of the following properties, or use forward
slashes as a path separator instead.

=======================================================================


1.  Set the following environment variables in your shell environment:
1.  `JAVA_HOME` to the directory in which JDK 8.0 is installed.
2.  `TS_HOME` to the directory in which the JTA TCK 1.3 software is
installed.
3.  `ANT_HOME` should not be set in your environment. If it is set,
unset it.
4.  Update your PATH environment variable to include `<JAVA_HOME>/bin`.
2.  Edit your `<TS_HOME>/bin/ts.jte` file and set the following
environment variables:
1.  If you are testing an implementation within a Web container, set the
`webServerHost` property to the name of the host on which your Web
server is running that is configured with JTA 1.3 Reference
Implementation. +
The default setting is `localhost`.
2.  If you are testing an implementation within a Web container, set the
`webServerPort` property to the port number of the host on which the Web
server is running that is configured with JTA 1.3 Reference
Implementation. +
The default setting is `8000`.
3.  Set the webServerHome property to the directory where you installed
JTA 1.3 Reference Implementation.
4.  Set the jta.classes property to point to the classes or JAR file
that contains the JTA classes.
5.  If you are using a deployment handler XML file to deploy the tests
to a Java Servlet or JavaServer Pages container, set the
`web.deployment.handler` property to point to your deployment handler
XML file in the `<TS_HOME>/bin/deploy` directory.Make sure that you
implement the `—deploy` and `—deploy.all` targets in this file.
6.  To copy the `tsharness.jar` and `jtatck.jar` files to the server's
extension directory, change to the `<TS_HOME>/bin` directory and execute
the following command: +
`<TS_HOME>/tools/ant/bin/ant config.vi`
7.  To deploy the JTATCKWAR files, change to the <TS_HOME>/bin directory
and execute the following command: +
`<TS_HOME>/tools/ant/bin/ant deploy.all`

[[GJLIB]][[TCPER00066]][[configuring-your-environment-to-run-the-jtatck-against-your-jta-1.3-implementation]]

4.2 Configuring Your Environment to Run the JTATCK Against Your JTA 1.3 Implementation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

After configuring your environment as described in this section,
continue with the instructions in link:#GJLHU[Using the JavaTest Harness
Software].


[NOTE]
=======================================================================

* In these instructions, variables in angle brackets need to be expanded
for each platform. For example, `<TS_HOME>` becomes `$TS_HOME` on
Solaris/Linux Java EE 8 and `%TS_HOME%` on Windows. In addition,
the forward slashes (/) used in all of the examples need to be replaced
with backslashes (\) for Windows. Finally, be sure to use the
appropriate separator for your operating system when specifying multiple
path entries (; on Windows, : on UNIX/Linux).
* On Windows, you must escape any backslashes with an extra backslash in
path separators used in any of the following properties, or use forward
slashes as a path separator instead.

=======================================================================


1.  Set the following environment variables in your shell environment:
1.  `JAVA_HOME` to the directory in which JDK 8.0 is installed
2.  `TS_HOME` to the directory in which the JTATCK 1.3 software is
installed
3.  `ANT_HOME` should not be set in your environment. If it is set,
unset it.
2.  Edit your <TS_HOME>/bin/ts.jte file and set the following
environment variables:
1.  If you are testing an implementation within a Web container, set the
`webServerHost` property to the name of the host on which your Web
server is running that is configured with your JTA 1.3 Vendor
Implementation. +
The default setting is `localhost`.
2.  If you are testing an implementation within a Web container, set the
`webServerPort` property to the port number of the host on which the Web
server is running that is configured with your JTA 1.3 Vendor
Implementation. +
The default setting is `8000`.
3.  Set the `webServerHome` property to the directory where you
installed your JTA 1.3 Vendor Implementation.
4.  Set the `jta.classes` property to point to the classes or JAR file
that contains the JTA classes.
5. Add Set `jta.JarClasspath` property to point to the path of the JTA API jar
file under test.
6.  If you are using a deployment handler XML file to deploy the tests
to a Java Servlet or JavaServer Pages container, set the
`web.deployment.handler` property to point to your deployment handler
XML file in the `<TS_HOME>/bin/deploy` directory.Make sure that you
implement the —deploy and —deploy.all targets in this file.
7.  To copy the tsharness.jar and jtatck.jar files to the server's
extension directory, change to the `<TS_HOME>/bin` directory and execute
the following command: +
`<TS_HOME>/tools/ant/bin/ant config.vi`
8.  To deploy the JTATCKWAR files, change to the `<TS_HOME>/bin`
directory and execute the following command: +
`<TS_HOME>/tools/ant/bin/ant deploy.all`

[[GJLHU]][[TCPER00067]][[using-the-javatest-harness-software]]

4.3 Using the JavaTest Harness Software
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

There are two general ways to run the JTA TCK test suite using the
JavaTest harness software:

* Through the JavaTest GUI; if using this method, please continue on to
link:#CEGJIACF[Using the JavaTest Harness Configuration GUI].
* In JavaTest batch mode, from the command line in your shell
environment; if using this method, please proceed directly to
link:using.html#GBFWO[Chapter 5, "Executing Tests,"].

[[CEGJIACF]][[using-the-javatest-harness-configuration-gui]]

4.4 Using the JavaTest Harness Configuration GUI
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

You can use the JavaTest harness GUI to modify general test settings and
to quickly get started with the default JTA TCK test environment. This
section covers the following topics:

* link:#CEGDBCHG[Configuration GUI Overview]
* link:#CEGHIAFH[Starting the Configuration GUI]
* link:#CEGFEECF[The Configuration Interview]
* link:#CEGGCHAG[Modifying the DefaultTest Configuration]


[NOTE]
=======================================================================

It is only necessary to proceed with this section if you want to run the
JavaTest harness in GUI mode. If you plan to run the JavaTest harness in
command-line mode, skip the remainder of this chapter, and continue with
link:using.html#GBFWO[Chapter 5, "Executing Tests,"].

=======================================================================


[[CEGDBCHG]][[configuration-gui-overview]]

4.4.1 Configuration GUI Overview
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In order for the JavaTest harness to execute the test suite, it requires
information about how your computing environment is configured. The
JavaTest harness requires two types of configuration information:

* Test environment - This is data used by the tests. For example, the
path to the Java runtime, how to start the product being tested, network
resources, and other information required by the tests in order to run.
This information does not change frequently and usually stays constant
from test run to test run.
* Test parameters - This is information used by the JavaTest harness to
run the tests. Test parameters are values used by the JavaTest harness
that determine which tests in the test suite are run, how the tests
should be run, and where the test reports are stored. This information
often changes from test run to test run.

The first time you run the JavaTest harness software, you are asked to
specify the test suite and work directory that you want to use. (These
parameters can be changed later from within the JavaTest harness GUI.)

Once the JavaTest harness GUI is displayed, whenever you choose Run
Tests->Start to begin a test run, the JavaTest harness determines
whether all of the required configuration information has been supplied:

* If the test environment and parameters have been completely
configured, the test run starts immediately.
* If any required configuration information is missing, the
configuration editor displays a series of questions asking you the
necessary information. This is called the configuration interview. When
you have entered the configuration data, you are asked if you wish to
proceed with running the test.

[[CEGHIAFH]][[starting-the-configuration-gui]]

4.4.2 Starting the Configuration GUI
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Before you start the JavaTest harness software, you must have a valid
test suite and JDK 8.0 installed on your system.

The JTA TCK includes an Ant script that is used to execute the JavaTest
harness from the `<TS_HOME>` directory. Using this Ant script to start
the JavaTest harness is part of the procedure described in
link:#CEGFEECF[The Configuration Interview].

When you execute the JavaTest harness software for the first time, the
JavaTest harness displays a Welcome dialog box that guides you through
the initial startup configuration.

* If it is able to open a test suite, the JavaTest harness displays a
Welcome to JavaTest dialog box that guides you through the process of
either opening an existing work directory or creating a new work
directory as described in the JavaTest online help.
* If the JavaTest harness is unable to open a test suite, it displays a
Welcome to JavaTest dialog box that guides you through the process of
opening both a test suite and a work directory as described in the
JavaTest documentation.

After you specify a work directory, you can use the TestManager to
configure and run tests as described in link:#CEGFEECF[The Configuration
Interview].

[[CEGFEECF]][[the-configuration-interview]]

4.4.3 The Configuration Interview
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The answers you give to some of the configuration interview questions
are specific to your site. For example, the name of the host on which
the JavaTest harness is running. Other configuration parameters can be
set however you wish. For example, where you want test report files to
be stored.

To Configure the JavaTest Harness to Run the JTATCKTests

Note that you only need to complete all these steps the first time you
start the JavaTest test harness. After you complete these steps, you can
either run all of the tests by completing the steps in
link:using.html#GBFUZ[Chapter 5, "Starting JavaTest"]or run a subset of
the tests by completing the steps in link:using.html#CHDDIDGE[Chapter 5,
"Running a Subset of the Tests"].

1.  Change to the `<TS_HOME>/bin` directory and start the JavaTest test
harness:cd +
`<TS_HOME>/bin` +
`<TS_HOME>/tools/ant/bin/ant gui` +
If the Welcome Screen does not appear do the following, otherwise skip
to next step.
2.  Click File, and then click OpenQuick StartWizard. +
The Welcome screen displays.
3.  Click Start a new test run, and then click Next. +
You are prompted to Create a new configuration or use a configuration
template.
4.  Select Create a new configuration, and then click Next. +
You are prompted to select a test suite.
5.  Accept the default suite `(<TS_HOME>/src)`, and then click Next. +
You are prompted to specify a work directory to use to store your test
results.
6.  Type a work directory name or use the Browse button to select a work
directory, and then click Next. +
You are prompted to start the configuration editor or start a test run.
At this point, the JTA TCK is configured to run the default test suite.
7.  Uncheck the Start the configuration editor option, and then click
Finish.
8.  Click Run Tests, and then click Start. +
The JavaTest harness starts running the tests.
9.  To Reconfigure the JavaTest test harness, click Configuration, New
Configuration or Configuration, and then click Change Configuration.
10. Click Report and then click Create Report.
11. Specify the directory in which the JavaTest test harness will write
the report, and then click OK. +
A report is created, and you are asked whether you want to view it.
12. Click Yes to view the report.

[[CEGGCHAG]][[modifying-the-defaulttest-configuration]]

4.4.4 Modifying the DefaultTest Configuration
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The JavaTest GUI enables you to configure numerous test options. These
options are divided into two general dialog box groups:

* Group 1 - Available from the JavaTest Configure -> Change
Configuration submenus, the following options are displayed in a tabbed
dialog box:

** Tests to Run

** Exclude List

** Keywords

** Prior Status

** Test Environment

** Concurrency

** Timeout Factor
* Group 2 - Available from the JavaTest Configure -> Change
Configuration -> Other Values submenu, or by pressing Ctrl+E, the
following options are displayed in a paged dialog box:

** Environment Files

** Test Environment

** Specify Tests to Run

** Specify an Exclude List +
Note that there is some overlap between the functions in these two
dialog boxes; for those functions use the dialog that is most convenient
for you. Please refer to the JavaTest Harness documentation or the
online help for complete information about these various options.
