type=page
status=published
title=Debugging Test Problems
next=faq.html
prev=using.html
~~~~~~
Debugging Test Problems
=======================

[[TCPER00007]][[GBFUV]]


[[debugging-test-problems]]
6 Debugging Test Problems
-------------------------

There are a number of reasons that tests can fail to execute properly.
This chapter provides some approaches for dealing with these failures.
Please note that most of these suggestions are only relevant when
running the test harness in GUI mode.

[[GBFYP]][[TCPER00046]][[overview]]

6.1 Overview
~~~~~~~~~~~~

The goal of a test run is for all tests in the test suite that are not
filtered out to have passing results. If a test run includes tests with
errors or failing results, you must troubleshoot and correct the cause
to satisfactorily complete the test run.

* Errors: Tests with errors could not be executed. These errors usually
occur because the test environment is not properly configured.
* Failures: Tests that fail were executed but had failing results.

The Test Manager GUI provides you with a number of tools for effectively
troubleshooting a test run. See the JavaTest User's Guide and JavaTest
online help for detailed descriptions of the GUI tools described in this
chapter.

[[GJCYT]][[TCPER00047]][[test-tree]]

6.2 Test Tree
~~~~~~~~~~~~~

Use the test tree in the JavaTest GUI to identify specific folders and
tests that had errors or failing results. Color codes are used to
indicate status as follows:

* Green: Passed
* Blue: Test Error
* Red: Failed to pass test
* White: Test not run
* Gray: Test filtered out (not run)

[[sthref11]][[folder-information]]

6.3 Folder Information
~~~~~~~~~~~~~~~~~~~~~~

Click a folder in the test tree in the JavaTest GUI to display its
tabbed pane.

Choose the Error and the Failed panes to view the lists of all tests in
and under a folder that were not successfully run. You can double-click
a test in the lists to view its test information.

[[GJCYI]][[TCPER00048]][[test-information]]

6.4 Test Information
~~~~~~~~~~~~~~~~~~~~

To display information about a test in the JavaTest GUI, click its icon
in the test tree or double-click its name in a folder status pane. The
tabbed pane contains detailed information about the test run and, at the
bottom of the pane, a brief status message identifying the type of
failure or error. This message may be sufficient for you to identify the
cause of the error or failure.If you need more information to identify
the cause of the error or failure, use the following panes listed in
order of importance:

* Test Run Messages contains a Message list and a Message pane that
display the messages produced during the test run.
* Test Run Details contains a two column table of name/value pairs
recorded when the test was run.
* Configuration contains a two column table of the test environment
name/value pairs derived from the configuration data actually used to
run the test.


[NOTE]
=======================================================================

You can set `harness.log.traceflag=true in <TS_HOME>/bin/ts.jte` to get
more debugging information.

=======================================================================


[[GJDFX]][[TCPER00049]][[report-files]]

6.5 Report Files
~~~~~~~~~~~~~~~~

Report files are another good source of troubleshooting information. You
may view the individual test results of a batch run in the JavaTest
Summary window, but there are also a wide range of HTML report files
that you can view in the JavaTest ReportBrowser or in the external
browser or your choice following a test run. See
link:using.html#GJCIW[Running the JTA TCK against Oracle's JTA 1.3
Reference Implementation] for more information.

[[GBFYF]][[TCPER00050]][[configuration-failures]]

6.6 Configuration Failures
~~~~~~~~~~~~~~~~~~~~~~~~~~

Configuration failures are easily recognized because many tests fail the
same way. When all your tests begin to fail, you may want to stop the
run immediately and start viewing individual test output. However, in
the case of full-scale launching problems where no tests are actually
processed, report files are usually not created (though sometimes a
small `harness.trace` file in the report directory is written).
