type=page
status=published
title=Preface
next=intro.html
prev=title.html
~~~~~~
Preface
=======

[[TCPER00001]][[GBFTI]]


[[preface]]
Preface
-------

[NOTE]
========================================================================

The Technology Compatability Kit (TCK) documentation is part of the Java Enterprise 
Edition contribution to the Eclipse Foundation and is not intended for 
use in relation to Java Enterprise Edition or Java Licensee 
requirements. The documentation is in the process of being revised to 
reflect the new Jakarta EE branding. 
Additional changes will be made as requirements and procedures evolve 
for Jakarta EE. Where applicable, references to Java EE or Java 
Enterprise Edition should be considered references to Jakarta EE. 

Please see the Title page for additional license information.
========================================================================

This guide describes how to install, configure, and run the Technology
Compatibility Kit (TCK) that is used to test the Java Transaction API
1.3 (JTA 1.3) (JSR 907) technology.

The JTA TCK is designed as a portable, configurable automated test suite
for verifying the compatibility of a licensee's implementation of the
JTA 1.3 Specification (hereafter referred to as the licensee
implementation). The JTA TCK uses the JavaTest harness version 4.4.1 to
run the test suite.


[NOTE]
=======================================================================

All references to specific Web URLs are given for the sake of your
convenience in locating the resources quickly. These references are
always subject to changes that are in many cases beyond the control of
the authors of this guide.

=======================================================================


[[TCPER00028]][[GBFUS]]


[[who-should-use-this-book]]
Who Should Use This Book
~~~~~~~~~~~~~~~~~~~~~~~~

This guide is for developers of JTA 1.3 technology to assist them in
running the test suite that verifies compatibility of their
implementation of the JTA 1.3 Specification.

[[TCPER00029]][[GBFPO]]


[[before-you-read-this-book]]
Before You Read This Book
~~~~~~~~~~~~~~~~~~~~~~~~~

Before reading this guide, you should familiarize yourself with the Java
programming language and the JTA 1.3 Specification. A good resource for
the Java Programming language is the
(`http://www.oracle.com/technetwork/java/index.html`) Website.

Oracle recommends that before you run the tests in the JTA TCK you have
read and are familiar with the JTA 1.3 Specification and the JavaTest
User's Guide, which describes the main JavaTest harness. The JavaTest
User's Guide is located at `<install_dir>/docs/javatest/javatest.pdf` in
the JTA TCK documentation bundle.

[[sthref2]][[how-this-book-is-organized]]

How This Book is Organized
~~~~~~~~~~~~~~~~~~~~~~~~~~

Before reading this guide, you should familiarize yourself with the Java
programming language at
`http://www.oracle.com/technetwork/java/index.html`. Before you run the
tests in the JTA TCK familiarize yourself with the JTA 1.3 Specification
and the JavaTest User's Guide, which describes the main JavaTest
harness. The JavaTest User's Guide is located at
`<install_dir>/docs/javatest/javatest.pdf` in the JTA TCK documentation
bundle.

[[TCPER00030]][[GBFWF]]


[[typographic-conventions]]
Typographic Conventions
~~~~~~~~~~~~~~~~~~~~~~~

The following table describes the typographic conventions that are used
in this book.

[width="100%",cols="15%,40%,45%",options="header",]
|=======================================================================
|Convention |Meaning |Example
|Boldface |Boldface type indicates graphical user interface elements
associated with an action, terms defined in text, or what you type,
contrasted with onscreen computer output. a|
From the File menu, select Open Project.

A cache is a copy that is stored locally.

[source,oac_no_warn]
----
machine_name% su
Password:
----

|`Monospace` |Monospace type indicates the names of files and
directories, commands within a paragraph, URLs, code in examples, text
that appears on the screen, or text that you enter. a|
Edit your `.login` file.

Use `ls` `-a` to list all files.

`machine_name% you have mail.`

|Italic |Italic type indicates book titles, emphasis, or placeholder
variables for which you supply particular values. a|
Read Chapter 6 in the User's Guide.

Do not save the file.

The command to remove a file is `rm` filename.

|=======================================================================


[[TCPER00031]][[FWBSD]]


[[shell-prompts-in-command-examples]]
Shell Prompts in Command Examples
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The following table shows the default UNIX system prompt and superuser
prompt for the C shell, Bourne shell, Korn shell, and Bash shell.

[width="100%",cols="50%,50%",options="header",]
|=====================================================
|Shell |Prompt
|C shell |`machine_name%`
|C shell for superuser |`machine_name#`
|Bourne shell and Korn shell |`$` +
|Bourne shell and Korn shell for superuser |`#` +
|Bash shell |`shell_name-shell_version$`
|Bash shell for superuser |`shell_name-shell_version#`
|=====================================================
