type=page
status=published
title=Installation
next=config.html
prev=rules.html
~~~~~~
Installation
============

[[TCCOA00004]][[GBFTP]]


[[installation]]
3 Installation
--------------

This chapter explains how to install the Java API for JSON Binding TCK
1.0 (JSON-B TCK) software. After installing the software according to
the instructions in this chapter, proceed to
link:config.html#GBFVV[Chapter 4, "JSON-B TCK Setup and Configuration,"]
for instructions on configuring your test environment.

This chapter contains the following sections:

* link:#GBFUD[Section 3.1, "Obtaining the JSON-B 1.0 Reference
Implementation"]
* link:#GBFTS[Section 3.2, "Installing the JSON-B Software"]

[[GBFUD]][[TCCOA00035]][[obtaining-the-json-b-1.0-reference-implementation]]

3.1 Obtaining the JSON-B 1.0 Reference Implementation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

You can obtain the JSON-B Reference Implementation (RI), Version 1.0
software from the Java Community Process
(`http://jcp.org/en/home/index`) web site. The JSON-B RI software is not
necessary for running the JSON-B TCK, but it can be useful as a test
base for familiarizing yourself with the TCK before testing your own
JSON-B implementation.

[[GBFTS]][[TCCOA00036]][[installing-the-json-b-software]]

3.2 Installing the JSON-B Software
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Before you can run the JSON-B TCK tests, you must install and set up the
following software components:

* Java Standard Edition (Java SE), Version 1.8.0 software
* JSON-B TCK, Version 1.0 software
* An implementation of the JSON-B 1.0 Specification

1.  Install the Java SE 8 software, if it is not already installed. +
Download and install the Java SE 8 software from the
`http://www.oracle.com/technetwork/java/javase/downloads/index.html` Web
site. Refer to the installation instructions that accompany the software
for additional information.
2.  Install the JSON-B TCK 1.0 software.
1.  Copy or download the JSON-B TCK software to your local system.
2.  Change to the directory in which you want to install the JSON-B TCK
software: +
[source,oac_no_warn]
----
cd install_directory
----
3.  Use the `unzip` command to extract the bundle: +
[source,oac_no_warn]
----
unzip jsonbtck-1.0_dd-Mmm-YYYY.zip
----
where dd indicates the day, Mmm indicates the month, and YYYY indicates
the year in which the TCK bundle was created. For example, the JSON-B
TCK bundle name could be `jsonbtck-1.0_15-May-2017.zip`. +
When the bundle is unzipped, the `jsonbtck` directory is created. The
install_directory`/``jsonbtck` directory is the test suite home,
`<TS_HOME>`.
3.  Install the JSON-B implementation to be tested. +
Before testing your own JSON-B implementation, it is recommended that
you run the JSON-B TCK against the JSON-B RI to familiarize yourself
with the JSON-B TCK suite and JavaTest software. See link:#GBFUD[Section
3.1, "Obtaining the JSON-B 1.0 Reference Implementation,"] for more
information.


