.  Install the Jakarta EE {JakartaEEVersion} CI software (the servlet Web container used
for running the {TechnologyShortName} TCK with the
{TechnologyShortName} {TechnologyVersion} CI), if it is not already
installed. +
Download and install the Servlet Web container with the
{TechnologyShortName} {TechnologyVersion} CI used for running the
{TechnologyShortName} TCK {TechnologyVersion}, represented by the Jakarta
EE 8 CI.
If you intend to use {TechnologyRI}, you may obtain this software via the
downloads tab from the project website: {TechnologyRIURL}.
You may also use Eclipse GlassFish 5.1 as your CI. You can obtain that from 
https://projects.eclipse.org/projects/ee4j.glassfish