.  Install the Java EE 8 RI software (the servlet Web container used
for running the {TechnologyShortName} TCK with the
{TechnologyShortName} {TechnologyVersion} RI), if it is not already
installed. +
Download and install the Servlet Web container with the
{TechnologyShortName} {TechnologyVersion} RI used for running the
{TechnologyShortName} TCK {TechnologyVersion}, represented by the Java
EE 8 RI.
This software can be obtained from the Java Licensee Engineering Web
site. Refer to any installation instructions that accompany the software
for additional information.
