type=page
status=published
title=Introduction
next=rules.html
prev=TCKpreface.html
~~~~~~
Introduction
============

[[TCPER00002]][[GBFOW]]


[[introduction]]
1 Introduction
--------------

This chapter provides an overview of the principles that apply generally
to all Technology Compatibility Kits (TCKs) and describes the Java EE
Security API TCK (Java EE Security 1.0) (JSR 338).

The chapter also includes a high level listing of what is needed to get
up and running with the Java EE Security API.

[[GBFTK]][[TCPER00032]][[compatibility-testing]]

1.1 Compatibility Testing
~~~~~~~~~~~~~~~~~~~~~~~~~

Compatibility testing differs from traditional product testing in a
number of ways. The focus of compatibility testing is to test those
features and areas of an implementation that are likely to differ across
other implementations, such as those features that:

* Rely on hardware or operating system-specific behavior
* Are difficult to port
* Mask or abstract hardware or operating system behavior

Compatibility test development for a given feature relies on a complete
specification and reference implementation for that feature.
Compatibility testing is not primarily concerned with robustness,
performance, or ease of use.

[[GBFQN]][[TCPER00054]][[why-compatibility-testing-is-important]]

1.1.1 Why Compatibility Testing is Important
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Java platform compatibility is important to different groups involved
with Java technologies for different reasons:

* Compatibility testing ensures that the Java platform does not become
fragmented as it is ported to different operating systems and hardware
environments.
* Compatibility testing benefits developers working in the Java
programming language, allowing them to write applications once and then
to deploy them across heterogeneous computing environments without
porting.
* Compatibility testing allows application users to obtain applications
from disparate sources and deploy them with confidence.
* Conformance testing benefits Java platform implementers by ensuring a
level playing field for all Java platform ports.

[[GBFPR]][[TCPER00055]][[tck-compatibility-rules]]

1.1.2 TCK Compatibility Rules
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compatibility criteria for all technology implementations are embodied
in the TCK Compatibility Rules that apply to a specified technology.

[[GBFPW]][[TCPER00056]][[tck-overview]]

1.1.3 TCK Overview
^^^^^^^^^^^^^^^^^^

A TCK is a set of tools and tests used to verify that a licensee's
implementation of a technology conforms to the applicable specification.
All tests in the TCK are based on the written specifications for the
Java platform. A TCK tests compatibility of a licensee's implementation
of a technology to the applicable specification of the technology.
Compatibility testing is a means of ensuring correctness, completeness,
and consistency across all implementations developed by licensees of a
technology.

The set of tests included with each TCK is called the test suite. Most
tests in a TCK's test suite are self-checking, but some tests may
require tester interaction. Most tests return either a Pass or Fail
status. For a given platform to be certified, all of the required tests
must pass. The definition of required tests may change from platform to
platform.

The definition of required tests will change over time. Before your
final certification test pass, be sure to download the latest Exclude
List for the TCK you are using.

[[GBFPB]][[TCPER00057]][[java-community-process-jcp-program-and-compatibility-testing]]

1.1.4 Java Community Process (JCP) Program and Compatibility Testing
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The Java Community Process (JCP) program is the formalization of the
open process that has been used since 1995 to develop and revise Java
technology specifications in cooperation with the international Java
community. The JCP program specifies that the following three major
components must be included as deliverables in a final Java technology
release under the direction of the responsible Expert Group:

* Technology Specification
* Reference Implementation
* Technology Compatibility Kit (TCK)

For further information about the JCP program, go to Java Community
Process (`http://jcp.org/en/home/index`).

[[GBFQR]][[TCPER00033]][[about-the-java-ee-security-api-tck-1.0]]

1.2 About the Java EE Security API TCK 1.0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The Java EE Security 1.0 is designed as a portable, configurable,
automated test suite for verifying the compatibility of a licensee's
implementation of the Java EE Security 1.0 Specification.

[[GBFQV]][[TCPER00058]][[java-ee-security-api-tck-specifications-and-requirements]]

1.2.1 Java EE Security API TCK Specifications and Requirements
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This section lists the applicable requirements and specifications.

* Specification Requirements: Software requirements for a Java EE
Security implementation are described in detail in the Java EE Security
API 1.0 Specification. Links to the Java EE Security specification and
other product information can be found at
`http://jcp.org/en/jsr/detail?id=375`.
* Java EE Security Version: The Java EE Security 1.0 is based on the
Java EE Security Specification, Version 1.0.
* Reference Implementation: 

[[GBFSQ]][[TCPER00059]][[java-ee-security-api-tck-components]]

1.2.2 Java EE Security API TCK Components
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The Java EE Security 1.0 includes the following components:

* JavaTest harness version 4.4.1 of the JavaTest harness
* Java EE Security signature tests check that all public APIs are
supported and/or defined as specified in the Java EE Security Version
1.0 implementation under test.
* API tests for all of the packages comprising the required class
libraries for Java EE Security API 1.0.
* End-to-end tests that demonstrate compliance with the Java EE Security
API 1.0 specification.

The Java EE Security tests have been tested with the following:

* Java EE Security 1.0 Reference Implementation
* Java SE 8

The Java EE Security tests run on the following platforms:

* Windows 10
* Mac OS X 10.10.5 and Mac OS X 10.11.6
* Oracle Linux 7.1

[[GBFSA]][[TCPER00060]][[javatest-harness]]

1.2.3 JavaTest Harness
^^^^^^^^^^^^^^^^^^^^^^

The JavaTest harness is a tool bundled with the TCK that runs and
manages test suites on different Java platforms. The JavaTest harness
can be described as both a Java application and a set of compatibility
testing tools. It can run tests on different kinds of Java platforms and
it allows the results to be browsed online within the JavaTest GUI, or
offline in the HTML reports that the JavaTest harness generates.

The JavaTest harness includes the applications and tools that are used
for test execution and test suite management. It supports the following
features:

* Sequencing of tests, allowing them to be loaded and executed
automatically
* Graphic user interface (GUI) for ease of use
* Automated reporting capability to minimize manual errors
* Failure analysis
* Test result auditing and auditable test specification framework
* Distributed testing environment support

To run tests using the JavaTest harness, you specify which tests in the
test suite to run, how to run them, and where to put the results as
described in link:config.html#GBFVV[Chapter 4, "Setup and
Configuration."]

[[GBFRA]][[TCPER00061]][[tck-compatibility-test-suite]]

1.2.4 TCK Compatibility Test Suite
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The test suite is the collection of tests used by the JavaTest harness
to test a particular technology implementation. In this case, it is the
collection of tests used by the Java EE Security 1.0 to test a Java EE
Security 1.0 implementation. The tests are designed to verify that a
licensee's runtime implementation of the technology complies with the
appropriate specification. The individual tests correspond to assertions
of the specification.

The tests that make up the TCK compatibility test suite are precompiled
and indexed within the TCK test directory structure. When a test run is
started, the JavaTest harness scans through the set of tests that are
located under the directories that have been selected. While scanning,
the JavaTest harness selects the appropriate tests according to any
matches with the filters you are using and queues them up for execution.

[[GBFSH]][[TCPER00062]][[exclude-lists]]

1.2.5 Exclude Lists
^^^^^^^^^^^^^^^^^^^

Each version of a TCK includes an Exclude List contained in a `.jtx`
file. This is a list of test file URLs that identify tests which do not
have to be run for the specific version of the TCK being used. Whenever
tests are run, the JavaTest harness automatically excludes any test on
the Exclude List from being executed.

A licensee is not required to pass or run any test on the Exclude List.
The Exclude List file, `<TS_HOME>/bin/ts.jtx`, is included in the Java
EE Security.


[NOTE]
=======================================================================

You should always make sure you are using an up-to-date copy of the
Exclude List before running the Java EE Security to verify your
implementation.

=======================================================================


A test might be in the Exclude List for reasons such as:

* An error in an underlying implementation API has been discovered which
does not allow the test to execute properly.
* An error in the specification that was used as the basis of the test
has been discovered.
* An error in the test itself has been discovered.
* The test fails due to a bug in the tools (such as the JavaTest
harness, for example).

In addition, all tests are run against the technology's reference
implementation. Any tests that fail when run on a reference Java
platform are put on the Exclude List. Any test that is not
specification-based, or for which the specification is vague, may be
excluded. Any test that is found to be implementation dependent (based
on a particular thread scheduling model, based on a particular file
system behavior, and so on) may be excluded.


[NOTE]
=======================================================================

Licensees are not permitted to alter or modify Exclude Lists. Changes to
an Exclude List can only be made by using the procedure described in
link:rules.html#BABHAFDG[Section 2.3, "Java EE Security API Version 1.0
Test Appeals Process."]

=======================================================================


[[GBFRR]][[TCPER00063]][[java-ee-security-api-configuration]]

1.2.6 Java EE Security API Configuration
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You need to set several variables in your test environment, modify
properties in the `<TS_HOME>/bin/ts.jte` file, and then use the JavaTest
harness to configure and run the Java EE Security API tests, as
described in link:config.html#GBFVV[Chapter 4, "Setup and
Configuration."]

[[GBFQW]][[TCPER00034]][[getting-started-with-the-java-ee-security-api]]

1.3 Getting Started With the Java EE Security API
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This section provides a general overview of what needs to be done to
install, set up, test, and use the Java EE Security API. These steps are
explained in more detail in subsequent chapters of this guide.

1.  Make sure that the following software has been correctly installed
on the system hosting the Java EE Security API:
* Java SE 8
* An implementation of the Java EE Security API 1.0 specification
* Java EE Security API TCK Version 1.0 +
See the documentation for each of these software applications for
installation instructions. See link:install.html#GBFTP[Chapter 3,
"Installation,"] for instructions on installing the Java EE Security.
2.  Set up the Java EE Security software. +
See link:config.html#GBFVV[Chapter 4, "Setup and Configuration,"] for
details about the following steps.
1.  Set up your shell environment.
2.  Modify the required properties in the `<TS_HOME>/bin/ts.jte` file.
3.  Configure the JavaTest harness, if you are planning to run the TCK
tests through the JavaTest GUI.
3.  Test the Java EE SecurityAPI 1.0 implementation. +
Test the Java EE Security API implementation installation by running the
test suite. See link:using.html#GBFWO[Chapter 5, "Executing Tests."]


