drop table INTEROP_COSNAMINGNOSSL_TABLE CASCADE  ;

create table INTEROP_COSNAMINGNOSSL_TABLE ( ID  INTEGER, NAME  varchar(25), PRICE float, constraint INTEROP_COSNAMINGNOSSL_TABLE_PK primary key(ID)) ;  

