type=page
status=published
title=Preface
next=intro.html
prev=title.html
~~~~~~
Preface
=======

[[GBFTI]][[preface]]

Preface
-------

[NOTE]
========================================================================

The Java Enterprise Edition documentation is part of the Java Enterprise 
Edition contribution to the Eclipse Foundation and is not intended for 
use in relation to Java Enterprise Edition or Java Licensee 
requirements. The documentation is in the process of being revised to 
reflect the new Jakarta EE branding. 
Additional changes will be made as requirements and procedures evolve 
for Jakarta EE. Where applicable, references to Java EE or Java 
Enterprise Edition should be considered references to Jakarta EE. 

Please see the Title page for additional license information.
========================================================================

This book introduces the Compatibility Test Suite (CTS) for the Jakarta
Platform, Enterprise Edition 8 (Jakarta EE 8) and Jakarta Platform, Enterprise
Edition 8 Web Profile (Jakarta EE 8 Web Profile), and explains how to
configure and run the test suite. It also provides information for
troubleshooting problems you may encounter as you run the test suite.

The Jakarta Platform, Enterprise Edition 8 Compatibility Test Suite (Jakarta
EE 8 CTS) is a portable, configurable automated test suite for verifying
the compatibility of a licensee's implementation of the Jakarta EE 8
Specification (hereafter referred to as the licensee implementation).
The Jakarta EE 8 CTS uses the JavaTest harness version 4.4.1 to run the
test suite.


[NOTE]
=======================================================================

URLs are provided so you can locate resources quickly. However, these
URLs are subject to changes that are beyond the control of the authors
of this guide.

=======================================================================


[[GBFUS]][[who-should-use-this-book]]

Who Should Use This Book
~~~~~~~~~~~~~~~~~~~~~~~~

This guide is for developers of the Java EE 8 technology to assist them
in running the test suite that verifies compatibility of their
implementation of the Java EE 8 Specification.


[[GJFXS]][[before-you-read-this-book]]

Before You Read This Book
~~~~~~~~~~~~~~~~~~~~~~~~~

Before reading this guide, you should familiarize yourself with the Java
programming language, the Java Platform, Enterprise Edition 8 (Java EE
8) Specification, and the JavaTest documentation.

The Java Platform, Enterprise Edition 8 (Java EE 8) Specification can be
downloaded from `http://jcp.org/en/jsr/detail?id=366`.

For documentation on the test harness used for running the Java EE 8 CTS
test suite, see
`https://wiki.openjdk.java.net/display/CodeTools/Documentation`. If you
cannot access the documentation from the website, contact Java Partner
Engineering for a pointer to the JavaTest documentation bundle.

[[GBFWF]][[typographic-conventions]]

Typographic Conventions
~~~~~~~~~~~~~~~~~~~~~~~

The following table describes the typographic conventions that are used
in this book.

[width="100%",cols="15%,40%,45%",options="header",]
|=======================================================================
|Convention |Meaning |Example
|Boldface |Boldface type indicates graphical user interface elements
associated with an action, terms defined in text, or what you type,
contrasted with onscreen computer output. a|
From the File menu, select Open Project.

A cache is a copy that is stored locally.

[source,oac_no_warn]
----
machine_name% su
Password:
----

|`Monospace` |Monospace type indicates the names of files and
directories, commands within a paragraph, URLs, code in examples, text
that appears on the screen, or text that you enter. a|
Edit your `.login` file.

Use `ls` `-a` to list all files.

`machine_name% you have mail.`

|Italic |Italic type indicates book titles, emphasis, or placeholder
variables for which you supply particular values. a|
Read Chapter 6 in the User's Guide.

Do not save the file.

The command to remove a file is `rm` filename.

|=======================================================================


[[FWBSD]][[shell-prompts-in-command-examples]]

Shell Prompts in Command Examples
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The following table shows the default UNIX system prompt and superuser
prompt for the C shell, Bourne shell, and Korn shell.

[width="100%",cols="50%,50%",options="header",]
|=====================================================
|Shell |Prompt
|C shell |`machine_name%`
|C shell for superuser |`machine_name#`
|Bourne shell and Korn shell |`$` +
|Bourne shell and Korn shell for superuser |`#` +
|Bash shell |`shell_name-shell_version$`
|Bash shell for superuser |`shell_name-shell_version#`
|=====================================================



