type=page
status=published
title=Troubleshooting
next=building.html
prev=debug.html
~~~~~~
Troubleshooting
===============

[[GFAHF]][[troubleshooting]]

9 Troubleshooting
-----------------

This chapter explains how to debug test failures that you could
encounter as you run the Java Platform, Enterprise Edition Compatibility
Test Suite.

[[GFAUR]][[common-cts-problems-and-resolutions]]

9.1 Common CTS Problems and Resolutions
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This section lists common problems that you may encounter as you run the
Java Platform, Enterprise Edition Compatibility Test Suite software on
the Java Platform, Enterprise Edition RI. It also proposes resolutions
for the problems, where applicable.

* Problem: +
The following exception may occur when a Java EE 8 CTS test tries to
write a very long tracelog: +
[source,oac_no_warn]
----
java.lang.StringIndexOutOfBoundsException: String 
index out of range:
-13493
at java.lang.String.substring(String.java:1525)
at java.lang.String.substring(String.java:1492)
at javasoft.sqe.javatest.TestResult$Section
$WritableOutputBuffer.write(TestResult.java:650)
at java.io.Writer.write(Writer.java:153)
at java.io.PrintWriter.write(PrintWriter.java: 213)
at java.io.PrintWriter.write(PrintWriter.java: 229)
at java.io.PrintWriter.print(PrintWriter.java: 360)
at java.io.PrintWriter.println(PrintWriter.java:497)
at javasoft.sqe.javatest.lib.ProcessCommand
$StreamCopier.run(ProcessCommand.java:331)
----
The execution of the test will either fail or hang. +
Resolution: +
Set the `-Djavatest.maxOutputSize=`nnn system parameter in the
`runclient` and/or `gui` targets in the `<TS_HOME>/bin/build.xml` file
to a value that is higher than the default setting of `100,000` on the
JavaTest VM.
* Problem: +
When you start the Java Platform, Enterprise Edition RI on Windows
XP/2000 by using the `javaee -verbose` command, the system may not find
the specified path and could display one of the following errors: +
[source,oac_no_warn]
----
"Verify that JAVA_HOME is set correctly"
"Verify that JAVAEE_HOME is set correctly"
----
Resolution: +
Set `JAVA_HOME` to the path where the version of Java being used was
installed and set `JAVAEE_HOME` to the location of the Java Platform,
Enterprise Edition installation directory.
* Problem: +
If the `cts.jar` and the `tsharness.jar` files are not loadable by the
extension classloader of your Java Platform, Enterprise Edition server,
the following exception will be displayed in the window where the server
was started when you attempt to run the tests: +
[source,oac_no_warn]
----
java.lang.NoClassDefFoundError: com/sun/cts/util
RemoteLoggingInitException
----
Resolution: +
Ensure that the `cts.jar` and `tsharness.jar` files can be loaded by the
extension class loader of your Java Platform, Enterprise Edition server.

[[GFAGN]][[support]]

9.2 Support
~~~~~~~~~~~

After completing the troubleshooting process explained in this chapter,
if you still cannot resolve your test problems, please contact the Java
Licensee Engineering representative assigned to your account.


