DROP TABLE INTEROP_CSIV2_TABLE1;
DROP TABLE INTEROP_CSIV2_TABLE2;
DROP TABLE INTEROP_CSIV2_TABLE3;
DROP TABLE INTEROP_CSIV2_TABLE4;
DROP TABLE INTEROP_CSIV2_TABLE5;
DROP TABLE INTEROP_CSIV2_TABLE6;
DROP TABLE INTEROP_CSIV2_TABLE7;
DROP TABLE INTEROP_CSIV2_TABLE52;
DROP TABLE INTEROP_CSIV2_TABLE8;
DROP TABLE INTEROP_CSIV2_TABLE53;
DROP TABLE INTEROP_CSIV2_TABLE10;
DROP TABLE INTEROP_CSIV2_TABLE11;
DROP TABLE INTEROP_CSIV2_TABLE12;
DROP TABLE INTEROP_CSIV2_TABLE13;
DROP TABLE INTEROP_CSIV2_TABLE14;
DROP TABLE INTEROP_CSIV2_TABLE15;
DROP TABLE INTEROP_CSIV2_TABLE16;
DROP TABLE INTEROP_CSIV2_TABLE17;
DROP TABLE INTEROP_CSIV2_TABLE18;
DROP TABLE INTEROP_CSIV2_TABLE19;
DROP TABLE INTEROP_CSIV2_TABLE20;
DROP TABLE INTEROP_CSIV2_TABLE21;
DROP TABLE INTEROP_CSIV2_TABLE22;
DROP TABLE INTEROP_CSIV2_TABLE23;
DROP TABLE INTEROP_CSIV2_TABLE24;
DROP TABLE INTEROP_CSIV2_TABLE25;
DROP TABLE INTEROP_CSIV2_TABLE26;
DROP TABLE INTEROP_CSIV2_TABLE27;
DROP TABLE INTEROP_CSIV2_TABLE28;
DROP TABLE INTEROP_CSIV2_TABLE29;
DROP TABLE INTEROP_CSIV2_TABLE30;
DROP TABLE INTEROP_CSIV2_TABLE31;
DROP TABLE INTEROP_CSIV2_TABLE32;
DROP TABLE INTEROP_CSIV2_TABLE33;
DROP TABLE INTEROP_CSIV2_TABLE34;
DROP TABLE INTEROP_CSIV2_TABLE35;
DROP TABLE INTEROP_CSIV2_TABLE36;
DROP TABLE INTEROP_CSIV2_TABLE37;
DROP TABLE INTEROP_CSIV2_TABLE38;
DROP TABLE INTEROP_CSIV2_TABLE39;
DROP TABLE INTEROP_CSIV2_TABLE40;
DROP TABLE INTEROP_CSIV2_TABLE41;
DROP TABLE INTEROP_CSIV2_TABLE42;
DROP TABLE INTEROP_CSIV2_TABLE43;
DROP TABLE INTEROP_CSIV2_TABLE44;
DROP TABLE INTEROP_CSIV2_TABLE45;
DROP TABLE INTEROP_CSIV2_TABLE46;
DROP TABLE INTEROP_CSIV2_TABLE47;
DROP TABLE INTEROP_CSIV2_TABLE48;
DROP TABLE INTEROP_CSIV2_TABLE49;
DROP TABLE INTEROP_CSIV2_TABLE50;
DROP TABLE INTEROP_COSNAMINGNOSSL_TABLE;


CREATE TABLE INTEROP_CSIV2_TABLE1 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TABL  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE2 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TAB1  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE3 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TAB2  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE4 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TAB3  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE5 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TAB4  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE6 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TAB5  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE7 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TAB6  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE52 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TAB7  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE8 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TAB8  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE53 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TAB9  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE10 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA10  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE11 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA11  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE12 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA12  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE13 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA13  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE14 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA14  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE15 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA15  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE16 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA16  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE17 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA17  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE18 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA18  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE19 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA19  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE20 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA20  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE21 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA21  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE22 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA22  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE23 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA23  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE24 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA24  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE25 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA25  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE26 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA26  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE27 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA27  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE28 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA28  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE29 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA29  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE30 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA30  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE31 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA31  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE32 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA32  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE33 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA33  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE34 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA34  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE35 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA35  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE36 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA36  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE37 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA37  PRIMARY KEY (ID));


CREATE TABLE INTEROP_CSIV2_TABLE38 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA38  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE39 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA39  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE40 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA40  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE41 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, CONSTRAINT INTEROP_CSIV2_TA41  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE42 ( KEY_ID INT NOT NULL, BRAND_NAME VARCHAR(25) NOT NULL, PRICE DOUBLE NOT NULL, CONSTRAINT INTEROP_CSIV2_TA42  PRIMARY KEY (KEY_ID));

CREATE TABLE INTEROP_CSIV2_TABLE43 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, PRICE REAL NOT NULL,
  CONSTRAINT INTEROP_CSIV2_TA43  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE44 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, PRICE REAL NOT NULL,
  CONSTRAINT INTEROP_CSIV2_TA44  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE45 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, PRICE REAL NOT NULL,
  CONSTRAINT INTEROP_CSIV2_TA45  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE46 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, PRICE REAL NOT NULL, CONSTRAINT INTEROP_CSIV2_TA46  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE47 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, PRICE REAL NOT NULL, CONSTRAINT INTEROP_CSIV2_TA47  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE48 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, PRICE REAL NOT NULL, CONSTRAINT INTEROP_CSIV2_TA48  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE49 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, PRICE REAL NOT NULL, CONSTRAINT INTEROP_CSIV2_TA49  PRIMARY KEY (ID));

CREATE TABLE INTEROP_CSIV2_TABLE50 ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, PRICE REAL NOT NULL, CONSTRAINT INTEROP_CSIV2_TA50  PRIMARY KEY (ID));


CREATE TABLE INTEROP_COSNAMINGNOSSL_TABLE ( ID INT NOT NULL, NAME VARCHAR(25) NOT NULL, PRICE DOUBLE NOT NULL, CONSTRAINT INTEROP_COSNAMINGN  PRIMARY KEY (ID));
