<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<definitions name="HelloBasicService" targetNamespace="http://HelloBasic.org" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://HelloBasic.org" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
  </types>
  <message name="HelloBasic_sayHelloBasic">
    <part name="String_1" type="xsd:string"/>
  </message>
  <message name="HelloBasic_sayHelloBasicResponse">
    <part name="result" type="xsd:string"/>
  </message>
  <portType name="HelloBasic">
    <operation name="sayHelloBasic" parameterOrder="String_1">
      <input message="tns:HelloBasic_sayHelloBasic"/>
      <output message="tns:HelloBasic_sayHelloBasicResponse"/>
    </operation>
  </portType>
  <binding name="HelloBasicBinding" type="tns:HelloBasic">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="sayHelloBasic">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal" namespace="http://HelloBasic.org"/>
      </input>
      <output>
        <soap:body use="literal" namespace="http://HelloBasic.org"/>
      </output>
    </operation>
  </binding>
  <service name="HelloBasicService">
    <port name="HelloBasicPort" binding="tns:HelloBasicBinding">
      <soap:address location="https://localhost:7000/SecEjbBasicSSL/ws4ee/SecEjbBasicSSL/HelloBasicPC"/>
    </port>
  </service>
</definitions>
