type=page
status=published
title=Setup and Configuration
next=using.html
prev=install.html
~~~~~~
Setup and Configuration
=======================

[[TCJAC00005]][[GBFVV]]


[[setup-and-configuration]]
4 Setup and Configuration
-------------------------

This chapter describes how to set up the JACC TCK and JavaTest harness
software. Before proceeding with the instructions in this chapter, be
sure to install all required software, as described in
link:install.html#GBFTP[Chapter 3, "Installation."]

After completing the instructions in this chapter, proceed to
link:using.html#GBFWO[Chapter 5, "Executing Tests,"] for instructions on
running the JACC TCK.

This chapter includes the following topics:

* link:#GBFVU[Configuring Your Environment to Run the JACC TCK Against
the JACC Reference Implementation]
* link:#GCLHU[Configuring Your Environment to Run the JACC TCK Against
Your JACC 1.5 Vendor Implementation]
* link:#GCRVD[Custom Deployment Handlers]
* link:#GBFUY[Using the JavaTest Harness Software]
* link:#GBFWG[Using the JavaTest Harness Configuration GUI]

[[GBFVU]][[TCJAC00045]][[configuring-your-environment-to-run-the-jacc-tck-against-the-jacc-reference-implementation]]

4.1 Configuring Your Environment to Run the JACC TCK Against the JACC Reference Implementation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

After configuring your environment as described in this section,
continue with the instructions in link:#GBFUY[Section 4.4, "Using the
JavaTest Harness Software."]


[NOTE]
=======================================================================

In these instructions, variables in angle brackets need to be expanded
for each platform. For example, `<TS_HOME>` becomes `$TS_HOME` on
Solaris/Linux and `%TS_HOME%` on Windows. In addition, the forward
slashes (`/`) used in all of the examples need to be replaced with
backslashes (`\`) for Windows. Finally, be sure to use the appropriate
separator for your operating system when specifying multiple path
entries (`;` on Windows, `:` on UNIX/Linux).

On Windows, you must escape any backslashes with an extra backslash in
path separators used in any of the following properties, or use forward
slashes as a path separator instead.

=======================================================================


1.  Set the following environment variables in your shell environment:
1.  `JAVA_HOME` to the directory in which Java SE 7 is installed
2.  `PATH` to include the `<TS_HOME>/bin` and `<TS_HOME>/tools/ant/bin`
directories
3.  `ANT_HOME` should not be set in your environment. If it is set,
unset it.
2.  Edit your `<TS_HOME>/bin/ts.jte` file and set the following
variables:
1.  Set the `jacc.home` property to the location where your JACC runtime
implementation is installed.
2.  Set the `jacc.host` property to the hostname of the system where
your JACC runtime is installed.
3.  Set the `jacc.classes` property to point to the classes or JAR file
that contains the JACC classes.
4.  Set the `sigTestClasspath` property to point to the classes or JAR
file for the runtime implementation of the JSR 115 API and any
additional required signature classes.
3.  Copy the `tsharness.jar` and `jacctck.jar` files to the server's
extension directory, change to the `<TS_HOME>/bin` directory and execute
the following commands: +
[source,oac_no_warn]
----
ant config.vi
ant enable.jacc
----

[[GCLHU]][[TCJAC00046]][[configuring-your-environment-to-run-the-jacc-tck-against-your-jacc-1.5-vendor-implementation]]

4.2 Configuring Your Environment to Run the JACC TCK Against Your JACC 1.5 Vendor Implementation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

After configuring your environment as described in this section,
continue with the instructions in link:#GBFUY[Section 4.4, "Using the
JavaTest Harness Software."]


[NOTE]
=======================================================================

In these instructions, variables in angle brackets need to be expanded
for each platform. For example, `<TS_HOME>` becomes `$TS_HOME` on
Solaris/Linux and `%TS_HOME%` on Windows. In addition, the forward
slashes (`/`) used in all of the examples need to be replaced with
backslashes (`\`) for Windows. Finally, be sure to use the appropriate
separator for your operating system when specifying multiple path
entries (`;` on Windows, `:` on UNIX/Linux).

On Windows, you must escape any backslashes with an extra backslash in
path separators used in any of the following properties, or use forward
slashes as a path separator instead.

=======================================================================


1.  Set the following environment variables in your shell environment:
1.  `JAVA_HOME` to the directory in which Java SE 7 is installed
2.  `PATH` to include the `<TS_HOME>/bin` and `<TS_HOME>/tools/ant/bin`
directories
3.  `ANT_HOME` should not be set in your environment. If it is set,
unset it.
2.  Edit your `<TS_HOME>/bin/ts.jte` file and set the following
variables:
1.  Set the `jacc.home` property to the location where your JACC runtime
implementation is installed.
2.  Set the `jacc.host` property to the hostname of the system where
your JACC runtime is installed.
3.  Set the `jacc.classes` property to point to the classes or JAR file
that contains the JACC classes.
4.  Set the `sigTestClasspath` property to point to the classes or JAR
file for the runtime implementation of the JSR 115 API and any
additional required signature classes.
3.  Copy the `tsharness.jar` and `jacctck.jar` files to your server's
extension directory and deploy.
4.  Change to the `<TS_HOME>/bin` directory and execute the following
command: +
[source,oac_no_warn]
----
ant config.vi
----
The `config.vi` Ant task performs several actions, including:
* Sets the following JACC JVM options: +
[source,oac_no_warn]
----
-Djavax.security.jacc.policy.provider=
        com.sun.ts.tests.jacc.provider.TSPolicy
-Dvendor.javax.security.jacc.policy.provider=
        com.sun.enterprise.security.provider.PolicyWrapper
-Djavax.security.jacc.PolicyConfigurationFactory.provider=
        com.sun.ts.tests.jacc.provider.TSPolicyConfigurationFactoryImpl
-Dvendor.javax.security.jacc.PolicyConfigurationFactory.provider=
        com.sun.enterprise.security.provider.PolicyConfigurationFactoryImpl
-Dlog.file.location=${log.file.location}
----
Note that the `log.file.location` comes from the property of the same
name in the `ts.jte` file.
* Deploys the JACC Provider (from `<TS_HOME>/lib/tsprovider.jar`) to
your server's library directory (for example,
`glassfish4/glassfish/lib`) where it can be picked up and loaded by the
server
* Enables the Security manager with the `-Djava.security.manager` JVM
option
* Creates users required by the TCK tests on the server under test
* Deploys `tsharness.jar` and `jacctck.jar` files to your JACC server's
`/lib` directory
5.  Enable the TCK JACC provider: +
[source,oac_no_warn]
----
ant enable.jacc
----
After running the JACC TCK tests, disable the JACC provider by running
the disable.jacc Ant task: +
[source,oac_no_warn]
----
ant disable.jacc
----
6.  Change to the appropriate JACC TCK test subdirectory
(`<TS_HOME>/src/com/sun/ts/tests/jacc/web` or
<TS_HOME>/src/com/sun/ts/tests/jacc/ejb) for the tests that you plan to
run and execute the `ant deploy` command to deploy the desired tests. +
To deploy the JACC EJB tests: +
[source,oac_no_warn]
----
cd ${TS_HOME}/src/com/sun/ts/tests/jacc/ejb
ant deploy
----
Or, to deploy the JACC Web tests: +
[source,oac_no_warn]
----
cd ${TS_HOME}/src/com/sun/ts/tests/jacc/web
ant deploy
----
Repeat this deployment step for each JACC test directory after you run
the tests in the current directory, as described in
link:using.html#GBFWO[Chapter 5, "Executing Tests."] +
JACC tests translate security configurations into corresponding JACC
permissions. If multiple test directories are deployed simultaneously,
the result can be permissions that are stricter than what is expected,
which can lead to test failures. To avoid this potential problem, deploy
and run individual test directories separately, not simultaneously.

[[GCRVD]][[TCJAC00047]][[custom-deployment-handlers]]

4.3 Custom Deployment Handlers
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Deployment handlers are used to deploy and undeploy the WAR files that
contain the tests to be run during the certification process. A
deployment handler is an Ant build file that contains at least the
required targets listed in link:#GJCBX[Table 4-1].

[[TCJAC115]][[sthref9]][[GJCBX]]


Table 4-1 Required Deployment Handler Targets

[width="100%",cols="25%,75%",options="header",]
|=======================================================================
|Required Ant Task |Description
|`-deploy` |Deploys an archive or any archive from the current working
directory and its children directories.

|`-undeploy` |Undeploys a deployed archive or any deployed archive from
the current working directory and its children directories.

|`-deploy.all` |Deploys all archives. (Do not implement for the JACC
TCK.)

|`undeploy.all` |Undeploys all deployed archives. (Do not implement for
the JACC TCK.)
|=======================================================================


The Java Authorization Contract for Containers TCK provides the
following deployment handlers:

* `<TS_HOME>/bin/xml/impl/none/deploy.xml`
* `<TS_HOME>/bin/xml/impl/glassfish/deploy.xml`

The `deploy.xml` files in each of these directories are used to control
deployment to a specific container (no deployment or deployment to the
GlassFish Web container) denoted by the name of the directory in which
each `deploy.xml` file resides. The primary `build.xml` file in the
`<TS_HOME>/bin` directory has a target to invoke any of the required
targets (`-deploy`, `-undeploy`, `-deploy.all`, `-undeploy.all`).


[NOTE]
=======================================================================

The JACC TCK does not require you to implement the `-deploy.all` or
`-undeploy.all` targets. In fact, it is recommended that you run each
JACC TCK test subdirectory individually, not collectively.

=======================================================================


[[GJCEK]][[TCJAC00077]][[creating-a-custom-deployment-handler]]

4.3.1 Creating a Custom Deployment Handler
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To deploy tests to another JACC 1.5 implementation, you must create a
custom handler.

1.  [[BABEDEIG]] +
Create a new directory in the `<TS_HOME>/bin/impl` directory tree. +
For example, create the `<TS_HOME>/bin/impl/`my_deployment_handler
directory.
2.  Copy the `deploy.xml` file from the `<TS_HOME>/bin/xml/impl/none`
directory to the directory that you created.
3.  Modify the required targets in the `deploy.xml` file. +
This is what the `deploy.xml` file for the "none" deployment handler
looks like. +
[source,oac_no_warn]
----
<project name="No-op Deployment" default="deploy">

  <!-- No-op deployment target -->
  <target name="-deploy">
      <echo message="No deploy target implemented for this deliverable"/>
  </target>

  <target name="-undeploy">
      <echo message="No undeploy target implemented for this deliverable"/>
  </target>

  <target name="-deploy.all">
      <echo message="No deploy target implemented for this deliverable"/>
  </target>

  <target name="-undeploy.all">
      <echo message="No undeploy target implemented for this deliverable"/>
  </target>

</project>
----
Although this example just echoes messages, it does include the four
required Ant targets (`-deploy`,`-undeploy`, `-deploy.all`,
`-undeploy.all`) that your custom `deploy.xml` file must contain. With
this as your starting point, look at the required targets in the
`deploy.xml` files in the `glassfish` directory for guidance as you
create the same targets for the Web container in which you will run your
implementation of JACC.
4.  Set the `impl.vi.deploy.dir` property in the `ts.jte` file to the
name of the directory, my_deployment_handler, that you created in step
link:#BABEDEIG[1]. +
The required Ant targets in your `deploy.xml` file can be called from
anywhere in the `<TS_HOME>/src` directory.

[[GBFUY]][[TCJAC00048]][[using-the-javatest-harness-software]]

4.4 Using the JavaTest Harness Software
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

There are two general ways to run the JACC TCK test suite using the
JavaTest harness software:

* Through the JavaTest GUI; if using this method, please continue on to
link:#GBFWG[Section 4.5, "Using the JavaTest Harness Configuration
GUI."]
* In JavaTest batch mode, from the command line in your shell
environment; if using this method, please proceed directly to
link:using.html#GBFWO[Chapter 5, "Executing Tests."]

[[GBFWG]][[TCJAC00049]][[using-the-javatest-harness-configuration-gui]]

4.5 Using the JavaTest Harness Configuration GUI
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

You can use the JavaTest harness GUI to modify general test settings and
to quickly get started with the default JACC TCK test environment.


[NOTE]
=======================================================================

It is only necessary to proceed with this section if you want to run the
JavaTest harness in GUI mode. If you plan to run the JavaTest harness in
command-line mode, skip the remainder of this chapter, and continue with
link:using.html#GBFWO[Chapter 5, "Executing Tests."]

=======================================================================


[[GBFVA]][[TCJAC00078]][[configuration-gui-overview]]

4.5.1 Configuration GUI Overview
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In order for the JavaTest harness to execute the test suite, it requires
information about how your computing environment is configured. The
JavaTest harness requires two types of configuration information:

* Test environment : This is data used by the tests. For example, the
path to the Java runtime, how to start the product being tested, network
resources, and other information required by the tests in order to run.
This information does not change frequently and usually stays constant
from test run to test run.
* Test parameters: This is information used by the JavaTest harness to
run the tests. Test parameters are values used by the JavaTest harness
that determine which tests in the test suite are run, how the tests
should be run, and where the test reports are stored. This information
often changes from test run to test run.

The first time you run the JavaTest harness software, you are asked to
specify the test suite and work directory that you want to use. (These
parameters can be changed later from within the JavaTest harness GUI.)

Once the JavaTest harness GUI is displayed, whenever you choose Run
Tests, and then Start to begin a test run, the JavaTest harness
determines whether all of the required configuration information has
been supplied:

* If the test environment and parameters have been completely
configured, the test run starts immediately.
* If any required configuration information is missing, the
configuration editor displays a series of questions asking you the
necessary information. This is called the configuration interview . When
you have entered the configuration data, you are asked if you wish to
proceed with running the test.

[[GBFVD]][[TCJAC00079]][[starting-the-configuration-gui]]

4.5.2 Starting the Configuration GUI
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Before you start the JavaTest harness software, you must have a valid
test suite and Java SE 7 installed on your system.

The JACC TCK includes an Ant script that is used to execute the JavaTest
harness from the `<TS_HOME>` directory. Using this Ant script to start
the JavaTest harness is part of the procedure described in
link:#GBFVX[Section 4.5.3, "To Configure the JavaTest Harness to Run the
JACC TCK Tests."]

When you execute the JavaTest harness software for the first time, the
JavaTest harness displays a Welcome dialog box that guides you through
the initial startup configuration.

* If it is able to open a test suite, the JavaTest harness displays a
Welcome to JavaTest dialog box that guides you through the process of
either opening an existing work directory or creating a new work
directory as described in the JavaTest online help.
* If the JavaTest harness is unable to open a test suite, it displays a
Welcome to JavaTest dialog box that guides you through the process of
opening both a test suite and a work directory as described in the
JavaTest documentation.

After you specify a work directory, you can use the Test Manager to
configure and run tests as described in link:#GBFVX[Section 4.5.3, "To
Configure the JavaTest Harness to Run the JACC TCK Tests."]

[[GBFVX]][[TCJAC00080]][[to-configure-the-javatest-harness-to-run-the-jacc-tck-tests]]

4.5.3 To Configure the JavaTest Harness to Run the JACC TCK Tests
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The answers you give to some of the configuration interview questions,
the name of the host on which the JavaTest harness is running, are
specific to your site. Other configuration parameters, such as where you
want test report files to be stored, can be set however you wish.

Note that you only need to complete all these steps the first time you
start the JavaTest test harness. After you complete these steps, you can
run the tests by completing the steps in link:using.html#GBFUZ[Section
5.1, "Starting JavaTest."]

1.  Change to the `<TS_HOME>/bin` directory and start the JavaTest test
harness: +
[source,oac_no_warn]
----
cd <TS_HOME>/bin
ant gui
----
2.  From the File menu, select Open Quick Start Wizard. +
The Welcome screen displays.
3.  Select Start a new test run, and then click Next. +
You are prompted to create a new configuration or use a configuration
template.
4.  Select Create a new configuration, and then click Next. +
You are prompted to select a test suite.
5.  Accept the default suite (`<TS_HOME>/src`), and then click Next. +
You are prompted to specify a work directory to use to store your test
results.
6.  Type a work directory name or use the Browse button to select a work
directory, and then click Next. +
You are prompted to start the configuration editor or start a test run.
At this point, the JACC TCK is configured to run the default test suite.
7.  Deselect the Start the configuration editor option, and then click
Finish.
8.  Click Run Tests, then click Start. +
The JavaTest harness starts running the tests.
9.  To reconfigure the JavaTest test harness, do one of the following:
* Click Configuration, then click New Configuration.
* Click Configuration, then click Change Configuration.
10. Click Report, and then click Create Report.
11. Specify the directory in which the JavaTest test harness will write
the report, and then click OK. +
A report is created, and you are asked whether you want to view it.
12. Click Yes to view the report.

[[GBFUU]][[TCJAC00081]][[modifying-the-default-test-configuration]]

4.5.4 Modifying the Default Test Configuration
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The JavaTest GUI enables you to configure numerous test options. These
options are divided into two general dialog box groups:

* Group 1: Available from the JavaTest Configure/Change Configuration
submenus, the following options are displayed in a tabbed dialog box:

** Tests to Run

** Exclude List

** Keywords

** Prior Status

** Test Environment

** Concurrency

** Timeout Factor
* Group 2: Available from the JavaTest Configure/Change
Configuration/Other Values submenu, or by pressing Ctrl+E, the following
options are displayed in a paged dialog box:

** Environment Files

** Test Environment

** Specify Tests to Run

** Specify an Exclude List

Note that there is some overlap between the functions in these two
dialog boxes; for those functions use the dialog box that is most
convenient for you. Please refer to the JavaTest Harness documentation
or the online help for complete information about these various options.


