/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 2002 International Business Machines Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest;

public interface MarshallTest extends java.rmi.Remote {
  public java.lang.String echoString(java.lang.String inputString)
      throws java.rmi.RemoteException;

  public java.math.BigInteger echoInteger(java.math.BigInteger inputInteger)
      throws java.rmi.RemoteException;

  public int echoInt(int inputInt) throws java.rmi.RemoteException;

  public long echoLong(long inputLong) throws java.rmi.RemoteException;

  public short echoShort(short inputShort) throws java.rmi.RemoteException;

  public java.math.BigDecimal echoDecimal(java.math.BigDecimal inputDecimal)
      throws java.rmi.RemoteException;

  public float echoFloat(float inputFloat) throws java.rmi.RemoteException;

  public double echoDouble(double inputDouble) throws java.rmi.RemoteException;

  public boolean echoBoolean(boolean inputBoolean)
      throws java.rmi.RemoteException;

  public byte echoByte(byte inputByte) throws java.rmi.RemoteException;

  public javax.xml.namespace.QName echoQName(
      javax.xml.namespace.QName inputQName) throws java.rmi.RemoteException;

  public java.util.Calendar echoDateTime(java.util.Calendar inputDateTime)
      throws java.rmi.RemoteException;

  public java.lang.String echoSoapString(java.lang.String inputSoapString)
      throws java.rmi.RemoteException;

  public java.lang.Boolean echoSoapBoolean(java.lang.Boolean inputSoapBoolean)
      throws java.rmi.RemoteException;

  public java.lang.Float echoSoapFloat(java.lang.Float inputSoapFloat)
      throws java.rmi.RemoteException;

  public java.lang.Double echoSoapDouble(java.lang.Double inputSoapDouble)
      throws java.rmi.RemoteException;

  public java.math.BigDecimal echoSoapDecimal(
      java.math.BigDecimal inputSoapDecimal) throws java.rmi.RemoteException;

  public java.lang.Integer echoSoapInt(java.lang.Integer inputSoapInt)
      throws java.rmi.RemoteException;

  public java.lang.Short echoSoapShort(java.lang.Short inputSoapShort)
      throws java.rmi.RemoteException;

  public java.lang.Byte echoSoapByte(java.lang.Byte inputSoapByte)
      throws java.rmi.RemoteException;

  public byte[] echoBase64Binary(byte[] inputBase64Binary)
      throws java.rmi.RemoteException;

  public byte[] echoHexBinary(byte[] inputHexBinary)
      throws java.rmi.RemoteException;

  public byte[] echoSoapBase64(byte[] inputSoapBase64)
      throws java.rmi.RemoteException;

  public java.lang.String[] echoStringArray(java.lang.String[] inputStringArray)
      throws java.rmi.RemoteException;

  public java.math.BigInteger[] echoIntegerArray(
      java.math.BigInteger[] inputIntegerArray) throws java.rmi.RemoteException;

  public int[] echoIntArray(int[] inputIntArray)
      throws java.rmi.RemoteException;

  public long[] echoLongArray(long[] inputLongArray)
      throws java.rmi.RemoteException;

  public short[] echoShortArray(short[] inputShortArray)
      throws java.rmi.RemoteException;

  public java.math.BigDecimal[] echoDecimalArray(
      java.math.BigDecimal[] inputDecimalArray) throws java.rmi.RemoteException;

  public float[] echoFloatArray(float[] inputFloatArray)
      throws java.rmi.RemoteException;

  public double[] echoDoubleArray(double[] inputDoubleArray)
      throws java.rmi.RemoteException;

  public boolean[] echoBooleanArray(boolean[] inputBooleanArray)
      throws java.rmi.RemoteException;

  public byte[] echoByteArray(byte[] inputByteArray)
      throws java.rmi.RemoteException;

  public javax.xml.namespace.QName[] echoQNameArray(
      javax.xml.namespace.QName[] inputQNameArray)
      throws java.rmi.RemoteException;

  public java.util.Calendar[] echoDateTimeArray(
      java.util.Calendar[] inputDateTimeArray) throws java.rmi.RemoteException;

  public java.lang.String[] echoSoapStringArray(
      java.lang.String[] inputSoapStringArray) throws java.rmi.RemoteException;

  public java.lang.Boolean[] echoSoapBooleanArray(
      java.lang.Boolean[] inputSoapBooleanArray)
      throws java.rmi.RemoteException;

  public java.lang.Float[] echoSoapFloatArray(
      java.lang.Float[] inputSoapFloatArray) throws java.rmi.RemoteException;

  public java.lang.Double[] echoSoapDoubleArray(
      java.lang.Double[] inputSoapDoubleArray) throws java.rmi.RemoteException;

  public java.math.BigDecimal[] echoSoapDecimalArray(
      java.math.BigDecimal[] inputSoapDecimalArray)
      throws java.rmi.RemoteException;

  public java.lang.Integer[] echoSoapIntArray(
      java.lang.Integer[] inputSoapIntArray) throws java.rmi.RemoteException;

  public java.lang.Short[] echoSoapShortArray(
      java.lang.Short[] inputSoapShortArray) throws java.rmi.RemoteException;

  public java.lang.Byte[] echoSoapByteArray(java.lang.Byte[] inputSoapByteArray)
      throws java.rmi.RemoteException;

  public byte[][] echoBase64BinaryArray(byte[][] inputBase64BinaryArray)
      throws java.rmi.RemoteException;

  public byte[][] echoHexBinaryArray(byte[][] inputHexBinaryArray)
      throws java.rmi.RemoteException;

  public byte[][] echoSoapBase64Array(byte[][] inputSoapBase64Array)
      throws java.rmi.RemoteException;

  public java.lang.String[] echoString1Array(
      java.lang.String[] inputString1Array) throws java.rmi.RemoteException;

  public java.math.BigInteger[] echoInteger1Array(
      java.math.BigInteger[] inputInteger1Array)
      throws java.rmi.RemoteException;

  public int[] echoInt1Array(int[] inputInt1Array)
      throws java.rmi.RemoteException;

  public long[] echoLong1Array(long[] inputLong1Array)
      throws java.rmi.RemoteException;

  public short[] echoShort1Array(short[] inputShort1Array)
      throws java.rmi.RemoteException;

  public java.math.BigDecimal[] echoDecimal1Array(
      java.math.BigDecimal[] inputDecimal1Array)
      throws java.rmi.RemoteException;

  public float[] echoFloat1Array(float[] inputFloat1Array)
      throws java.rmi.RemoteException;

  public double[] echoDouble1Array(double[] inputDouble1Array)
      throws java.rmi.RemoteException;

  public boolean[] echoBoolean1Array(boolean[] inputBoolean1Array)
      throws java.rmi.RemoteException;

  public byte[] echoByte1Array(byte[] inputByte1Array)
      throws java.rmi.RemoteException;

  public javax.xml.namespace.QName[] echoQName1Array(
      javax.xml.namespace.QName[] inputQName1Array)
      throws java.rmi.RemoteException;

  public java.util.Calendar[] echoDateTime1Array(
      java.util.Calendar[] inputDateTime1Array) throws java.rmi.RemoteException;

  public java.lang.String[] echoSoapString1Array(
      java.lang.String[] inputSoapString1Array) throws java.rmi.RemoteException;

  public java.lang.Boolean[] echoSoapBoolean1Array(
      java.lang.Boolean[] inputSoapBoolean1Array)
      throws java.rmi.RemoteException;

  public java.lang.Float[] echoSoapFloat1Array(
      java.lang.Float[] inputSoapFloat1Array) throws java.rmi.RemoteException;

  public java.lang.Double[] echoSoapDouble1Array(
      java.lang.Double[] inputSoapDouble1Array) throws java.rmi.RemoteException;

  public java.math.BigDecimal[] echoSoapDecimal1Array(
      java.math.BigDecimal[] inputSoapDecimal1Array)
      throws java.rmi.RemoteException;

  public java.lang.Integer[] echoSoapInt1Array(
      java.lang.Integer[] inputSoapInt1Array) throws java.rmi.RemoteException;

  public java.lang.Short[] echoSoapShort1Array(
      java.lang.Short[] inputSoapShort1Array) throws java.rmi.RemoteException;

  public java.lang.Byte[] echoSoapByte1Array(
      java.lang.Byte[] inputSoapByte1Array) throws java.rmi.RemoteException;

  public byte[][] echoBase64Binary1Array(byte[][] inputBase64Binary1Array)
      throws java.rmi.RemoteException;

  public byte[][] echoHexBinary1Array(byte[][] inputHexBinary1Array)
      throws java.rmi.RemoteException;

  public byte[][] echoSoapBase641Array(byte[][] inputSoapBase641Array)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.AllStruct echoAllStruct(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.AllStruct inputAllStruct)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.AllStruct[] echoAllStructArray(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.AllStruct[] inputAllStructArray)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.AllStruct2 echoAllStruct2(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.AllStruct2 inputAllStruct2)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.AllStruct2[] echoAllStruct2Array(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.AllStruct2[] inputAllStruct2Array)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.SequenceStruct echoSequenceStruct(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.SequenceStruct inputSequenceStruct)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.SequenceStruct[] echoSequenceStructArray(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.SequenceStruct[] inputSequenceStructArray)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.SequenceStruct2 echoSequenceStruct2(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.SequenceStruct2 inputSequenceStruct2)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.SequenceStruct2[] echoSequenceStruct2Array(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.SequenceStruct2[] inputSequenceStruct2Array)
      throws java.rmi.RemoteException;

  public void echoVoid() throws java.rmi.RemoteException;

  public void echoRemoteException(java.lang.String inputString)
      throws java.rmi.RemoteException;

  public void echoSubClassRemoteException(java.lang.String inputString)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumString echoEnumString(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumString inputEnumString)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumInteger echoEnumInteger(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumInteger inputEnumInteger)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumInt echoEnumInt(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumInt inputEnumInt)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumLong echoEnumLong(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumLong inputEnumLong)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumShort echoEnumShort(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumShort inputEnumShort)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumDecimal echoEnumDecimal(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumDecimal inputEnumDecimal)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumFloat echoEnumFloat(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumFloat inputEnumFloat)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumDouble echoEnumDouble(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumDouble inputEnumDouble)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumByte echoEnumByte(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.EnumByte inputEnumByte)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.NilTrueStruct echonilTrue(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.NilTrueStruct inputnilTrue)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.NilFalseStruct echonilFalse(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest.NilFalseStruct inputnilFalse)
      throws java.rmi.RemoteException;
}
