/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 2002 International Business Machines Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest;

public class NilFalseStruct {
  protected int nilint;

  protected long nillong;

  protected short nilshort;

  protected float nilfloat;

  protected double nildouble;

  protected boolean nilboolean;

  protected byte nilbyte;

  public NilFalseStruct() {
  }

  public NilFalseStruct(int nilint, long nillong, short nilshort,
      float nilfloat, double nildouble, boolean nilboolean, byte nilbyte) {
    this.nilint = nilint;
    this.nillong = nillong;
    this.nilshort = nilshort;
    this.nilfloat = nilfloat;
    this.nildouble = nildouble;
    this.nilboolean = nilboolean;
    this.nilbyte = nilbyte;
  }

  public int getNilint() {
    return nilint;
  }

  public void setNilint(int nilint) {
    this.nilint = nilint;
  }

  public long getNillong() {
    return nillong;
  }

  public void setNillong(long nillong) {
    this.nillong = nillong;
  }

  public short getNilshort() {
    return nilshort;
  }

  public void setNilshort(short nilshort) {
    this.nilshort = nilshort;
  }

  public float getNilfloat() {
    return nilfloat;
  }

  public void setNilfloat(float nilfloat) {
    this.nilfloat = nilfloat;
  }

  public double getNildouble() {
    return nildouble;
  }

  public void setNildouble(double nildouble) {
    this.nildouble = nildouble;
  }

  public boolean isNilboolean() {
    return nilboolean;
  }

  public void setNilboolean(boolean nilboolean) {
    this.nilboolean = nilboolean;
  }

  public byte getNilbyte() {
    return nilbyte;
  }

  public void setNilbyte(byte nilbyte) {
    this.nilbyte = nilbyte;
  }
}
