/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 2002 International Business Machines Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.marshalltest;

public class NilTrueStruct {
  protected java.lang.Integer nilint;

  protected java.lang.Long nillong;

  protected java.lang.Short nilshort;

  protected java.lang.Float nilfloat;

  protected java.lang.Double nildouble;

  protected java.lang.Boolean nilboolean;

  protected java.lang.Byte nilbyte;

  public NilTrueStruct() {
  }

  public NilTrueStruct(java.lang.Integer nilint, java.lang.Long nillong,
      java.lang.Short nilshort, java.lang.Float nilfloat,
      java.lang.Double nildouble, java.lang.Boolean nilboolean,
      java.lang.Byte nilbyte) {
    this.nilint = nilint;
    this.nillong = nillong;
    this.nilshort = nilshort;
    this.nilfloat = nilfloat;
    this.nildouble = nildouble;
    this.nilboolean = nilboolean;
    this.nilbyte = nilbyte;
  }

  public java.lang.Integer getNilint() {
    return nilint;
  }

  public void setNilint(java.lang.Integer nilint) {
    this.nilint = nilint;
  }

  public java.lang.Long getNillong() {
    return nillong;
  }

  public void setNillong(java.lang.Long nillong) {
    this.nillong = nillong;
  }

  public java.lang.Short getNilshort() {
    return nilshort;
  }

  public void setNilshort(java.lang.Short nilshort) {
    this.nilshort = nilshort;
  }

  public java.lang.Float getNilfloat() {
    return nilfloat;
  }

  public void setNilfloat(java.lang.Float nilfloat) {
    this.nilfloat = nilfloat;
  }

  public java.lang.Double getNildouble() {
    return nildouble;
  }

  public void setNildouble(java.lang.Double nildouble) {
    this.nildouble = nildouble;
  }

  public java.lang.Boolean getNilboolean() {
    return nilboolean;
  }

  public void setNilboolean(java.lang.Boolean nilboolean) {
    this.nilboolean = nilboolean;
  }

  public java.lang.Byte getNilbyte() {
    return nilbyte;
  }

  public void setNilbyte(java.lang.Byte nilbyte) {
    this.nilbyte = nilbyte;
  }
}
