type=page
status=published
title=Preface
next=intro.html
prev=title.html
~~~~~~
Preface
=======

[[GBFTI]][[preface]]

Preface
-------

[NOTE]
========================================================================

The Jakarta Enterprise Edition documentation is part of the Jakarta Enterprise 
Edition contribution to the Eclipse Foundation and is not intended for 
use in relation to Java Enterprise Edition or Java Licensee 
requirements. This documentation is in the process of being revised to 
reflect the new Jakarta EE requirements and branding. 
Additional changes will be made as requirements and procedures evolve 
for Jakarta EE. Where applicable, references to Java EE or Java 
Enterprise Edition should be considered references to Jakarta EE. 

Please see the Title page for additional license information.
========================================================================

This book introduces the Test Compatibility Kit (TCK) for the Jakarta
Platform, Enterprise Edition 9 (Jakarta EE 9) and Jakarta Platform, Enterprise
Edition 9 Web Profile (Jakarta EE 9 Web Profile), and explains how to
configure and run the test suite. It also provides information for
troubleshooting problems you may encounter as you run the test suite.

The Jakarta Platform, Enterprise Edition 9 Test Compatibility Kit (Jakarta
EE 9 TCK) is a portable, configurable automated test suite for verifying
the compatibility of an implementer's compliance with the Jakarta EE 9
Specification (hereafter referred to as the implementer's implementation, or VI).
The Jakarta EE 9 Platform TCK uses the JavaTest harness version 5.0 to run the
test suite.


[NOTE]
=======================================================================

URLs are provided so you can locate resources quickly. However, these
URLs are subject to changes that are beyond the control of the authors
of this guide.

=======================================================================


[[GBFUS]][[who-should-use-this-book]]

Who Should Use This Book
~~~~~~~~~~~~~~~~~~~~~~~~

This guide is for developers of the Jakarta EE 9 technology to assist them
in running the test suite that verifies compatibility of their
implementation of the Jakarta EE 9 Specification.


[[GJFXS]][[before-you-read-this-book]]

Before You Read This Book
~~~~~~~~~~~~~~~~~~~~~~~~~

Before reading this guide, you should familiarize yourself with the Java
programming language, the Jakarta Platform, Enterprise Edition 9 (Jakarta EE
9) Specification, and the JavaTest documentation.

The Jakarta Platform, Enterprise Edition 9 (Jakarta EE 9) Specification can be
downloaded from `https://projects.eclipse.org/projects/ee4j.jakartaee-platform`.

For documentation on the test harness used for running the Jakarta EE 9 Platform TCK
test suite, see
`https://wiki.openjdk.java.net/display/CodeTools/Documentation`.

[[GBFWF]][[typographic-conventions]]

Typographic Conventions
~~~~~~~~~~~~~~~~~~~~~~~

The following table describes the typographic conventions that are used
in this book.

[width="100%",cols="15%,40%,45%",options="header",]
|=======================================================================
|Convention |Meaning |Example
|Boldface |Boldface type indicates graphical user interface elements
associated with an action, terms defined in text, or what you type,
contrasted with onscreen computer output. a|
From the File menu, select Open Project.

A cache is a copy that is stored locally.

[source,oac_no_warn]
----
machine_name% su
Password:
----

|`Monospace` |Monospace type indicates the names of files and
directories, commands within a paragraph, URLs, code in examples, text
that appears on the screen, or text that you enter. a|
Edit your `.login` file.

Use `ls` `-a` to list all files.

`machine_name% you have mail.`

|Italic |Italic type indicates book titles, emphasis, or placeholder
variables for which you supply particular values. a|
Read Chapter 6 in the User's Guide.

Do not save the file.

The command to remove a file is `rm` filename.

|=======================================================================


[[FWBSD]][[shell-prompts-in-command-examples]]

Shell Prompts in Command Examples
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The following table shows the default UNIX system prompt and superuser
prompt for the C shell, Bourne shell, and Korn shell.

[width="100%",cols="50%,50%",options="header",]
|=====================================================
|Shell |Prompt
|C shell |`machine_name%`
|C shell for superuser |`machine_name#`
|Bourne shell and Korn shell |`$` +
|Bourne shell and Korn shell for superuser |`#` +
|Bash shell |`shell_name-shell_version$`
|Bash shell for superuser |`shell_name-shell_version#`
|=====================================================



