/*
 * Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.1, build R5)
// Generated source version: 1.1.1

package com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest;

import java.util.Map;
import java.util.HashMap;

public class EnumFloat {
  private float value;

  private static Map valueMap = new HashMap();

  public static final float _value1 = (float) -1.00000000;

  public static final float _value2 = (float) 3.00000000;

  public static final EnumFloat value1 = new EnumFloat(_value1);

  public static final EnumFloat value2 = new EnumFloat(_value2);

  protected EnumFloat(float value) {
    this.value = value;
    valueMap.put(this.toString(), this);
  }

  public float getValue() {
    return value;
  }

  public static EnumFloat fromValue(float value)
      throws java.lang.IllegalStateException {
    if (value1.value == value) {
      return value1;
    } else if (value2.value == value) {
      return value2;
    }
    throw new IllegalArgumentException();
  }

  public static EnumFloat fromString(String value)
      throws java.lang.IllegalStateException {
    EnumFloat ret = (EnumFloat) valueMap.get(value);
    if (ret != null) {
      return ret;
    }
    if (value.equals("-1.00000000")) {
      return value1;
    } else if (value.equals("3.00000000")) {
      return value2;
    }
    throw new IllegalArgumentException();
  }

  public String toString() {
    return new Float(value).toString();
  }

  private Object readResolve() throws java.io.ObjectStreamException {
    return fromValue(getValue());
  }

  public boolean equals(Object obj) {
    if (!(obj instanceof EnumFloat)) {
      return false;
    }
    return ((EnumFloat) obj).value == value;
  }

  public int hashCode() {
    return new Float(value).toString().hashCode();
  }
}
