/*
 * Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.1, build R5)
// Generated source version: 1.1.1

package com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest;

import java.util.Map;
import java.util.HashMap;

public class EnumShort {
  private short value;

  private static Map valueMap = new HashMap();

  public static final short _value1 = (short) -32768;

  public static final short _value2 = (short) 32767;

  public static final EnumShort value1 = new EnumShort(_value1);

  public static final EnumShort value2 = new EnumShort(_value2);

  protected EnumShort(short value) {
    this.value = value;
    valueMap.put(this.toString(), this);
  }

  public short getValue() {
    return value;
  }

  public static EnumShort fromValue(short value)
      throws java.lang.IllegalStateException {
    if (value1.value == value) {
      return value1;
    } else if (value2.value == value) {
      return value2;
    }
    throw new IllegalArgumentException();
  }

  public static EnumShort fromString(String value)
      throws java.lang.IllegalStateException {
    EnumShort ret = (EnumShort) valueMap.get(value);
    if (ret != null) {
      return ret;
    }
    if (value.equals("-32768")) {
      return value1;
    } else if (value.equals("32767")) {
      return value2;
    }
    throw new IllegalArgumentException();
  }

  public String toString() {
    return new Short(value).toString();
  }

  private Object readResolve() throws java.io.ObjectStreamException {
    return fromValue(getValue());
  }

  public boolean equals(Object obj) {
    if (!(obj instanceof EnumShort)) {
      return false;
    }
    return ((EnumShort) obj).value == value;
  }

  public int hashCode() {
    return new Short(value).toString().hashCode();
  }
}
