/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

// This class was generated by the JAXRPC RI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Reference Implementation (1.1, build EA-R13)

package com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest;

public interface ParameterModeTest extends java.rmi.Remote {
  public void echoIn(java.lang.String varString)
      throws java.rmi.RemoteException;

  public void echoOut(javax.xml.rpc.holders.StringHolder varString)
      throws java.rmi.RemoteException;

  public void echoInOut(javax.xml.rpc.holders.StringHolder varString)
      throws java.rmi.RemoteException;

  public void echoInOut2(javax.xml.rpc.holders.StringHolder varString)
      throws java.rmi.RemoteException;

  public java.lang.String echoInOut3(java.lang.String param)
      throws java.rmi.RemoteException;

  public java.lang.String echoInOut4(java.lang.String param)
      throws java.rmi.RemoteException;

  public void echoMix(java.lang.String varInString,
      javax.xml.rpc.holders.StringHolder varInOutString,
      javax.xml.rpc.holders.StringHolder varOutString)
      throws java.rmi.RemoteException;

  public void echoInSimpleTypes(java.lang.String varString,
      java.math.BigInteger varInteger, int varInt, long varLong, short varShort,
      java.math.BigDecimal varDecimal, float varFloat, double varDouble,
      boolean varBoolean, byte varByte, javax.xml.namespace.QName varQName,
      java.util.Calendar varDateTime, java.lang.String varSoapString,
      java.lang.Boolean varSoapBoolean, java.lang.Float varSoapFloat,
      java.lang.Double varSoapDouble, java.math.BigDecimal varSoapDecimal,
      java.lang.Integer varSoapInt, java.lang.Short varSoapShort,
      java.lang.Byte varSoapByte, byte[] varBase64Binary, byte[] varHexBinary,
      byte[] varSoapBase64) throws java.rmi.RemoteException;

  public void echoOutSimpleTypes(javax.xml.rpc.holders.StringHolder varString,
      javax.xml.rpc.holders.BigIntegerHolder varInteger,
      javax.xml.rpc.holders.IntHolder varInt,
      javax.xml.rpc.holders.LongHolder varLong,
      javax.xml.rpc.holders.ShortHolder varShort,
      javax.xml.rpc.holders.BigDecimalHolder varDecimal,
      javax.xml.rpc.holders.FloatHolder varFloat,
      javax.xml.rpc.holders.DoubleHolder varDouble,
      javax.xml.rpc.holders.BooleanHolder varBoolean,
      javax.xml.rpc.holders.ByteHolder varByte,
      javax.xml.rpc.holders.QNameHolder varQName,
      javax.xml.rpc.holders.CalendarHolder varDateTime,
      javax.xml.rpc.holders.StringHolder varSoapString,
      javax.xml.rpc.holders.BooleanWrapperHolder varSoapBoolean,
      javax.xml.rpc.holders.FloatWrapperHolder varSoapFloat,
      javax.xml.rpc.holders.DoubleWrapperHolder varSoapDouble,
      javax.xml.rpc.holders.BigDecimalHolder varSoapDecimal,
      javax.xml.rpc.holders.IntegerWrapperHolder varSoapInt,
      javax.xml.rpc.holders.ShortWrapperHolder varSoapShort,
      javax.xml.rpc.holders.ByteWrapperHolder varSoapByte,
      javax.xml.rpc.holders.ByteArrayHolder varBase64Binary,
      javax.xml.rpc.holders.ByteArrayHolder varHexBinary,
      javax.xml.rpc.holders.ByteArrayHolder varSoapBase64)
      throws java.rmi.RemoteException;

  public void echoInOutSimpleTypes(javax.xml.rpc.holders.StringHolder varString,
      javax.xml.rpc.holders.BigIntegerHolder varInteger,
      javax.xml.rpc.holders.IntHolder varInt,
      javax.xml.rpc.holders.LongHolder varLong,
      javax.xml.rpc.holders.ShortHolder varShort,
      javax.xml.rpc.holders.BigDecimalHolder varDecimal,
      javax.xml.rpc.holders.FloatHolder varFloat,
      javax.xml.rpc.holders.DoubleHolder varDouble,
      javax.xml.rpc.holders.BooleanHolder varBoolean,
      javax.xml.rpc.holders.ByteHolder varByte,
      javax.xml.rpc.holders.QNameHolder varQName,
      javax.xml.rpc.holders.CalendarHolder varDateTime,
      javax.xml.rpc.holders.StringHolder varSoapString,
      javax.xml.rpc.holders.BooleanWrapperHolder varSoapBoolean,
      javax.xml.rpc.holders.FloatWrapperHolder varSoapFloat,
      javax.xml.rpc.holders.DoubleWrapperHolder varSoapDouble,
      javax.xml.rpc.holders.BigDecimalHolder varSoapDecimal,
      javax.xml.rpc.holders.IntegerWrapperHolder varSoapInt,
      javax.xml.rpc.holders.ShortWrapperHolder varSoapShort,
      javax.xml.rpc.holders.ByteWrapperHolder varSoapByte,
      javax.xml.rpc.holders.ByteArrayHolder varBase64Binary,
      javax.xml.rpc.holders.ByteArrayHolder varHexBinary,
      javax.xml.rpc.holders.ByteArrayHolder varSoapBase64)
      throws java.rmi.RemoteException;

  public void echoInEnum(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.EnumString varEnumString,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.EnumInteger varEnumInteger,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.EnumInt varEnumInt,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.EnumLong varEnumLong,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.EnumShort varEnumShort,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.EnumDecimal varEnumDecimal,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.EnumFloat varEnumFloat,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.EnumDouble varEnumDouble,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.EnumByte varEnumByte)
      throws java.rmi.RemoteException;

  public void echoOutEnum(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumStringHolder varEnumString,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumIntegerHolder varEnumInteger,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumIntHolder varEnumInt,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumLongHolder varEnumLong,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumShortHolder varEnumShort,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumDecimalHolder varEnumDecimal,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumFloatHolder varEnumFloat,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumDoubleHolder varEnumDouble,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumByteHolder varEnumByte)
      throws java.rmi.RemoteException;

  public void echoInOutEnum(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumStringHolder varEnumString,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumIntegerHolder varEnumInteger,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumIntHolder varEnumInt,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumLongHolder varEnumLong,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumShortHolder varEnumShort,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumDecimalHolder varEnumDecimal,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumFloatHolder varEnumFloat,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumDoubleHolder varEnumDouble,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.EnumByteHolder varEnumByte)
      throws java.rmi.RemoteException;

  public void echoInStruct(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.AllStruct varStruct)
      throws java.rmi.RemoteException;

  public void echoInOutSimpleTypesArray(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOfstringHolder varString,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOfintegerHolder varInteger,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOfintHolder varInt,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOflongHolder varLong,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOfshortHolder varShort,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOfdecimalHolder varDecimal,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOffloatHolder varFloat,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOfdoubleHolder varDouble,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOfbooleanHolder varBoolean,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOfbyteHolder varByte,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOfQNameHolder varQName,
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOfdateTimeHolder varDateTime)
      throws java.rmi.RemoteException;

  public void echoInOutBook(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.BookHolder varBook)
      throws java.rmi.RemoteException;

  public void echoInOutBookArray(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.parametermodetest.holders.ArrayOfBookHolder varBook)
      throws java.rmi.RemoteException;
}
