#!/bin/sh
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0, which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# This Source Code may also be made available under the following Secondary
# Licenses when the conditions for such availability set forth in the
# Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
# version 2 with the GNU Classpath Exception, which is available at
# https://www.gnu.org/software/classpath/license.html.
#
# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
#

# Generate Specification Assertions
#

DOCS_DIR=/home/gsingh/spider-ws/internal/docs/jacc
TOOLS_DIR=/home/gsingh/cts-tools

# sort the assertions
#
#cd ${TOOLS_DIR}/tools/scripts
#./sort-spec-assertions ${DOCS_DIR}/JACCSpecAssertions.xml ${DOCS_DIR}/JACCSpecAssertions-sorted.xml

# Number the assertions
#
#cd ${TOOLS_DIR}/tools/number-assert 
#ant -Dinput_file=${DOCS_DIR}/JACCSpecAssertions-sorted.xml -Doutput_file=${DOCS_DIR}/JACCSpecAssertions-numbered.xml -Dreplace_tag=_NUMBER_ -Dinc_num=1 -Dstart_num=1 run

# Generate html output
#
cd ${TOOLS_DIR}/tools/xsl-transformer/scripts
./run ${DOCS_DIR}/JACCSpecAssertions.xml ${DOCS_DIR}/jaccRegrouping.xsl  ${DOCS_DIR}/JACCSpecAssertions.html

# Remove temporary files
#
#\rm -rf ${DOCS_DIR}/JACCSpecAssertions-numbered.xml ${DOCS_DIR}/JACCSpecAssertions-sorted.xml

