#!/bin/sh
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0, which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# This Source Code may also be made available under the following Secondary
# Licenses when the conditions for such availability set forth in the
# Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
# version 2 with the GNU Classpath Exception, which is available at
# https://www.gnu.org/software/classpath/license.html.
#
# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
#

SRC_DIR=/home/rperumal/jacc14/jacc-ri
TOOLS_DIR=/home/rperumal/cts-tools
OUTPUT_DIR=/home/rperumal/CTS14beta/internal/docs/jacc

mkdir ${OUTPUT_DIR}/temp

# Generate JACC Javadoc assertions
#
cd ${TOOLS_DIR}/tools/scripts/
./assert-gen3.sh JACC "JACC 1.0" "Java Authorization Contract for Containers" "1.0" ${SRC_DIR} ${OUTPUT_DIR}/temp jakarta.security.jacc 
# Copy generated Javadoc assertions from temp directory to ${OUTPUT_DIR} 
#
cp ${OUTPUT_DIR}/temp/assertions.html ${OUTPUT_DIR}/JACCJavadocAssertions.html

# Remove temporary directory
#
#\rm -rf ${OUTPUT_DIR}/temp

