
[[building-the-tests]]
= Building the Tests

For final certification and branding, you need to run the tests as shipped in the Jakarta TCK EE distribution bundle without modification. However, you can build and run the tests for debugging purposes. The one exception is the rebuildable tests, which you can modify and rebuild.

== Build the Platform TCK EE Tests

While the Jakarta TCK EE distribution bundle contains the test sources, they are not in a buildable Maven project form. To obtain a buildable version of the test sources from the Jakarta TCK EE GitHub repository, follow these steps:

. Clone the Jakarta TCK EE GitHub repository and checkout the release tag of interest:
+
[source,bash]
----
git clone https://github.com/jakartaee/platform-tck.git
cd platform-tck
git checkout jakartaeetck-{jakartaee_tck_version}
----
. Set your `JAVA_HOME` environment variable to point to a JDK 17+ installation.
. Build the test sources:
[source,bash]
----
mvn install
----

Your local Maven repository will now have the Jakarta TCK EE tests installed.
