
[[oracle]] 
Eclipse Foundation™
-------------------

Jakarta Platform, Enterprise Edition 11 Test Compatibility Kit User's
Guide

Release 11 for Jakarta EE

June 2022

Provides detailed instructions for obtaining, installing, configuring,
and using the Eclipse Jakarta, Enterprise Edition 11 Compatibility Test
Suite for the Full Profile and the Web Profile.

'''''

Jakarta Platform, Enterprise Edition 11 Test Compatibility Kit User's
Guide, Release 11 for Jakarta EE

Copyright © 2017, 2021 Oracle and/or its affiliates. All rights reserved.


Emeritus Author: Eric Jendrock

This program and the accompanying materials are made available under the terms of the Eclipse Public License v. 2.0, which is available at http://www.eclipse.org/legal/epl-2.0.

SPDX-License-Identifier: EPL-2.0

Oracle and Java are registered trademarks of Oracle and/or its affiliates. Other names may be trademarks of their respective owners.

Intel and Intel Xeon are trademarks or registered trademarks of Intel Corporation. All SPARC trademarks are used under license and are trademarks or registered trademarks of SPARC International, Inc. AMD, Opteron, the AMD logo, and the AMD Opteron logo are trademarks or registered trademarks of Advanced Micro Devices. UNIX is a registered trademark of The Open Group.


    References in this document to Java EE refer to the Jakarta EE unless otherwise noted.
