
[[common-troubleshooting]]
= Troubleshooting
:doctype: book

This chapter explains how to debug test failures that you could
encounter as you run the Jakarta Platform, Enterprise Edition Compatibility
Test Suite.

[[common-tck-problems-and-resolutions]]
== Common TCK Problems and Resolutions

This section lists common problems that you may encounter as you run the
Jakarta Platform, Enterprise Edition Test Compatibility Kit software on
the Jakarta Platform, Enterprise Edition CI, Eclipse GlassFish 6.1. It also proposes resolutions
for the problems, where applicable.

* Problem: +
The following exception may occur when a Jakarta EE {tck_version} Platform TCK test tries to
write a very long tracelog: +
[source,oac_no_warn]
----
java.lang.StringIndexOutOfBoundsException: String 
index out of range:
-13493
at java.lang.String.substring(String.java:1525)
at java.lang.String.substring(String.java:1492)
at javasoft.sqe.javatest.TestResult$Section
$WritableOutputBuffer.write(TestResult.java:650)
at java.io.Writer.write(Writer.java:153)
at java.io.PrintWriter.write(PrintWriter.java: 213)
at java.io.PrintWriter.write(PrintWriter.java: 229)
at java.io.PrintWriter.print(PrintWriter.java: 360)
at java.io.PrintWriter.println(PrintWriter.java:497)
at javasoft.sqe.javatest.lib.ProcessCommand
$StreamCopier.run(ProcessCommand.java:331)
----
The execution of the test will either fail or hang. +
Resolution: +
Set the `-Djavatest.maxOutputSize=`nnn system parameter in the
`runclient` and/or `gui` targets in the `<TS_HOME>/bin/build.xml` file
to a value that is higher than the default setting of `100,000` on the
JavaTest VM.

* Problem: +
When you start the Jakarta Platform, Enterprise Edition CI, Eclipse GlassFish 6.1 on 
Windows by using the `javaee -verbose` command, the system may not find
the specified path and could display one of the following errors: +
[source,oac_no_warn]
----
"Verify that JAVA_HOME is set correctly"
"Verify that JAKARTAEE_HOME is set correctly"
----
Resolution: +
Set `JAVA_HOME` to the path where the version of Java being used was
installed and set `JAKARTAEE_HOME` to the location of the Jakarta Platform,
Enterprise Edition installation directory.
* Problem: +
If the `cts.jar` and the `tsharness.jar` files are not loadable by the
extension classloader of your Jakarta Platform, Enterprise Edition server,
the following exception will be displayed in the window where the server
was started when you attempt to run the tests: +
[source,oac_no_warn]
----
java.lang.NoClassDefFoundError: com/sun/cts/util
RemoteLoggingInitException
----
Resolution: +
Ensure that the `cts.jar` and `tsharness.jar` files can be loaded by the
extension class loader of your Jakarta Platform, Enterprise Edition server.

* Problem: +
When running the Jakarta Persistence TCK tests you see an error log message containing:
[source,oac_no_warn]
----
LogFileProcessor setup failed
Please verify that the property log.file.location exists in ts.jte
----

Resolution: +
You may have the `log.file.location` set in the ts.jte file, but if your Jakarta Persistence integration eagerly loads the testcase custom persistence provider, it may do so before the `log.file.location` property is set by the TCK harness code. To resolve this issue, you can set the `log.file.location` system property in your server configuration.

[[support]]
== Support

Jakarta EE is a community sponsored and community supported project. If you need additional
assistance, you can reach out to the specific developer community. You will find the 
list of all Eclipse EE4J projects at `https://projects.eclipse.org/projects/ee4j`. All the sub-projects
are listed. Each project page has details regarding how to contact their developer community.


