[[executing-tests]]
= Executing Tests
:doctype: book

The Jakarta EE {tck_version} Platform TCK uses the JavaTest harness to execute the tests in the
test suite. For detailed instructions that explain how to run and use
JavaTest, see the JavaTest User's Guide and Reference.

This chapter includes the following topics:

* <<jakarta-ee-platform-tck-operating-assumptions>>
* <<starting-javatest>>
* <<validating-your-test-configuration>>
* <<running-a-subset-of-the-tests>>
* <<test-reports>>

[NOTE]
============
The instructions in this chapter assume that you have installed and configured your test environment as described
<<installation>> and <<setup-and-configuration>>
respectively.
============


[[jakarta-ee-platform-tck-operating-assumptions]]
== Jakarta EE {tck_version} Platform TCK Operating Assumptions

The following are assumed in this chapter:

* Jakarta EE {tck_version} CI is installed and configured as described in this guide.
* Detailed configuration will vary from product to product. In this guide, we provide details
for configuring the Jakarta EE CI, Eclipse GlassFish 6.1. If you are using another CI, refer to that
product's setup and configuration documentation.
* Java SE 8 software is correctly installed and configured on the host
machine.
* Jakarta EE {tck_version} Platform TCK is installed and configured as described in this guide.
* Implementations of the technologies to be tested are properly
installed and configured.

[[starting-javatest]]
== Starting JavaTest

There are two general ways to run Jakarta EE {tck_version} Platform TCK using the JavaTest
harness software:

* Through the JavaTest GUI
* From the command line in your shell environment

Running the JavaTest harness from JavaTest GUI is recommended for
initial configuration procedures, for validating your configuration, for
selecting tests to run, and for general ease-of-use when running tests
and viewing test reports.

Running the JavaTest harness from the command line is useful in headless
server configurations, and for running tests in batch mode.


[NOTE]
====
The `build.xml` file in `<TS_HOME>/bin` contains the various Ant
targets for the Jakarta EE {tck_version} Platform TCK test suite
====


[[running-test-cli]]
=== To Run Test in Command-Line Mode (Needs Rewrite)

1.  Set the `TS_HOME` environment variable to the directory in which
Jakarta EE {tck_version} Platform TCK was installed.
2.  Change to any subdirectory under `<TS_HOME>/src/com/sun/ts/tests`.
3.  Ensure that the `ts.jte` file contains information relevant to your
setup. +
Refer to link:config.html#GBFVV[Chapter 5, "Setup and Configuration,"]
for detailed configuration instructions.
4.  Execute the `runclient` Ant target to start the JavaTest: +
[source,oac_no_warn]
----
ant runclient
----
This runs all tests in the current directory and any subdirectories.

[[running-sigtest-example]]
==== Example 7-1 Running the Jakarta EE {tck_version} Platform TCK Signature Tests (Needs Rewrite)

To run the Jakarta EE {tck_version} Platform TCK signature tests, enter the following commands:

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests/signaturetest/javaee
ant runclient
----

[[running-tests-package]]
==== Example 7-2 Running a Single Test Directory (Needs Rewrite)

To run a single test directory in the `forward` direction, enter the
following commands:

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests/jaxws/api/jakarta_xml_ws/Dispatch
ant -Dkeywords=forward runclient
----

[[running-subset-tests]]
==== Example 7-3 Running a Subset of Test Directories (Needs Rewrite)

To run a subset of test directories in the `reverse` direction, enter
the following commands:

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests/jaxws/api
ant -Dkeywords=reverse runclient
----

[[validating-your-test-configuration]]
== Validating Your Test Configuration

[[to-validate-your-configuration-in-command-line-mode]]
=== To Validate Your Configuration in Command-Line Mode (Needs Rewrite)

.  Go to the `<TS_HOME>/src/com/sun/ts/tests/samples` directory.
.  Start the the test run by executing the following command: 
+
[source,oac_no_warn]
----
ant runclient
----
+
All sample tests will be run, and should pass.
.  Generate test reports by executing the following commands:
..  Change to the `<TS_HOME>/bin` directory: 
+
[source,oac_no_warn]
----
cd <TS_HOME>/bin
----
+
..  Run the `report` Ant target: 
+
[source,oac_no_warn]
----
ant report
----
+
Reports are written to the report directory you specified in
`<TS_HOME>/bin/ts.jte`. If no report directory is specified, reports are
written to the `/tmp/JTreport` directory (Solaris/Linux) or
`C:\temp\JTreport` (Windows).

[[running-a-subset-of-the-tests]]
== Running a Subset of the Tests (Needs Rewrite)

[[to-run-a-subset-of-tests-in-command-line-mode]]

=== To Run a Subset of Tests in Command-Line Mode

1.  Change to the directory containing the tests you want to run. +
For example, `<TS_HOME>/src/com/sun/ts/tests/samples`.
2.  Start the test run by executing the following command: 
+
[source,oac_no_warn]
----
ant runclient
----
+
The tests in `<TS_HOME>/src/com/sun/ts/tests/samples` and its
subdirectories are run.

[[GBFVL]][[to-run-a-subset-of-tests-in-batch-mode-based-on-prior-result-status]]


[[using-keywords-to-test]]
== Using Keywords to Test Required Technologies (Needs Rewrite)

The Jakarta EE TCK includes some tests that may be optional depending on
your implementation. For example, certain technologies are now optional
for implementations of the full Jakarta EE Platform. There are other
technologies which are optional for Web Profile implementations, but may
be implemented. If implemented, optional tests must be run and pass.
There are two mechanisms in place in the TCK which control whether or
not a given set of tests is run - the `javaee.level` property in the
`ts.jte` file (see <<setting-the-javaee.level-property>>) and keywords (see <<using-keywords-to-create-groups-and-subsets-of-tests>>).

[[setting-the-javaee.level-property]]
=== Setting the javaee.level Property

The `ts.jte` file includes the `javaee.level` property. This property
serves two purposes. First, it is used to determine whether the
implementation under test is a Jakarta EE Full profile (full) or Jakarta EE
Web profile (web). Either "full" or "web" must be specified in the list
values. A setting of "full" instructs the test harness to deploy EAR
files. A setting of "web" instructs the test harness to deploy WAR
files. The `javaee.level` property is also used to help determine which
APIs in the signature tests are to be tested. The comments that precede
the property setting in the `ts.jte` file provide additional information
about setting this property.

The default setting is as follows:

[source,oac_no_warn]
----
javaee.level=full
----

[[using-keywords-to-create-groups-and-subsets-of-tests]]
=== Using Keywords to Create Groups and Subsets of Tests (Needs Rewrite)

Each test in TCK has keywords associated with it. The keywords are used
to create groups and subsets of tests. At test execution time, a user
can tell the test harness to only run tests with or without certain
keywords. This mechanism is used to select or omit testing on selected
optional technologies. The "keywords" property can be set to a set of
available keywords joined by "&" and/or "|".

To set the keywords system property at runtime, you must either pass it
on the command line via `-Dkeywords=""` or in the JavaTest GUI, by
opening the test suite and performing the following steps:

1.  Select *View*, then select *Filters*, then select *CurrentConfiguration*.
2.  Select *Configure*, then select *ChangeConfiguration*, then select
*Keywords*.
3.  In the Keywords dialog, select the Select *Tests that Match* check
box, specify the desired keyword in the field, then click *Done*. +
Only tests that have been tagged with that keyword will be enabled in
the test tree.

The examples in the sections that follow show how to use keywords to run
required technologies in both the Full and Web profile, run/omit running
optional sets of tests in TCK, and run the Interoperability and
Rebuildable tests in forward and reverse directions.

[[to-use-keywords-to-run-required-technologies]]
==== To Use Keywords to Run Required Technologies (Needs Rewrite)

===== Example 7-4 Running Tests for Required Technologies in the Full Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords=javaee runclient
----

Only tests that are required by the Full Profile will be run.


===== Example 7-5 Running Tests for All Required Technologies in the Web Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords=javaee_web_profile runclient
----

Only tests that are required by the Web Profile will be run.

===== Example 7-6 Running All Required Tests Except Connector Tests in the Full Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords="javaee & !connector" runclient
----


===== Example 7-7 Running All EJB Tests in the Full Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords=ejb runclient
----


===== Example 7-8 Running All EJB 3.2 Tests in the Full Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords=ejb32 runclient
----


===== Example 7-9 Running All EJB Tests in the Web Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords=ejb_web_profile runclient
----

[[to-use-keywords-to-run-optional-subsets-of-tests-with-the-web-profile]]
==== To Use Keywords to Run Optional Subsets of Tests With the Web Profile (Needs Rewrite)

Keywords can be used to run subsets of tests from additional areas that
are not required by the Jakarta EE {tck_version} Web Profile specification. For
example, if your server implements the Jakarta EE {tck_version} Web Profile and the
Jakarta Connector Architecture 2.0 technology, set the keywords to
`javaee_web_profile|connector_web_profile` to enable running tests for
both areas. The command below shows how to specify these keywords to run
the tests in both areas.

[source,oac_no_warn]
----
ant -Dkeywords="(javaee_web_profile|connector_web_profile) runclient
----

<<keyword-web-profile-optional-table>> lists optional subsets of tests that can be run
for the Web Profile and provides the technology-to-keyword mappings for
each of the optional areas.

[[keyword-web-profile-optional-table]]
.Keyword to Technology Mappings for Web Profile Optional Subsets
[width="100%",cols="50%,50%",options="header",]
|==================================
|Technology |Keyword
|Jakarta Connectors |`connector_web_profile`
|Jakarta Mail (formerly JavaMail) |`javamail_web_profile`
|Jakarta Registries (formerly JAXR) |`jaxr_web_profile`
|Jakarta Messaging(formerly JMS) |`jms_web_profile`
|XA |`xa_web_profile`
|==================================


To add tests for other technologies, select the appropriate keyword from
<<keyword-web-profile-optional-table>>. This table provides a mapping of keywords to
optional technologies (test directories) in the test suite and indicates
optional test areas for the Jakarta EE {tck_version} Web Profile.

===== Example 7-12 Running Tests for All Optional Technologies in the Web Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords=javaee_web_profile_optional runclient
----

===== Example 7-13 Running the Optional Jakarta Authorization and Authentication Tests With All Required Web Profile Tests

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords="javaee_web_profile | jacc_web_profile | jaspic_web_profile" runclient
----

[[to-use-keywords-to-run-optional-subsets-for-jakarta-enterprise-beans-lite]]
==== To Use Keywords to Run Optional Subsets for Jakarta Enterprise Beans Lite

<<keyword-optional-jakarta-enterprise-beans-lite-table>> shows the TCK keywords you can use to test optional Jakarta Enterprise Beans (formerly EJB) Lite
components. Components denoted with an asterisk (*) are pruned
components; components without an asterisk are not required by EJB Lite.

[[keyword-optional-jakarta-enterprise-beans-lite-table]]
.TCK Keywords for Optional Jakarta Enterprise Beans Lite Components
[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Component |TCK Keyword
|Message-Driven Beans |`ejb_mdb_optional`

|1x CMP/BMP Entity Beans * |ejb_1x_optional

|2x CMP/BMP Entity Beans, Remote/Home Component, Local/Home Component *
|`ejb_2x_optional`

|3x Remote |`ejb_3x_remote_optional`

|EJB QL * |`ejb_ql_optional`

|Persistent Timer Service |`ejb_persistent_timer_optional`

|Remote asyncrhonous session bean |`ejb_remote_async_optional`

|EJB Embeddable Container |`ejb_embeddable_optional`
|=======================================================================


==== To Use Keywords to Run Tests in Forward and Reverse Directions (Needs Rewrite)

The `forward` and `reverse` keywords can be used to filter the interop
and/or rebuildable tests during a selected test run when running tests
in one of the following directories only:

[source,oac_no_warn]
----
<TS_HOME>/src/com/sun/ts/tests/jaxws
<TS_HOME>/src/com/sun/ts/tests/jws
<TS_HOME>/src/com/sun/ts/tests/interop
----

`Forward` tests are interop tests that run from the Vendor
Implementation to the Compatible Implementation, as well as rebuildable
tests that run only against the Vendor Implementation. Reverse tests
(with test names ending in _reverse) are interop tests that run from the
Compatible Implementation to the Vendor Implementation, as well as
rebuildable tests that run only against the Compatible Implementation.

To set one of these keywords when running in command-line mode, set the
appropriate keyword using the keyword system property.

===== Example 7-16 Running Tests in the Forward Direction

[source,oac_no_warn]
----
ant -Dkeywords=forward runclient
----

===== Example 7-17 Running Tests in the Reverse Direction

[source,oac_no_warn]
----
ant -Dkeywords=reverse runclient
----

To set one of these keywords in the Javatest GUI, select the Configure
menu item, then select Change Configuration, then select Keywords, and
set the appropriate keyword.

When one of these keywords has been set, executing tests in the
directories above causes only those tests that match the keyword to be
run. This can be useful when trying to debug failures with a particular
test configuration. Note, however, for certification all tests in both
directions must pass.


== Rebuilding Test Directories (Needs Rewrite)

The following directories require rebuilding, which is done by running
the `configure.datasource.tests` Ant target:

* `com/sun/ts/tests/ejb30/lite/packaging/war/datasource`
* `com/sun/ts/tests/ejb30/assembly/appres`
* `com/sun/ts/tests/ejb30/misc/datasource`

When the `configure.datasource.tests` Ant target is run from any
directory, it rebuilds these directories and any required
subdirectories.

The `com/sun/ts/tests/jms/ee20/resourcedefs` directory must also be
rebuilt. Run the `build.special.webservices.clients` Ant target to
rebuild the tests in this directory.

The database properties in the TCK bundle are set to Derby database. If
any other database is used, the `update.metadata.token.values` ant
target needs to be executed for metadata-complete tests.

The following directories require rebuilding:
`src\com\sun\ts\tests\appclient\deploy\metadatacomplete\testapp.`

This can be done by running the `update.metadata.token.values` Ant
target.

[[test-reports]]
== Test Reports (Needs Rewrite)

A set of report files is created for every test run. These report files
can be found in the report directory you specify. After a test run is
completed, the JavaTest harness writes HTML reports for the test run.
You can view these files in the JavaTest ReportBrowser when running in
GUI mode, or in the web browser of your choice outside the JavaTest
interface.

To see all of the HTML report files, enter the URL of the `report.html`
file. This file is the root file that links to all of the other HTML
reports.

The JavaTest harness also creates a `summary.txt` file in the report
directory that you can open in any text editor. The `summary.txt` file
contains a list of all tests that were run, their test results, and
their status messages.

Although you can run the Ant report target from any test directory, its
support is not guaranteed in the lower level directories. It is
recommended that you always run the report target from `<TS_HOME>/bin`,
from which reports are generated containing information about which
tests were or were not run.

[[creating-test-reports]]
=== Creating Test Reports

Specify where you want to create the test report.

1.  To specify the report directory from the command line at runtime,
use: 
+
[source,oac_no_warn]
----
ant report -Dreport.dir="report_dir"
----
+
Reports are written for the last test run to the directory you specify.
2.  To specify the default report directory, set the `report.dir`
property in `<TS_HOME>/bin/ts.jte`. +
For example, `report.dir="/home/josephine/reports"`.
3.  To disable reporting, set the `report.dir` property to `"none"`,
either on the command line or in `ts.jte`. +
For example: 
+
[source,oac_no_warn]
----
ant -Dreport.dir="none"
----

==== Troubleshooting

Although you can run the `report` Ant target from any test directory,
its support is not guaranteed in the lower level directories. It is
recommended that you always run the `report` target from
`<TS_HOME)/bin`, from which reports are generated containing information
about which tests were or were not run.cc

[[viewing-an-existing-test-report]]
=== Viewing an Existing Test Report

Use the Web browser of your choice to view the `report.html` file in the
report directory you specified from the command line or in `ts.jte`.

The current report directory is displayed when you run the `report`
target.
