[[executing-tests]]
= Executing Tests
:doctype: book

The Jakarta EE {tck_version} Platform TCK uses Arquillian and Junit5 as the test framework. The technology test artifacts have been split up into individual test artifacts based on the underlying component specification.

This chapter includes the following topics:

* <<jakarta-ee-platform-tck-operating-assumptions>>
* <<running-the-tests>>
* <<validating-your-test-configuration>>
* <<running-a-subset-of-the-tests>>
* <<test-reports>>

[NOTE]
============
The instructions in this chapter assume that you have installed and configured your test environment as described
<<installation>> and <<setup-and-configuration>>
respectively.
============


[[jakarta-ee-platform-tck-operating-assumptions]]
== Jakarta EE {tck_version} Platform TCK Operating Assumptions

The following are assumed in this chapter:

* Jakarta EE {tck_version} CI is installed and configured as described in this guide.
* Detailed configuration will vary from product to product. In this guide, we provide details
for configuring the Jakarta EE CI, Eclipse {glassfish_version}. If you are using another CI, refer to that product's setup and configuration documentation.
* Java SE 17/21 software is correctly installed and configured on the host
machine.
* Jakarta EE {tck_version} Platform TCK is installed and configured as described in this guide.
* Implementations of the technologies to be tested are properly
installed and configured.

[[running-the-tests]]
== Running the Tests

There are two general ways to run Jakarta EE {tck_version} Platform TCK using the Arquillian/Junit5 test harness software:

* Through a Java IDE that supports Junit5
* From a maven pom setup that configures the surefire plugin to run the tests

Running the tests in a Java IDE is useful for debugging and validating individual test setup.

Running the tests from a maven test runner pom is the standard way of automating the run of the complete set of tests and allows for producing test reports used to create a certification request.


[[running-test-cli]]
=== To Run Test in Command-Line Mode

Any framework that allows one to configure the run of Junit5 tests could be used, but in this section we will highlight the use of maven and the maven-surefire-plugin. The platform-tck project includes a set of maven runner projects for {glassfish_version} in the https://github.com/jakartaee/platform-tck/tree/main/glassfish-runner subproject. There is one runner project for each of the technology test artifacts. You can use these runners as a template for your own test runners, or you can create one complete test runner that includes all the technology test artifacts.

As a general rule, the test runner should include the following:

. Dependencies on the Junit5 and Arquillian test frameworks as shown in <<runner-maven-dependencies>>.
. Configure your Arquillian container as shown in <<arquillian-container-configuration>>.
.  Set the `TS_HOME` environment variable to the directory in which
Jakarta EE {tck_version} Platform TCK was installed.
.  Ensure that the `ts.jte` file contains information relevant to your
setup. +
Refer to <<setup-and-configuration>> for detailed configuration instructions, or that your runner maven project surefire/failsafe plugin has defined the equivalent system properties.
.  Execute the `test` Maven goal to start the testuite: +
[source,bash]
----
mvn test
----
This runs all tests in the current directory and any subdirectories.

[[runner-maven-dependencies]]
=== Maven Dependencies
Your runner configuration should have a dependencyManagement section that imports the Junit5 and Arquillian and Jakarta EE API bom dependencies:

[[maven-dependency-management]]
[source,xml,subs="attributes+"]
----
    <!-- The Junit5 test frameworks -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>{junit_version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.jboss.arquillian</groupId>
                <artifactId>arquillian-bom</artifactId>
                <version>{arquillian_version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.platform</groupId>
                <artifactId>jakarta.jakartaee-api</artifactId>
                <version>{jakartaee_api_version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.tck</groupId>
                <artifactId>artifacts-bom</artifactId>
                <version>{jakartaee_tck_version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
----

You then need to define the specific dependencies for the test runner without the version information:

[[maven-dependencies]]
[source,xml,subs="attributes+"]
----
    <dependencies>
        <!-- Jakarta EE APIs -->
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- The TCK test artifacts for components of interest -->
        <dependency>
            <groupId>jakarta.tck</groupId>
            <artifactId>ejb30</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.tck</groupId>
            <artifactId>ejb32</artifactId>
            <scope>test</scope>
        </dependency>

      <!-- TCK common dependencies -->
      <dependency>
        <groupId>jakarta.tck</groupId>
        <artifactId>common</artifactId>
      </dependency>

      <!-- TCK Arquillian artifacts -->
      <dependency>
        <groupId>jakarta.tck.arquillian</groupId>
        <artifactId>arquillian-protocol-appclient</artifactId>
      </dependency>
      <dependency>
        <groupId>jakarta.tck.arquillian</groupId>
        <artifactId>arquillian-protocol-javatest</artifactId>
      </dependency>
      <dependency>
        <groupId>jakarta.tck.arquillian</groupId>
        <artifactId>tck-porting-lib</artifactId>
      </dependency>

        <!--
            The Arquillian connector that starts the VI and deploys archives to it. This is the {glassfish_version} version.
        -->
        <dependency>
            <groupId>org.omnifaces.arquillian</groupId>
            <artifactId>arquillian-glassfish-server-managed</artifactId>
            <version>1.7</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
----

[[available-tck-test-artifacts]]
==== Available TCK Test Artifacts
The list of groupId:artifactId for the Jakarta EE {tck_version} TCK test artifacts is:

* jakarta.tck:appclient
* jakarta.tck:assembly-tck
* jakarta.tck:common
* jakarta.tck:cdi-tck-ee-impl
* jakarta.tck:connector
* jakarta.tck:ejb30
* jakarta.tck:ejb32
* jakarta.tck:el-platform-tck
* jakarta.tck:integration
* jakarta.tck:javaee-tck
* jakarta.tck:rest-platform-tck
* jakarta.tck:javamail
* jakarta.tck:jdbc-platform-tck
* jakarta.tck:jms-platform-tck
* jakarta.tck:project
* jakarta.tck:persistence-platform-tck-tests
* jakarta.tck:persistence-platform-tck-common
* jakarta.tck:persistence-platform-tck-dbprocedures
* jakarta.tck:persistence-platform-tck-spec-tests
* jakarta.tck:jsonb-platform-tck
* jakarta.tck:jsonp-platform-tck
* jakarta.tck:pages-platform-tck
* jakarta.tck:transactions-tck
* jakarta.tck:tags-tck
* jakarta.tck:signaturetest
* jakarta.tck:websocket-tck-platform-tests
* jakarta.tck:xa

The version of these artifacts is the same as the service release version of the TCK. You can find the latest version of these artifacts in the Jakarta staging repository or in the Maven Central repository. You can search for the jakarta.tck:artifacts-bom to find the latest version that has been released.

[[arquillian-container-configuration]]
=== Arquillian Container Configuration (JavaTest Protocol)
In addition to specifying the test framework and TCK test artifact dependencies, you need to configure the Arquillian container. The
Arquillian container manages the VI being tested and handles starting the container, deploying the test archives, and then stopping the container.

The configuration will depend on the container you are using, but you will need to include a configuration of the Arquillian javatest protocol for platform tests.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<arquillian xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://jboss.org/schema/arquillian"
            xsi:schemaLocation="http://jboss.org/schema/arquillian http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

  <engine>
        <property name="deploymentExportPath">target/deployments</property>
  </engine>
  <extension qualifier="glassfish-descriptors">
      <property name="descriptorDir">target/</property>
  </extension>

  <group qualifier="glassfish-servers" default="true">
    <container qualifier="tck-javatest" default="true">
        <configuration> <1>
            <property name="glassFishHome">target/glassfish8</property>
            <property name="debug">true</property>
            <property name="suspend">false</property>
        </configuration>
        <protocol type="javatest"> <2>
            <property name="trace">true</property>
            <property name="workDir">/tmp</property>
            <property name="tsJteFile">jakartaeetck/bin/ts.jte</property>
            <property name="tsSqlStmtFile">sql/derby/derby.dml.sql</property>
        </protocol>
    </container>
  </group>

</arquillian>
----
<1> This is the managed container specific config, here for Glassfish 8.
<2> This is the javatest protocol configuration.
* `tsJteFile` property is the path to the ts.jte file that contains the configuration for the test run.
* `tsSqlStmtFile` property is the path to the SQL file that contains the DML statements for the test run.
* the `trace` property is used to enable additional logging for the test run.
* the `workDir` property is the directory where the test TCK classes will put working files.

=== Arquillian Container Configuration (Appclient Protocol) (Full Platform Only)
TBD

[[running-sigtest-example]]
==== Example 7-1 Running the Jakarta EE {tck_version} Platform TCK Signature Tests (Needs Rewrite)

To run the Jakarta EE {tck_version} Platform TCK signature tests, enter the following commands:

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests/signaturetest/javaee
ant runclient
----

[[running-tests-package]]
==== Example 7-2 Running a Single Test Directory (Needs Rewrite)

To run a single test directory in the `forward` direction, enter the
following commands:

[source,oac_no_warn]
----
mvn ...
----


[[validating-your-test-configuration]]
== Validating Your Test Configuration

[[to-validate-your-configuration-in-command-line-mode]]
=== To Validate Your Configuration in Command-Line Mode (Needs Rewrite)

.  Go to the `<TS_HOME>/src/com/sun/ts/tests/samples` directory.
.  Start the test run by executing the following command:
+
[source,oac_no_warn]
----
ant runclient
----
+
All sample tests will be run, and should pass.
.  Generate test reports by executing the following commands:
..  Change to the `<TS_HOME>/bin` directory: 
+
[source,oac_no_warn]
----
cd <TS_HOME>/bin
----
+
..  Run the `report` Ant target: 
+
[source,oac_no_warn]
----
ant report
----
+
Reports are written to the report directory you specified in
`<TS_HOME>/bin/ts.jte`. If no report directory is specified, reports are
written to the `/tmp/JTreport` directory (Solaris/Linux) or
`C:\temp\JTreport` (Windows).

[[running-a-subset-of-the-tests]]
== Running a Subset of the Tests (Needs Rewrite)

[[to-run-a-subset-of-tests-in-command-line-mode]]

=== To Run a Subset of Tests in Command-Line Mode

1.  Change to the directory containing the tests you want to run. +
For example, `<TS_HOME>/src/com/sun/ts/tests/samples`.
2.  Start the test run by executing the following command: 
+
[source,oac_no_warn]
----
ant runclient
----
+
The tests in `<TS_HOME>/src/com/sun/ts/tests/samples` and its subdirectories are run.

[[to-run-a-subset-of-tests-in-batch-mode-based-on-prior-result-status]]


[[using-keywords-to-test]]
== Using Keywords to Test Required Technologies (Needs Rewrite)

The Jakarta EE TCK includes some tests that may be optional depending on
your implementation. For example, certain technologies are now optional
for implementations of the full Jakarta EE Platform. There are other
technologies which are optional for Web Profile implementations, but may
be implemented. If implemented, optional tests must be run and pass.
There are two mechanisms in place in the TCK which control whether or
not a given set of tests is run - the `javaee.level` property in the
`ts.jte` file (see <<setting-the-javaee.level-property>>) and keywords (see <<using-keywords-to-create-groups-and-subsets-of-tests>>).


[[using-keywords-to-create-groups-and-subsets-of-tests]]
=== Using Keywords to Create Groups and Subsets of Tests (Needs Rewrite)

Each test in TCK has keywords associated with it. The keywords are used
to create groups and subsets of tests. At test execution time, a user
can tell the test harness to only run tests with or without certain
keywords. This mechanism is used to select or omit testing on selected
optional technologies. The "keywords" property can be set to a set of
available keywords joined by "&" and/or "|".

To set the keywords system property at runtime, you must either pass it
on the command line via `-Dkeywords=""` or in the JavaTest GUI, by
opening the test suite and performing the following steps:

1.  Select *View*, then select *Filters*, then select *CurrentConfiguration*.
2.  Select *Configure*, then select *ChangeConfiguration*, then select
*Keywords*.
3.  In the Keywords dialog, select the Select *Tests that Match* check
box, specify the desired keyword in the field, then click *Done*. +
Only tests that have been tagged with that keyword will be enabled in
the test tree.

The examples in the sections that follow show how to use keywords to run
required technologies in both the Full and Web profile, run/omit running
optional sets of tests in TCK, and run the Interoperability and
Rebuildable tests in forward and reverse directions.

[[to-use-keywords-to-run-required-technologies]]
==== To Use Keywords to Run Required Technologies (Needs Rewrite)

===== Example 7-4 Running Tests for Required Technologies in the Full Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords=javaee runclient
----

Only tests that are required by the Full Profile will be run.


===== Example 7-5 Running Tests for All Required Technologies in the Web Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords=javaee_web_profile runclient
----

Only tests that are required by the Web Profile will be run.

===== Example 7-6 Running All Required Tests Except Connector Tests in the Full Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords="javaee & !connector" runclient
----


===== Example 7-7 Running All EJB Tests in the Full Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords=ejb runclient
----


===== Example 7-8 Running All EJB 3.2 Tests in the Full Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords=ejb32 runclient
----


===== Example 7-9 Running All EJB Tests in the Web Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords=ejb_web_profile runclient
----

[[to-use-keywords-to-run-optional-subsets-of-tests-with-the-web-profile]]
==== To Use Keywords to Run Optional Subsets of Tests With the Web Profile (Needs Rewrite)

Keywords can be used to run subsets of tests from additional areas that
are not required by the Jakarta EE {tck_version} Web Profile specification. For
example, if your server implements the Jakarta EE {tck_version} Web Profile and the
Jakarta Connector Architecture 2.0 technology, set the keywords to
`javaee_web_profile|connector_web_profile` to enable running tests for
both areas. The command below shows how to specify these keywords to run
the tests in both areas.

[source,oac_no_warn]
----
ant -Dkeywords="(javaee_web_profile|connector_web_profile) runclient
----

<<keyword-web-profile-optional-table>> lists optional subsets of tests that can be run
for the Web Profile and provides the technology-to-keyword mappings for
each of the optional areas.

[[keyword-web-profile-optional-table]]
.Keyword to Technology Mappings for Web Profile Optional Subsets
[width="100%",cols="50%,50%",options="header",]
|==================================
|Technology |Keyword
|Jakarta Connectors |`connector_web_profile`
|Jakarta Mail (formerly JavaMail) |`javamail_web_profile`
|Jakarta Registries (formerly JAXR) |`jaxr_web_profile`
|Jakarta Messaging(formerly JMS) |`jms_web_profile`
|XA |`xa_web_profile`
|==================================


To add tests for other technologies, select the appropriate keyword from
<<keyword-web-profile-optional-table>>. This table provides a mapping of keywords to
optional technologies (test directories) in the test suite and indicates
optional test areas for the Jakarta EE {tck_version} Web Profile.

===== Example 7-12 Running Tests for All Optional Technologies in the Web Profile

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords=javaee_web_profile_optional runclient
----

===== Example 7-13 Running the Optional Jakarta Authorization and Authentication Tests With All Required Web Profile Tests

[source,oac_no_warn]
----
cd <TS_HOME>/src/com/sun/ts/tests
ant -Dkeywords="javaee_web_profile | jacc_web_profile | jaspic_web_profile" runclient
----

[[to-use-keywords-to-run-optional-subsets-for-jakarta-enterprise-beans-lite]]
==== To Use Keywords to Run Optional Subsets for Jakarta Enterprise Beans Lite

<<keyword-optional-jakarta-enterprise-beans-lite-table>> shows the TCK keywords you can use to test optional Jakarta Enterprise Beans (formerly EJB) Lite
components. Components denoted with an asterisk (*) are pruned
components; components without an asterisk are not required by EJB Lite.

[[keyword-optional-jakarta-enterprise-beans-lite-table]]
.TCK Keywords for Optional Jakarta Enterprise Beans Lite Components
[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Component |TCK Keyword
|Message-Driven Beans |`ejb_mdb_optional`

|1x CMP/BMP Entity Beans * |ejb_1x_optional

|2x CMP/BMP Entity Beans, Remote/Home Component, Local/Home Component *
|`ejb_2x_optional`

|3x Remote |`ejb_3x_remote_optional`

|EJB QL * |`ejb_ql_optional`

|Persistent Timer Service |`ejb_persistent_timer_optional`

|Remote asyncrhonous session bean |`ejb_remote_async_optional`

|EJB Embeddable Container |`ejb_embeddable_optional`
|=======================================================================

== Rebuilding Test Directories (Needs Rewrite)

The following directories require rebuilding, which is done by running the `configure.datasource.tests` Ant target:

* `com/sun/ts/tests/ejb30/lite/packaging/war/datasource`
* `com/sun/ts/tests/ejb30/assembly/appres`
* `com/sun/ts/tests/ejb30/misc/datasource`

When the `configure.datasource.tests` Ant target is run from any
directory, it rebuilds these directories and any required
subdirectories.

=== JMS (Full Platform Only)
The `com/sun/ts/tests/jms/ee20/resourcedefs` tests may need to be updated and rebuilt for resource definitions...

The database properties in the TCK bundle are set to Derby database. If any other database is used, ...

The following directories require rebuilding:
`src\com\sun\ts\tests\appclient\deploy\metadatacomplete\testapp.`

This can be done by running the `update.metadata.token.values` Ant
target.

[[test-reports]]
== Test Reports (Needs Rewrite)

A set of report files is created for every test run. These report files
can be found in the report directory you specify. After a test run is
completed, the JavaTest harness writes HTML reports for the test run.
You can view these files in the JavaTest ReportBrowser when running in
GUI mode, or in the web browser of your choice outside the JavaTest
interface.

To see all of the HTML report files, enter the URL of the `report.html`
file. This file is the root file that links to all of the other HTML
reports.

The JavaTest harness also creates a `summary.txt` file in the report
directory that you can open in any text editor. The `summary.txt` file
contains a list of all tests that were run, their test results, and
their status messages.

Although you can run the Ant report target from any test directory, its
support is not guaranteed in the lower level directories. It is
recommended that you always run the report target from `<TS_HOME>/bin`,
from which reports are generated containing information about which
tests were or were not run.

[[creating-test-reports]]
=== Creating Test Reports

Specify where you want to create the test report.

1.  To specify the report directory from the command line at runtime,
use: 
+
[source,oac_no_warn]
----
ant report -Dreport.dir="report_dir"
----
+
Reports are written for the last test run to the directory you specify.
2.  To specify the default report directory, set the `report.dir`
property in `<TS_HOME>/bin/ts.jte`. +
For example, `report.dir="/home/josephine/reports"`.
3.  To disable reporting, set the `report.dir` property to `"none"`,
either on the command line or in `ts.jte`. +
For example: 
+
[source,oac_no_warn]
----
ant -Dreport.dir="none"
----

==== Troubleshooting

Although you can run the `report` Ant target from any test directory,
its support is not guaranteed in the lower level directories. It is
recommended that you always run the `report` target from
`<TS_HOME)/bin`, from which reports are generated containing information
about which tests were or were not run.cc

[[viewing-an-existing-test-report]]
=== Viewing an Existing Test Report

Use the Web browser of your choice to view the `report.html` file in the
report directory you specified from the command line or in `ts.jte`.

The current report directory is displayed when you run the `report`
target.
