[[setup-and-configuration-for-testing-with-the-jakarta-ee-11-web-profile]]
= Setup and Configuration for Testing with the Jakarta EE {tck_version} Web Profile

This chapter describes how to configure the Jakarta EE {tck_version} Platform TCK test suite to
work with your Jakarta EE {tck_version} Web Profile test environment. It is recommended
that you first set up the testing environment using the Jakarta EE {tck_version} Web
Profile CI and then with your Jakarta EE {tck_version} Web Profile server.

[[configuring-the-jakarta-ee-11-web-profile-test-environment]]
== Configuring the Jakarta EE {tck_version} Web Profile Test Environment

The instructions in this section and in <<configuring-your-application-server-as-the-vi>>
step you through the configuration process for the Solaris, Microsoft Windows, and Linux platforms.

[[to-run-tests-against-a-jakarta-ee-11-web-profile-implementation]]
== To Run Tests Against a Jakarta EE {tck_version} Web Profile Implementation

The Jakarta EE {tck_version} Platform TCK is the Technology Compatibility Kit (TCK) for the Jakarta
Platform, Enterprise Edition as well as the Jakarta EE {tck_version} Web Profile.
Implementations of the full Jakarta Platform, Enterprise Edition must pass
all of the tests as defined by Jakarta EE {tck_version} Platform TCK Rules in
<<procedure-for-jakarta-platform-enterprise-edition-certification>>.

Implementations of the Jakarta EE {tck_version} Web Profile must run the tests that
verify requirements defined by the Jakarta EE {tck_version} Web Profile Specification.
These tests are defined by the Rules in <<procedure-for-jakarta-platform-enterprise-edition-web-profile-certification>>. These requirements are a subset of the tests contained
in the Jakarta EE {tck_version} Platform TCK test suite. The test suite provides a mechanism
whereby only those tests for the Jakarta EE {tck_version} Web Profile will be run. The
following steps explain how to use this mechanism.

1.  Configure your runner pom.xml  maven-surefire-plugin to specify a group of 'web' as shown below:
+
[source,xml]
----
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
                <configuration>
                    <dependenciesToScan>...</dependency>
                    </dependenciesToScan>
                    <groups>web></groups>
...
            </plugin>
----
+
This setting will only allow WAR files (that is, no EAR files) to be
passed to the Deployment Porting Package. This is the minimal set of
requirements that vendors must support for Web Profile. Again, "web" only covers REQUIRED technologies for the Jakarta EE {tck_version} Web Profile.



