*{techID}10* Each Container must make technically accessible all Java SE
Runtime interfaces and functionality, as defined by the Specifications,
to programs running in the Container, except only as specifically
exempted by these Rules.

*{techID}10.1* Containers may impose security constraints, as defined by
the Specifications.

*{techID}11* A web Container must report an error, as defined by the
Specifications, when processing a {TechnologyShortName} Page that does not conform to the
Specifications.

*{techID}12* The presence of a Java language comment or Java language
directive in a {TechnologyShortName} Page that specifies ”java” as the scripting
language, when processed by a web Container, must not cause the
functional programmatic behavior of that {TechnologyShortName} Page to vary from the
functional programmatic behavior of that {TechnologyShortName} Page in the absence of
that Java language comment or Java language directive.

*{techID}13* The contents of any fixed template data (defined by the
Specifications) in a {TechnologyShortName} Page, when processed by a web Container, must
not affect the functional programmatic behavior of that {TechnologyShortName} Page,
except as defined by the Specifications.

*{techID}14* The functional programmatic behavior of a {TechnologyShortName} Page that
specifies ”java” as the scripting language must be equivalent to the
functional programmatic behavior of the {TechnologyShortName} Page Implementation Class
constructed from that {TechnologyShortName} Page.
