///////////////////////////////////////////////////////////////////////
NOTE TO WRITERS:
The following sections should be customized for the technology.
This text was originally from the JACC TCK.  Some references
to JACC have been parameterized to serve as a simple starting
point for customization.  There are still many details that will
need to be changed or removed.
///////////////////////////////////////////////////////////////////////

[[GBFHA]][[troubleshooting-tips]]

6.7 Troubleshooting Tips
~~~~~~~~~~~~~~~~~~~~~~~~

None for the Jakarta Annotations TCK.
