type=page
status=published
title=Technology Compatibility Kit User's Guide for Common Annotations for the Jakarta Platform 1.3, Release 1.3 for Jakarta EE
next=TCKpreface.html
prev=toc.html
~~~~~~
Technology Compatibility Kit User's Guide for Common Annotations for the Jakarta Platform 1.3, Release 1.3 for Jakarta EE
=========================================================================================================================

[[oracle]] 
Eclipse Foundation™
-------------------

Technology Compatibility Kit User's Guide for Common Annotations for the
Jakarta Platform 1.3

Release 1.3 for Jakarta EE

September 2017

[[sthref1]]

'''''

Technology Compatibility Kit User's Guide for Common Annotations for the
Java Platform 1.3, Release 1.3 for Jakarta EE

Copyright (c) 2009, 2018 Oracle and/or its affiliates. All rights reserved.

Emeritus Author: Eric Jendrock

This program and the accompanying materials are made available under the terms of the Eclipse Public License v. 2.0, which is available at http://www.eclipse.org/legal/epl-2.0.

SPDX-License-Identifier: EPL-2.0

Oracle and Java are registered trademarks of Oracle and/or its affiliates. Other names may be trademarks of their respective owners.

Intel and Intel Xeon are trademarks or registered trademarks of Intel Corporation. All SPARC trademarks are used under license and are trademarks or registered trademarks of SPARC International, Inc. AMD, Opteron, the AMD logo, and the AMD Opteron logo are trademarks or registered trademarks of Advanced Micro Devices. UNIX is a registered trademark of The Open Group.

This software or hardware and documentation may provide access to or information about content, products, and services from third parties. Oracle Corporation and its affiliates are not responsible for and expressly disclaim all warranties of any kind with respect to third-party content, products, and services unless otherwise set forth in an applicable agreement between you and Oracle. Oracle Corporation and its affiliates will not be responsible for any loss, costs, or damages incurred due to your access to or use of third-party content, products, or services, except as set forth in an applicable agreement between you and Oracle.