|Development Kit |A software product that implements or incorporates a
Compiler, a Schema Compiler, a Schema Generator, a Java-to-WSDL Tool, a
WSDL-to-Java Tool, and/or an RMI Compiler.

|Java-to-WSDL Output |Output of a Java-to-WSDL Tool that is required for
Web service deployment and invocation.

|Java-to-WSDL Tool |A software development tool that implements or
incorporates a function that generates web service endpoint descriptions
in WSDL and XML schema format from Source Code as specified by the
Jakarta XML Web Services Specification.

|WSDL-to-Java Output |Output of a WSDL-to-Java tool that is required for
Web service deployment and invocation.

|WSDL-to-Java Tool |A software development tool that implements or
incorporates a function that generates web service interfaces for
clients and endpoints from a WSDL description as specified by the
Jakarta XML Web Services Specification.
