type=page
status=published
title=Installation
next=config.html
prev=rules.html
~~~~~~
Installation
============

[[TCJWS00006]][[GBFTP]]


[[installation]]
3 Installation
--------------

This chapter explains how to install the Java API for XML Web Services
TCK 2.3 (JAX-WS TCK) software. After installing the software according
to the instructions in this chapter, proceed to
link:config.html#GBFVV[Chapter 4, "Setup and Configuration"] for
instructions on configuring your test environment.

[[GBFUD]][[TCJWS00055]][[obtaining-the-jax-ws-2.3-reference-implementation]]

3.1 Obtaining the JAX-WS 2.3 Reference Implementation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[GBFTS]][[TCJWS00056]][[installing-the-jax-ws-software]]

3.2 Installing the JAX-WS Software
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Before you can run the JAX-WS TCK tests, you must install and set up the
following software components:

* Java SE 8
* JAX-WS TCK version 2.3
* The JAX-WS 2.3 Reference Implementation (RI)
* The JAX-WS 2.3 Vendor Implementation (VI)
* The Java EE 8 RI which contains the JAX-WS 2.3 Reference
Implementation (RI)

1.  Install the Java SE software, if it is not already installed. +
Download and install the Java SE software from
`http://www.oracle.com/technetwork/java/javase/downloads/index.html`.
Refer to the installation instructions that accompany the software for
additional information.
2.  Install the JAX-WS TCK 2.3 software
1.  Copy or download the JAX-WS TCK software to your local system. 
2.  Use the `unzip` command to extract the bundle in the directory of
your choice: +
[source,oac_no_warn]
----
unzip jaxws-2_3-tck.zip
----
This command creates the `name="TCKinstalldir" content="jaxwstck"`
directory. The
install_directory`/``name="TCKinstalldir" content="jaxwstck"` directory
is the test suite home, `<TS_HOME>`.
3.  Install the Java EE 8 RI software which contains the JAX-WS 2.3
Reference Implementation or install the Standalone JAX-WS 2.3 RI
software. +
The Java EE 8 RI software contains the JAX-WS 2.3 Reference
Implementation and is used to validate your initial configuration and
setup of the JAX-WS TCK 2.3, as well as to run the reverse tests which
are explained further in link:config.html#GBFVV[Chapter 4, "Setup and
Configuration"] and link:rebuild.html#GCLIZ[Appendix B, "Rebuilding the
JAX-WS TCK Using the Vendor's Toolset"]. +
The Standalone JAX-WS 2.3 RI software contains the JAX-WS 2.3 Reference
Implementation and can be used with any web container that meets the
minimum requirements for a container as defined in the JAX-WS 2.3
Specification such as the Apache Tomcat web container. +
If you use the Standalone JAX-WS 2.3 RI software with the Apache Tomcat
web container, you need to copy the JAR files/classes from the
standalone JAX-WS 2.3 RI software to the correct location under the
Apache Tomcat web container. Assuming the Apache Tomcat web container is
installed under `${tomcat.home}`, you would copy the JAR files/classes
as follows: +
[source,oac_no_warn]
----
cp jaxws-api.jar jaxb-api.jar ${tomcat.home}/common/endorsed

cp commonj.sdo.jar eclipselink.jar FastInfoset.jar gmbal-api-only.jar ha-api.jar javax.annotation-api.jar javax.persistence.jar javax.xml.soap-api.jar jaxb-core.jar jaxb-impl.jar jaxb-jxc.jar jaxb-xjc.jar jaxws-eclipselink-plugin.jar jaxws-rt.jar jaxwstck.jar jaxws-tools.jar jsr181-api.jar mail.jar management-api.jar mimepull.jar policy.jar resolver.jar saaj-impl.jar sdo-eclipselink-plugin.jar stax2-api.jar stax-ex.jar streambuffer.jar tsharness.jar woodstox-core-asl.jar ${tomcat.home}/shared/lib

cp jaxwstck/lib/tsharness.jar jaxwstck/lib/jaxwstck.jar ${tomcat.home}/shared/lib 
----
If, instead of using Tomcat, you are using the Java EE 8 Reference
Implementation, which already includes JAX-WS 2.3, you only need to copy
the `jaxwstck/lib/tsharness.jar` and `jaxwstck/lib/jaxwstck.jar` TCK JAR
files to the domain's `lib/ext` directory.
4.  Install the JAX-WS 2.3 Vendor Implementation (VI) to be tested. +
Follow the installation instructions for the particular VI under test. +
Download, install, and configure the JAX-WS 2.3 VI configuration that is
under test. To familiarize yourself with the JAX-WS TCK suite and the
JavaTest software before you begin testing with your own implementation,
you can optionally do a trial run using the Java EE 8 RI.


