
*{techID}10* Source Code in WSDL-to-Java Output when compiled by a
Reference Compiler must execute properly when run on a Reference
Runtime.

*{techID}11* Source Code in WSDL-to-Java Output must be in source file
format defined by the Java Language Specification (JLS).

*{techID}12* Java-to-WSDL Output must fully meet W3C requirements for
the Web Services Description Language (WSDL) 1.1.

*{techID}13* A Java-to-WSDL Tool must not produce Java-to-WSDL Output
from source code that does not conform to the Java Language
Specification (JLS).
