<?xml version="1.0" encoding="utf-8"?>
<!--

    Copyright (c) 2003, 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<definitions
        name="W2JRLR2751TestDefs"
	targetNamespace="http://w2jrlr2751testservice.org/W2JRLR2751TestDefs.wsdl"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://w2jrlr2751testservice.org/W2JRLR2751TestDefs.wsdl"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:ns1="http://w2jrlr2751testservice.org/types4">

  <types>
    <xsd:schema elementFormDefault="qualified" attributeFormDefault="unqualified">
        <xsd:import namespace="http://w2jrlr2751testservice.org/types4" schemaLocation="W2JRLR2751TestDefs.xsd"/>
        </xsd:schema>
  </types>

  <message name="echoRequest">
    <part name="Item" type="xsd:string"/>
    <part name="ConfigHeader" element="ns1:ConfigHeaderRequest"/>
    <part name="ConfigHeader2" element="ns1:ConfigHeader2Request"/>
    <part name="ConfigHeader3" element="ns1:ConfigHeader3Request"/>
  </message>

  <message name="echoResponse">
    <part name="result" type="xsd:string"/>
  </message>

  <portType name="W2JRLR2751Test">
    <operation name="echoIt">
      <input message="tns:echoRequest"/>
      <output message="tns:echoResponse"/>
    </operation>
  </portType>

  <binding name="W2JRLR2751TestBinding" type="tns:W2JRLR2751Test">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/> 
      <operation name="echoIt">
        <soap:operation soapAction=""/>
        <input>
          <soap:body use="literal" parts="Item" namespace="http://w2jrlr2751testservice.org/W2JRLR2751TestDefs.wsdl"/>
   	     <soap:header message="tns:echoRequest" part="ConfigHeader" use="literal"/>
	     <soap:header message="tns:echoRequest" part="ConfigHeader2" use="literal"/>
	     <soap:header message="tns:echoRequest" part="ConfigHeader3" use="literal"/>
        </input>
        <output>
          <soap:body use="literal" namespace="http://w2jrlr2751testservice.org/W2JRLR2751TestDefs.wsdl"/>
        </output>
      </operation>
  </binding>
</definitions>
