[[executing-tests]]
= Executing Tests
:doctype: book

The Jakarta EE {tck_version} Platform TCK uses Arquillian and Junit5 as the test framework. The technology test artifacts have been split up into individual test artifacts based on the underlying component specification.

This chapter includes the following topics:

* <<jakarta-ee-platform-tck-operating-assumptions>>
* <<running-the-tests>>
* <<using-keywords-to-test>>
* <<rebuilding-test-for-different-databases>>
* <<test-reports>>

[NOTE]
============
The instructions in this chapter assume that you have installed and configured your test environment as described
<<installation>> and <<setup-and-configuration>> respectively.
============


[[jakarta-ee-platform-tck-operating-assumptions]]
== Jakarta EE {tck_version} Platform TCK Operating Assumptions

The following are assumed in this chapter:

* Jakarta EE {tck_version} CI is installed and configured as described in this guide.
* Detailed configuration will vary from product to product. In this guide, we provide details
for configuring the Jakarta EE CI, Eclipse {glassfish_version}. If you are using another CI, refer to that product's setup and configuration documentation.
* Java SE 17/21 software is correctly installed and configured on the host
machine.
* Jakarta EE {tck_version} Platform TCK is installed and configured as described in this guide.
* Implementations of the technologies to be tested are properly
installed and configured.

[[running-the-tests]]
== Running the Tests

There are two general ways to run Jakarta EE {tck_version} Platform TCK using the Arquillian/Junit5 test harness software:

* Through a Java IDE that supports Junit5
* From a maven pom setup that configures the surefire plugin to run the tests

Running the tests in a Java IDE is useful for debugging and validating individual test setup.

Running the tests from a maven test runner pom is the standard way of automating the run of the complete set of tests and allows for producing test reports used to create a certification request.


[[running-test-cli]]
=== To Run Test in Command-Line Mode

Any framework that allows one to configure the run of Junit5 tests could be used, but in this section we will highlight the use of maven and the maven-surefire-plugin. The platform-tck project includes a set of maven runner projects for {glassfish_version} in the https://github.com/jakartaee/platform-tck/tree/main/glassfish-runner subproject. There is one runner project for each of the technology test artifacts. You can use these runners as a template for your own test runners, or you can create one complete test runner that includes all the technology test artifacts.

As a general rule, the test runner should include the following:

. Dependencies on the Junit5 and Arquillian test frameworks as shown in <<runner-maven-dependencies>>.
. Configure your Arquillian container as shown in <<arquillian-container-configuration>>.
.  Set the `TS_HOME` environment variable to the directory in which
Jakarta EE {tck_version} Platform TCK was installed.
.  Ensure that the `ts.jte` file contains information relevant to your
setup. +
Refer to <<setup-and-configuration>> for detailed configuration instructions, or that your runner maven project surefire/failsafe plugin has defined the equivalent system properties.
.  Execute the `test` Maven goal to start the testsuite: +
[source,bash]
----
mvn test
----
This runs all tests in the current directory and any subdirectories.

[[runner-maven-dependencies]]
==== Maven Dependencies
Your runner configuration should have a dependencyManagement section that imports the Junit5 and Arquillian and Jakarta EE API and Jakarta TCK test artifact bom dependencies:

.Maven `dependencyManagement` Section
[[maven-dependency-management]]
[source,xml,subs="attributes+"]
----
    <!-- The Junit5 test frameworks -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>{junit_version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.jboss.arquillian</groupId>
                <artifactId>arquillian-bom</artifactId>
                <version>{arquillian_version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.platform</groupId>
                <artifactId>jakarta.jakartaee-api</artifactId>
                <version>{jakartaee_api_version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.tck</groupId>
                <artifactId>artifacts-bom</artifactId>
                <version>{jakartaee_tck_version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
----

You then need to define the specific dependencies for the test runner without the version information:

.Maven `dependencies` Section
[[maven-dependencies]]
[source,xml,subs="attributes+"]
----
    <dependencies>
        <!-- Jakarta EE APIs -->
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- The TCK test artifacts for components of interest -->
        <dependency>
            <groupId>jakarta.tck</groupId>
            <artifactId>ejb30</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.tck</groupId>
            <artifactId>ejb32</artifactId>
            <scope>test</scope>
        </dependency>

      <!-- TCK common dependencies -->
      <dependency>
        <groupId>jakarta.tck</groupId>
        <artifactId>common</artifactId>
      </dependency>

      <!-- TCK Arquillian artifacts -->
      <dependency>
        <groupId>jakarta.tck.arquillian</groupId>
        <artifactId>arquillian-protocol-appclient</artifactId>
      </dependency>
      <dependency>
        <groupId>jakarta.tck.arquillian</groupId>
        <artifactId>arquillian-protocol-javatest</artifactId>
      </dependency>
      <dependency>
        <groupId>jakarta.tck.arquillian</groupId>
        <artifactId>tck-porting-lib</artifactId>
      </dependency>

        <!--
            The Arquillian connector that starts the VI and deploys archives to it. This is the {glassfish_version} version.
        -->
        <dependency>
            <groupId>org.omnifaces.arquillian</groupId>
            <artifactId>arquillian-glassfish-server-managed</artifactId>
            <version>1.7</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
----

[[available-tck-test-artifacts]]
==== Available TCK Test Artifacts
The list of groupId:artifactId for the Jakarta EE {tck_version} TCK test artifacts is:

* jakarta.tck:appclient
* jakarta.tck:assembly-tck
* jakarta.tck:common
* jakarta.tck:cdi-tck-ee-impl
* jakarta.tck:connector
* jakarta.tck:ejb30
* jakarta.tck:ejb32
* jakarta.tck:el-platform-tck
* jakarta.tck:integration
* jakarta.tck:javaee-tck
* jakarta.tck:rest-platform-tck
* jakarta.tck:javamail
* jakarta.tck:jdbc-platform-tck
* jakarta.tck:jms-platform-tck
* jakarta.tck:project
* jakarta.tck:persistence-platform-tck-tests
* jakarta.tck:persistence-platform-tck-common
* jakarta.tck:persistence-platform-tck-dbprocedures
* jakarta.tck:persistence-platform-tck-spec-tests
* jakarta.tck:jsonb-platform-tck
* jakarta.tck:jsonp-platform-tck
* jakarta.tck:pages-platform-tck
* jakarta.tck:transactions-tck
* jakarta.tck:tags-tck
* jakarta.tck:signaturetest
* jakarta.tck:websocket-tck-platform-tests
* jakarta.tck:xa

The version of these artifacts is the same as the service release version of the TCK. You can find the latest version of these artifacts in the Jakarta staging repository or in the Maven Central repository. You can search for the jakarta.tck:artifacts-bom to find the latest version that has been released.

[[arquillian-container-configuration]]
==== Arquillian Container Configuration (JavaTest Protocol)
In addition to specifying the test framework and TCK test artifact dependencies, you need to configure the Arquillian container. The
Arquillian container manages the VI being tested and handles starting the container, deploying the test archives, and then stopping the container.

The configuration will depend on the container you are using, but you will need to include a configuration of the Arquillian javatest protocol for platform tests.

.Maven `arquillian.xml` javatest Protocol Configuration
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<arquillian xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://jboss.org/schema/arquillian"
            xsi:schemaLocation="http://jboss.org/schema/arquillian http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

  <engine>
        <property name="deploymentExportPath">target/deployments</property>
  </engine>
  <extension qualifier="glassfish-descriptors">
      <property name="descriptorDir">target/</property>
  </extension>

  <group qualifier="glassfish-servers" default="true">
    <container qualifier="tck-javatest" default="true">
        <configuration> <1>
            <property name="glassFishHome">target/glassfish8</property>
            <property name="debug">true</property>
            <property name="suspend">false</property>
        </configuration>
        <protocol type="javatest"> <2>
            <property name="trace">true</property>
            <property name="workDir">/tmp</property>
            <property name="tsJteFile">jakartaeetck/bin/ts.jte</property>
            <property name="tsSqlStmtFile">sql/derby/derby.dml.sql</property>
        </protocol>
    </container>
  </group>

</arquillian>
----
<1> This is the managed container specific config, here for Glassfish 8.
<2> This is the javatest protocol configuration.
* `tsJteFile` property is the path to the ts.jte file that contains the configuration for the test run.
* `tsSqlStmtFile` property is the path to the SQL file that contains the DML statements for the test run.
* the `trace` property is used to enable additional logging for the test run.
* the `workDir` property is the directory where the test TCK classes will put working files.

==== Arquillian Container Configuration (Appclient Protocol) (Full Platform Only)
TBD

[[running-sigtest-example]]
==== Example - Running the Jakarta EE {tck_version} Platform TCK Signature Tests (Needs Rewrite)

To run the Jakarta EE {tck_version} Platform TCK signature tests, enter the following commands:

[source,oac_no_warn]
----
TBD
----

[[running-tests-package]]
==== Example - Running a Single Test Package

To run a single test package, you would configure your surefile/failsafe plugin to have an execution that only includes the tests in the package you are interested in. For example, to run the tests in the `ee.jakarta.tck.persistence.ee.cdi` package, you would configure your surefire/failsafe plugin as shown in the following example:

[source,xml]
----
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.5.0</version>
                <configuration>
                    <trimStackTrace>false</trimStackTrace>
                    <dependenciesToScan>jakarta.tck:persistence-platform-tck-tests</dependenciesToScan>
                <executions>
                    <execution>
                        <id>jpa-tests-cdi</id>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            <includes>
                                <include>ee/jakarta/tck/persistence/ee/cdi/*Test.java</include><1>
                            </includes>


                            <systemPropertyVariables>
                                <arquillian.xml>cdi-arquillian.xml</arquillian.xml>
                            </systemPropertyVariables>
                        </configuration>
                    </execution>
...
               </executions>
            </plugin>
----
<1> Restrict the tests run to only those in the `ee.jakarta.tck.persistence.ee.cdi` package.

You could further restrict the included test to a specific test class by changing the include to the specific test class name.

[[using-keywords-to-test]]
== Using Keywords to Test Required Technologies

The Jakarta EE TCK includes Junit5 `@Tag` annotations that allow you to select a subset of tests based on the tag name. Each test in TCK has keywords associated with it. The keywords are used to create groups and subsets of tests. At test execution time, a user can tell the test harness to only run tests with or without certain groups.

The full list of available tags are:

* @Tag("assembly")
* @Tag("connector")
* @Tag("connector_standalone")
* @Tag("connector_web")
* @Tag("ejb")
* @Tag("ejb30")
* @Tag("ejb32")
* @Tag("ejb_web")
* @Tag("ejb_web_profile")
* @Tag("el")
* @Tag("integration")
* @Tag("jaxrs")
* @Tag("jdbc")
* @Tag("jms")
* @Tag("jms_web")
* @Tag("jsonb")
* @Tag("jsonp")
* @Tag("jsp")
* @Tag("jsp_security")
* @Tag("jstl")
* @Tag("jta")
* @Tag("mail")
* @Tag("persistence")
* @Tag("platform")
* @Tag("security")
* @Tag("signaturetest")
* @Tag("tck-appclient")
* @Tag("tck-javatest")
* @Tag("web")
* @Tag("websocket")
* @Tag("xa")

The most useful of these are the "platform" and "web" tags. The "platform" tag is used to run tests that are required by the Full Platform. The "web" tag is used to run tests that are required by the Web Profile.

[[to-use-keywords-to-run-required-technologies]]
=== To Use Keywords to Run Required Technologies

You use the `<groups>` element in the failsafe/surefire plugin configuration as described in the https://maven.apache.org/surefire/maven-failsafe-plugin/examples/junit-platform.html#filtering-by-tags[Failsafe Plugin documentation] to specify the tags you want to run.

==== Example - Running Tests for Required Technologies in the Full Platform

To restrict the tests to the group of tests that are required by the Full Platform, use the `platform` keyword.
[source,xml]
----
...
    <plugins>
        ...
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>3.5.2</version>
            <configuration>
                <groups>platform</groups>
            </configuration>
        </plugin>
    </plugins>
----

Only tests that are required by the Full Platform will be run.


=== Example - Running Tests for All Required Technologies in the Web Profile

To restrict the tests to the group of tests that are required by the Web Profile, use the `web` keyword.

[source,xml]
----
...
    <plugins>
        ...
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>3.5.2</version>
            <configuration>
                <groups>web</groups>
            </configuration>
        </plugin>
    </plugins>
----

Only tests that are required by the Web Profile will be run.

[[rebuilding-test-for-different-databases]]
== Rebuilding Tests for Different Databases

The following packages in the `jakarta.tck:ejb30` test artifact require rebuilding if you are using a database other than Derby:

* `com/sun/ts/tests/ejb30/lite/packaging/war/datasource`
* `com/sun/ts/tests/ejb30/misc/datasource/twojars`
* `com/sun/ts/tests/ejb30/misc/datasource/twowars`

The tests under these packages use classes with `@DataSourceDefinition` annotations with settings appropriate for the Derby database. If you are using a different database, you will need to update the `@DataSourceDefinition` annotations in these classes to match the settings for your database.

=== JMS (Full Platform Only)
The `com/sun/ts/tests/jms/ee20/resourcedefs` tests may need to be updated and rebuilt for resource definitions...

The database properties in the TCK bundle are set to Derby database. If any other database is used, ...

The following directories require rebuilding:
`src\com\sun\ts\tests\appclient\deploy\metadatacomplete\testapp.`


[[test-reports]]
== Test Reports

The Maven failsafe/surefire plugins generate test class reports in the `target/failsafe-reports` and `target/surefire-reports` directory respectively. The reports are in XML format and can be viewed in any XML viewer. They follow a naming convention of `TEST-<test-class-name>.xml`.

[[creating-test-reports]]
=== Creating Summary Test Reports

To create a summary report in html format, use the `surefire-report`  Maven plugin with:

* surefire-report:report-only - for reports on tests run with surefire
* surefire-report:failsafe-report-only - for reports on tests run with failsafe

For example, to create a summary report for tests run with failsafe, use the following command:
[source,bash]
----
mvn mvn surefire-report:failsafe-report-only
----

This will produce a target/reports/failsafe.html file that provides an overview summary as well as the individual test details.

For example, to create a summary report for tests run with surefire, use the following command:
[source,bash]
----
mvn mvn surefire-report:report-only
----

This will produce a target/reports/surefire.html file that provides an overview summary as well as the individual test details.
