DROP table INTEROP_CSIV2_TABLE1  !
CREATE table INTEROP_CSIV2_TABLE1 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE1 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE2  !
CREATE table INTEROP_CSIV2_TABLE2 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE2 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE3  !
CREATE table INTEROP_CSIV2_TABLE3 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE3 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE4  !
CREATE table INTEROP_CSIV2_TABLE4 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE4 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE5  !
CREATE table INTEROP_CSIV2_TABLE5 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE5 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE6  !
CREATE table INTEROP_CSIV2_TABLE6 (ID INTEGER NOT NULL ,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE6 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE7  !
CREATE table INTEROP_CSIV2_TABLE7 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE7 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE52  !
CREATE table INTEROP_CSIV2_TABLE52 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE52 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE8  !
CREATE table INTEROP_CSIV2_TABLE8 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE8 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE53  !
CREATE table INTEROP_CSIV2_TABLE53 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE53 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE10  !
CREATE table INTEROP_CSIV2_TABLE10 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE10 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE11  !
CREATE table INTEROP_CSIV2_TABLE11 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE11 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE12  !
CREATE table INTEROP_CSIV2_TABLE12 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE12 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE13 !
CREATE table INTEROP_CSIV2_TABLE13 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE13 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE14 !
CREATE table INTEROP_CSIV2_TABLE14 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE14 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE15 !
CREATE table INTEROP_CSIV2_TABLE15 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE15 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE16 !
CREATE table INTEROP_CSIV2_TABLE16 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE16 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE17 !
CREATE table INTEROP_CSIV2_TABLE17 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE17 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE18 !
CREATE table INTEROP_CSIV2_TABLE18 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE18 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE19 !
CREATE table INTEROP_CSIV2_TABLE19 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE19 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE20  !
CREATE table INTEROP_CSIV2_TABLE20 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE20 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE21 !
CREATE table INTEROP_CSIV2_TABLE21 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE21 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE22 !
CREATE table INTEROP_CSIV2_TABLE22 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE22 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE23 !
CREATE table INTEROP_CSIV2_TABLE23 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE23 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE24 !
CREATE table INTEROP_CSIV2_TABLE24 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE24 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE25 !
CREATE table INTEROP_CSIV2_TABLE25 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE25 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE26 !
CREATE table INTEROP_CSIV2_TABLE26 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE26 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE27 !
CREATE table INTEROP_CSIV2_TABLE27 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE27 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE28 !
CREATE table INTEROP_CSIV2_TABLE28 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE28 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE29 !
CREATE table INTEROP_CSIV2_TABLE29 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE29 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE30  !
CREATE table INTEROP_CSIV2_TABLE30 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE30 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE31 !
CREATE table INTEROP_CSIV2_TABLE31 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE31 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE32 !
CREATE table INTEROP_CSIV2_TABLE32 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE32 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE33 !
CREATE table INTEROP_CSIV2_TABLE33 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE33 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE34 !
CREATE table INTEROP_CSIV2_TABLE34 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE34 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE35 !
CREATE table INTEROP_CSIV2_TABLE35 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE35 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE36 !
CREATE table INTEROP_CSIV2_TABLE36 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE36 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE37 !
CREATE table INTEROP_CSIV2_TABLE37 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE37 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE38 !
CREATE table INTEROP_CSIV2_TABLE38 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE38 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE39 !
CREATE table INTEROP_CSIV2_TABLE39 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE39 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE40 !
CREATE table INTEROP_CSIV2_TABLE40 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE40 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE41 !
CREATE table INTEROP_CSIV2_TABLE41 (ID INTEGER NOT NULL,NAME  varchar(25),constraint INTEROP_CSIV2_TABLE41 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE42 !
CREATE table INTEROP_CSIV2_TABLE42 (KEY_ID INTEGER NOT NULL,BRAND_NAME  varchar(25),PRICE FLOAT,constraint INTEROP_CSIV2_TABLE42 primary key(KEY_ID)) !
DROP table INTEROP_CSIV2_TABLE43 !
CREATE table INTEROP_CSIV2_TABLE43 (ID INTEGER NOT NULL,NAME  varchar(25),PRICE REAL,constraint INTEROP_CSIV2_TABLE43 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE44 !
CREATE table INTEROP_CSIV2_TABLE44 (ID INTEGER NOT NULL,NAME  varchar(25),PRICE REAL,constraint INTEROP_CSIV2_TABLE44 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE45 !
CREATE table INTEROP_CSIV2_TABLE45 (ID INTEGER NOT NULL,NAME  varchar(25),PRICE REAL,constraint INTEROP_CSIV2_TABLE45 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE46 !
CREATE table INTEROP_CSIV2_TABLE46 (ID INTEGER NOT NULL,NAME  varchar(25),PRICE REAL,constraint INTEROP_CSIV2_TABLE46 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE47 !
CREATE table INTEROP_CSIV2_TABLE47 (ID INTEGER NOT NULL,NAME  varchar(25),PRICE REAL,constraint INTEROP_CSIV2_TABLE47 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE48 !
CREATE table INTEROP_CSIV2_TABLE48 (ID INTEGER NOT NULL,NAME  varchar(25),PRICE REAL,constraint INTEROP_CSIV2_TABLE48 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE49 !
CREATE table INTEROP_CSIV2_TABLE49 (ID INTEGER NOT NULL,NAME  varchar(25),PRICE REAL,constraint INTEROP_CSIV2_TABLE49 primary key(ID)) !
DROP table INTEROP_CSIV2_TABLE50 !
CREATE table INTEROP_CSIV2_TABLE50 (ID INTEGER NOT NULL,NAME  varchar(25),PRICE REAL,constraint INTEROP_CSIV2_TABLE50 primary key(ID)) !
DROP table INTEROP_COSNAMINGNOSSL_TABLE  !
CREATE table INTEROP_COSNAMINGNOSSL_TABLE (ID INTEGER NOT NULL,NAME  varchar(25),PRICE float,constraint INTEROP_COSNAMINGNOSSL_TABLE primary key(ID)) !
