--Need domains for tinyint and Boolean data type
drop domain boolean CASCADE;
drop domain tinyint CASCADE;
create domain boolean as bool;
create domain tinyint as smallint;

drop table ctstable2 ;
drop table ctstable1 ;
drop table concurrencetable ;
drop table Numeric_Tab ;
drop table Decimal_Tab ;
drop table Double_Tab ;
drop table Float_Tab ;
drop table Real_Tab ;
drop table Bit_Tab ;
drop table Smallint_Tab ;
drop table Tinyint_Tab ;
drop table Integer_Tab ;
drop table Bigint_Tab ;
drop table Char_Tab ;
drop table Varchar_Tab ;
drop table Longvarchar_Tab ;
drop table Longvarcharnull_Tab ;
drop table Date_Tab ;
drop table Time_Tab ;
drop table Timestamp_Tab ;
drop table Binary_Tab ;
drop table Varbinary_Tab ;
drop table Longvarbinary_Tab ;
drop table ctstable3 ;
drop table ctstable4 ;
drop table TxBean_Tab1 ;
drop table TxBean_Tab2 ;
drop table TxEBean_Tab ;
drop table Integration_Tab ;
drop table Integration_Sec_Tab ;
drop table BB_Tab ;
drop table JTA_Tab1 ;
drop table JTA_Tab2 ;
drop table Deploy_Tab1 ;
drop table Deploy_Tab2 ;
drop table Deploy_Tab3 ;
drop table Deploy_Tab4 ;
drop table Deploy_Tab5 ;
drop table Xa_Tab1 ;
drop table Xa_Tab2 ;
drop table SEC_Tab1 ;
drop table Connector_Tab ;
drop table Coffee_Table ;
drop table Coffee_StringPK_Table ;
drop table Coffee_LongPK_Table ;
drop table Coffee_FloatPK_Table ;
drop table Coffee_CompoundPK_Table ;
DROP TABLE COFFEEEJBLITE cascade;
DROP TABLE EJB_AUTOCLOSE_TAB ;


create table ctstable1 (TYPE_ID int, TYPE_DESC varchar(32), primary key(TYPE_ID)) ;
create table ctstable2 (KEY_ID int, COF_NAME varchar(32), PRICE float, TYPE_ID int, primary key(KEY_ID), foreign key(TYPE_ID) references ctstable1) ;
create table concurrencetable (TYPE_ID int, TYPE_DESC varchar(32), primary key(TYPE_ID)) ;
create table Numeric_Tab (MAX_VAL NUMERIC(30,15), MIN_VAL NUMERIC(30,15), NULL_VAL NUMERIC(30,15) NULL) ;
create table Decimal_Tab (MAX_VAL DECIMAL(30,15),MIN_VAL DECIMAL(30,15), NULL_VAL DECIMAL(30,15) NULL) ;
create table Double_Tab (MAX_VAL DOUBLE PRECISION, MIN_VAL DOUBLE PRECISION, NULL_VAL DOUBLE PRECISION NULL) ;
create table Float_Tab (MAX_VAL FLOAT8, MIN_VAL FLOAT8, NULL_VAL FLOAT8 NULL) ;
--create table Real_Tab (MAX_VAL real, MIN_VAL real ,NULL_VAL real NULL) ;
create table Real_Tab (MAX_VAL float8, MIN_VAL float8 ,NULL_VAL float8 NULL) ;
--create table Bit_Tab (MAX_VAL bit(1), MIN_VAL bit(1), NULL_VAL bit(1) NULL) ;
create table Bit_Tab (MAX_VAL boolean, MIN_VAL boolean, NULL_VAL boolean NULL) ;
create table Smallint_Tab (MAX_VAL SMALLINT, MIN_VAL SMALLINT, NULL_VAL SMALLINT NULL) ;
create table Tinyint_Tab (MAX_VAL SMALLINT, MIN_VAL SMALLINT, NULL_VAL SMALLINT NULL) ;
create table Integer_Tab (MAX_VAL INTEGER, MIN_VAL INTEGER, NULL_VAL INTEGER NULL) ;
--create table Bigint_Tab (MAX_VAL NUMERIC(19,0), MIN_VAL NUMERIC(19,0), NULL_VAL NUMERIC(19,0) NULL) ;
create table Bigint_Tab (MAX_VAL int8, MIN_VAL int8 , NULL_VAL int8  NULL) ;
create table Char_Tab (COFFEE_NAME CHAR(30), NULL_VAL CHAR(30) NULL) ;
create table Varchar_Tab (COFFEE_NAME VARCHAR(60), NULL_VAL VARCHAR(60) NULL) ;
create table Longvarchar_Tab (COFFEE_NAME TEXT) ;
create table Longvarcharnull_Tab (NULL_VAL TEXT NULL) ;
create table Date_Tab (MFG_DATE DATE, NULL_VAL DATE NULL) ;
create table Time_Tab (BRK_TIME TIME, NULL_VAL TIME NULL) ;
create table Timestamp_Tab (IN_TIME TIMESTAMP without time zone, NULL_VAL TIMESTAMP  without time zone ) ;
create table Binary_Tab (BINARY_VAL BYTEA NULL) ;
create table Varbinary_Tab (VARBINARY_VAL BYTEA NULL) ;
create table Longvarbinary_Tab (LONGVARBINARY_VAL BYTEA NULL) ;
CREATE TABLE ctstable3(STRING1 VARCHAR(20), STRING2 VARCHAR(20), STRING3 VARCHAR(20), NUMCOL NUMERIC, FLOATCOL FLOAT, DATECOL DATE, TIMECOL TIME, TSCOL1 DATE, TSCOL2 DATE) ;
CREATE TABLE ctstable4(STRING4 VARCHAR(20), NUMCOL NUMERIC) ;
create table TxBean_Tab1 (KEY_ID int, TABONE_NAME varchar(32), PRICE float) ;
create table TxBean_Tab2 (KEY_ID int, TABTWO_NAME varchar(32), PRICE float) ;
create table TxEBean_Tab (KEY_ID INTEGER NOT NULL, BRAND_NAME VARCHAR(32), PRICE FLOAT, primary key(KEY_ID)) ;
create table Integration_Tab (ACCOUNT INTEGER NOT NULL, BALANCE FLOAT, primary key(ACCOUNT)) ;
create table Integration_Sec_Tab (LOG_NO INTEGER, LINE_NO INTEGER, MESSAGE varchar(255)) ;
create table BB_Tab (KEY_ID INTEGER NOT NULL, BRAND_NAME varchar(32), PRICE float, primary key(KEY_ID)) ;
create table JTA_Tab1 (KEY_ID int, COF_NAME varchar(32), PRICE float) ;
create table JTA_Tab2 (KEY_ID int, CHOC_NAME varchar(32), PRICE float) ;
create table Deploy_Tab1 (KEY_ID INTEGER NOT NULL, BRAND_NAME varchar(32), PRICE float, primary key(KEY_ID)) ;
create table Deploy_Tab2 (KEY_ID VARCHAR(100) NOT NULL, BRAND_NAME varchar(32), PRICE float, primary key(KEY_ID)) ;
create table Deploy_Tab3 (KEY_ID INTEGER NOT NULL, BRAND_NAME varchar(32), PRICE float, primary key(KEY_ID)) ;
create table Deploy_Tab4 (KEY_ID FLOAT NOT NULL, BRAND_NAME varchar(32), PRICE float, primary key(KEY_ID)) ;
create table Deploy_Tab5 (KEY_ID1 int NOT NULL, KEY_ID2 varchar(100) NOT NULL, KEY_ID3 float NOT NULL, BRAND_NAME varchar(32), PRICE float, primary key(KEY_ID1, KEY_ID2, KEY_ID3)) ;
create table Xa_Tab1 (col1 int, col2 varchar(32), col3 varchar(32), primary key(col1)) ;
create table Xa_Tab2 (col1 int, col2 varchar(32), col3 varchar(32), primary key(col1)) ;
create table SEC_Tab1 (KEY_ID INTEGER NOT NULL, PRICE float, BRAND varchar(32), primary key(KEY_ID)) ;
create table Connector_Tab (KEY_ID int, PRODUCT_NAME varchar(32), PRICE float) ;
create table Coffee_Table (KEY_ID INTEGER NOT NULL, BRAND_NAME varchar(32) NOT NULL, PRICE float NOT NULL, primary key(KEY_ID)) ;
create table Coffee_StringPK_Table (KEY_ID VARCHAR(100) NOT NULL, BRAND_NAME varchar(32) NOT NULL, PRICE float NOT NULL, primary key(KEY_ID)) ;
create table Coffee_LongPK_Table (KEY_ID NUMERIC(38) NOT NULL, BRAND_NAME varchar(32) NOT NULL, PRICE float NOT NULL, primary key(KEY_ID)) ;
create table Coffee_FloatPK_Table (KEY_ID FLOAT NOT NULL, BRAND_NAME varchar(32) NOT NULL, PRICE float NOT NULL, primary key(KEY_ID)) ;
create table Coffee_CompoundPK_Table (KEY_ID1 int NOT NULL, KEY_ID2 varchar(100) NOT NULL, KEY_ID3 float NOT NULL, BRAND_NAME varchar(32) NOT NULL, PRICE float NOT NULL, primary key(KEY_ID1, KEY_ID2, KEY_ID3)) ;
CREATE TABLE COFFEEEJBLITE (ID INTEGER PRIMARY KEY NOT NULL, BRANDNAME VARCHAR(25), PRICE NUMERIC(126));
CREATE TABLE EJB_AUTOCLOSE_TAB (NAME VARCHAR(25) NOT NULL, MESSAGE VARCHAR(25) NOT NULL);