.  Install the Jakarta EE {JakartaEEVersion} CI software (the servlet Web container used
for running the {TechnologyShortName} TCK with the
{TechnologyShortName} {TechnologyVersion} CI), if it is not already
installed. +
Download and install the Servlet Web container with the
{TechnologyShortName} {TechnologyVersion} CI used for running the
{TechnologyShortName} TCK {TechnologyVersion}, represented by the Jakarta
EE {JakartaEEVersion} CI.
This software can be obtained from the Eclipse EE4J Github project
site. Refer to any installation instructions that accompany the software
for additional information.
