drop table INTEROP_CSIV2_TABLE1 CASCADE  ;
drop table INTEROP_CSIV2_TABLE2 CASCADE  ;
drop table INTEROP_CSIV2_TABLE3 CASCADE  ;
drop table INTEROP_CSIV2_TABLE4 CASCADE  ;
drop table INTEROP_CSIV2_TABLE5 CASCADE  ;
drop table INTEROP_CSIV2_TABLE6 CASCADE  ;
drop table INTEROP_CSIV2_TABLE7 CASCADE  ;
drop table INTEROP_CSIV2_TABLE52 CASCADE  ;
drop table INTEROP_CSIV2_TABLE8 CASCADE  ;
drop table INTEROP_CSIV2_TABLE53 CASCADE  ;
drop table INTEROP_CSIV2_TABLE10 CASCADE  ;
drop table INTEROP_CSIV2_TABLE11 CASCADE  ;
drop table INTEROP_CSIV2_TABLE12 CASCADE  ;
drop table INTEROP_CSIV2_TABLE13 CASCADE  ;
drop table INTEROP_CSIV2_TABLE14 CASCADE  ;
drop table INTEROP_CSIV2_TABLE15 CASCADE  ;
drop table INTEROP_CSIV2_TABLE16 CASCADE  ;
drop table INTEROP_CSIV2_TABLE17 CASCADE  ;
drop table INTEROP_CSIV2_TABLE18 CASCADE  ;
drop table INTEROP_CSIV2_TABLE19 CASCADE  ;
drop table INTEROP_CSIV2_TABLE20 CASCADE  ;
drop table INTEROP_CSIV2_TABLE21 CASCADE  ;
drop table INTEROP_CSIV2_TABLE22 CASCADE  ;
drop table INTEROP_CSIV2_TABLE23 CASCADE  ;
drop table INTEROP_CSIV2_TABLE24 CASCADE  ;
drop table INTEROP_CSIV2_TABLE25 CASCADE  ;
drop table INTEROP_CSIV2_TABLE26 CASCADE  ;
drop table INTEROP_CSIV2_TABLE27 CASCADE  ;
drop table INTEROP_CSIV2_TABLE28 CASCADE  ;
drop table INTEROP_CSIV2_TABLE29 CASCADE  ;
drop table INTEROP_CSIV2_TABLE30 CASCADE  ;
drop table INTEROP_CSIV2_TABLE31 CASCADE  ;
drop table INTEROP_CSIV2_TABLE32 CASCADE  ;
drop table INTEROP_CSIV2_TABLE33 CASCADE  ;
drop table INTEROP_CSIV2_TABLE34 CASCADE  ;
drop table INTEROP_CSIV2_TABLE35 CASCADE  ;
drop table INTEROP_CSIV2_TABLE36 CASCADE  ;
drop table INTEROP_CSIV2_TABLE37 CASCADE  ;
drop table INTEROP_CSIV2_TABLE38 CASCADE  ;
drop table INTEROP_CSIV2_TABLE39 CASCADE  ;
drop table INTEROP_CSIV2_TABLE40 CASCADE  ;
drop table INTEROP_CSIV2_TABLE41 CASCADE  ;
drop table INTEROP_CSIV2_TABLE42 CASCADE  ;
drop table INTEROP_CSIV2_TABLE43 CASCADE  ;
drop table INTEROP_CSIV2_TABLE44 CASCADE  ;
drop table INTEROP_CSIV2_TABLE45 CASCADE  ;
drop table INTEROP_CSIV2_TABLE46 CASCADE  ;
drop table INTEROP_CSIV2_TABLE47 CASCADE  ;
drop table INTEROP_CSIV2_TABLE48 CASCADE  ;
drop table INTEROP_CSIV2_TABLE49 CASCADE  ;
drop table INTEROP_CSIV2_TABLE50 CASCADE  ;
drop table INTEROP_COSNAMINGNOSSL_TABLE CASCADE  ;



create table INTEROP_CSIV2_TABLE1 ( ID  INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE1_PK_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE2 ( ID  INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE2_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE3 ( ID  INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE3_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE4 ( ID  INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE4_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE5 ( ID  INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE5_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE6 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE6_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE7 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE7_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE52 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE52_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE8 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE8_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE53 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE53_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE10 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE10_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE11 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE11_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE12 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE12_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE13 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE13_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE14 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE14_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE15 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE15_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE16 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE16_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE17 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE17_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE18 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE18_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE19 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE19_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE20 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE20_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE21 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE21_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE22 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE22_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE23 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE23_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE24 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE24_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE25 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE25_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE26 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE26_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE27 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE27_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE28 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE28_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE29 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE29_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE30 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE30_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE31 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE31_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE32 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE32_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE33 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE33_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE34 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE34_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE35 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE35_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE36 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE36_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE37 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE37_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE38 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE38_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE39 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE39_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE40 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE40_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE41 ( ID INTEGER, NAME  varchar(25), constraint INTEROP_CSIV2_TABLE41_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE42 ( KEY_ID INTEGER, BRAND_NAME  varchar(25), PRICE FLOAT, constraint INTEROP_CSIV2_TABLE42_PK primary key(KEY_ID)) ;
create table INTEROP_CSIV2_TABLE43 ( ID INTEGER, NAME  varchar(25), PRICE REAL, constraint INTEROP_CSIV2_TABLE43_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE44 ( ID INTEGER, NAME  varchar(25), PRICE REAL, constraint INTEROP_CSIV2_TABLE44_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE45 ( ID INTEGER, NAME  varchar(25), PRICE REAL, constraint INTEROP_CSIV2_TABLE45_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE46 ( ID INTEGER, NAME  varchar(25), PRICE REAL, constraint INTEROP_CSIV2_TABLE46_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE47 ( ID INTEGER, NAME  varchar(25), PRICE REAL, constraint INTEROP_CSIV2_TABLE47_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE48 ( ID INTEGER, NAME  varchar(25), PRICE REAL, constraint INTEROP_CSIV2_TABLE48_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE49 ( ID INTEGER, NAME  varchar(25), PRICE REAL, constraint INTEROP_CSIV2_TABLE49_PK primary key(ID)) ;
create table INTEROP_CSIV2_TABLE50 ( ID INTEGER, NAME  varchar(25), PRICE REAL, constraint INTEROP_CSIV2_TABLE50_PK primary key(ID)) ;
create table INTEROP_COSNAMINGNOSSL_TABLE ( ID  INTEGER, NAME  varchar(25), PRICE float, constraint INTEROP_COSNAMINGNOSSL_TABLE_PK primary key(ID)) ;  



