type=page
status=published
title=Introduction
next=rules.html
prev=TCKpreface.html
~~~~~~
Introduction
============

[[TCCON00002]][[GBFOW]]


[[introduction]]
1 Introduction
--------------

This chapter provides an overview of the principles that apply generally
to all Technology Compatibility Kits (TCKs) and describes the Java EE
Connector Architecture TCK (JCA TCK 1.7) (JSR 322). It also includes a
high level listing of what is needed to get up and running with the JCA
TCK.

[[GBFTK]][[TCCON00037]][[compatibility-testing]]

1.1 Compatibility Testing
~~~~~~~~~~~~~~~~~~~~~~~~~

Compatibility testing differs from traditional product testing in a
number of ways. The focus of compatibility testing is to test those
features and areas of an implementation that are likely to differ across
other implementations, such as those features that:

* Rely on hardware or operating system-specific behavior
* Are difficult to port
* Mask or abstract hardware or operating system behavior

Compatibility test development for a given feature relies on a complete
specification and reference implementation for that feature.
Compatibility testing is not primarily concerned with robustness,
performance, or ease of use.

[[GBFQN]][[TCCON00066]][[why-compatibility-testing-is-important]]

1.1.1 Why Compatibility Testing is Important
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Java platform compatibility is important to different groups involved
with Java technologies for different reasons:

* Compatibility testing ensures that the Java platform does not become
fragmented as it is ported to different operating systems and hardware
environments.
* Compatibility testing benefits developers working in the Java
programming language, allowing them to write applications once and then
to deploy them across heterogeneous computing environments without
porting.
* Compatibility testing allows application users to obtain applications
from disparate sources and deploy them with confidence.
* Conformance testing benefits Java platform implementors by ensuring a
level playing field for all Java platform ports.

[[GBFPR]][[TCCON00067]][[tck-compatibility-rules]]

1.1.2 TCK Compatibility Rules
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compatibility criteria for all technology implementations are embodied
in the TCK Compatibility Rules that apply to a specified technology.
Each TCK tests for adherence to these Rules as described in
link:rules.html#GBFSN[Chapter 2, "Procedure for Java EE Connector
Architecture (JCA) 1.7 Certification."]

[[GBFPW]][[TCCON00068]][[tck-overview]]

1.1.3 TCK Overview
^^^^^^^^^^^^^^^^^^

A TCK is a set of tools and tests used to verify that a licensee's
implementation of a technology conforms to the applicable specification.
All tests in the TCK are based on the written specifications for the
Java platform. A TCK tests compatibility of a licensee's implementation
of a technology to the applicable specification of the technology.
Compatibility testing is a means of ensuring correctness, completeness,
and consistency across all implementations developed by technology
licensees.

The set of tests included with each TCK is called the test suite. Most
tests in a TCK's test suite are self-checking, but some tests may
require tester interaction. Most tests return either a Pass or Fail
status. For a given platform to be certified, all of the required tests
must pass. The definition of required tests may change from platform to
platform.

The definition of required tests will change over time. Before your
final certification test pass, be sure to download the latest Exclude
List for the TCK you are using.

[[GBFPB]][[TCCON00069]][[java-community-process-jcp-program-and-compatibility-testing]]

1.1.4 Java Community Process (JCP) Program and Compatibility Testing
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The Java Community Process (JCP) program is the formalization of the
open process that has been used since 1995 to develop and revise Java
technology specifications in cooperation with the international Java
community. The JCP program specifies that the following three major
components must be included as deliverables in a final Java technology
release under the direction of the responsible Expert Group:

* Technology Specification
* Reference Implementation
* Technology Compatibility Kit (TCK)

For further information about the JCP program, go to Java Community
Process (`http://jcp.org`).

[[GBFQR]][[TCCON00038]][[about-the-jca-tck-1.7]]

1.2 About the JCA TCK 1.7
~~~~~~~~~~~~~~~~~~~~~~~~~

The JCA TCK 1.7 is designed as a portable, configurable, automated test
suite for verifying the compatibility of a licensee's implementation of
JCA 1.7 Specification.

[[GBFQV]][[TCCON00070]][[jca-tck-specifications-and-requirements]]

1.2.1 JCA TCK Specifications and Requirements
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This section lists the applicable requirements and specifications.

* Specification Requirements: Software requirements for a JCA
implementation are described in detail in the JCA 1.7 Specification.
Links to the JCA specification and other product information can be
found at
`http://jcp.org/aboutJava/communityprocess/final/jsr322/index.html`.
* JCA Version: The JCA TCK 1.7 is based on the JCA Specification,
Version 1.7.
* Reference Runtime: The designated Reference Runtime for conformance
testing of implementations based upon the JCA Specification 1.7 is JCA
1.7 Reference Implementation.

[[GBFSQ]][[TCCON00071]][[jca-tck-components]]

1.2.2 JCA TCK Components
^^^^^^^^^^^^^^^^^^^^^^^^

The JCA TCK 1.7 includes the following components:

* JavaTest harness version 4.4.1 and related documentation, which is
available in the JCA TCK documentation bundle
* JCA TCK signature tests, which check that all public APIs are
supported and/or defined as specified in the JCA Version 1.7
implementation under test
* API tests for all of the packages that comprise the required class
libraries for Java EE Connector Architecture 1.7
* End-to-end tests, which demonstrate compliance with the Java EE
Connector Architecture 1.7 specification

[[GBFSA]][[TCCON00072]][[javatest-harness]]

1.2.3 JavaTest Harness
^^^^^^^^^^^^^^^^^^^^^^

The JavaTest harness version 4.4.1 is a set of tools designed to run and
manage test suites on different Java platforms. The JavaTest harness can
be described as both a Java application and a set of compatibility
testing tools. It can run tests on different kinds of Java platforms and
it allows the results to be browsed online within the JavaTest GUI, or
offline in the HTML reports that the JavaTest harness generates.

The JavaTest harness includes the applications and tools that are used
for test execution and test suite management. It supports the following
features:

* Sequencing of tests, allowing them to be loaded and executed
automatically
* Graphic user interface (GUI) for ease of use
* Automated reporting capability to minimize manual errors
* Failure analysis
* Test result auditing and auditable test specification framework
* Distributed testing environment support

To run tests using the JavaTest harness, you specify which tests in the
test suite to run, how to run them, and where to put the results as
described in link:config.html#GBFVV[Chapter 4, "Setup and
Configuration."]

[[GBFRA]][[TCCON00073]][[tck-compatibility-test-suite]]

1.2.4 TCK Compatibility Test Suite
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The test suite is the collection of tests used by the JavaTest harness
to test a particular technology implementation. In this case, it is the
collection of tests used by the JCA TCK 1.7 to test a JCA 1.7
implementation. The tests are designed to verify that a licensee's
runtime implementation of the technology complies with the appropriate
specification. The individual tests correspond to assertions of the
specification.

The tests that make up the TCK compatibility test suite are precompiled
and indexed within the TCK test directory structure. When a test run is
started, the JavaTest harness scans through the set of tests that are
located under the directories that have been selected. While scanning,
the JavaTest harness selects the appropriate tests according to any
matches with the filters you are using and queues them up for execution.

[[GBFSH]][[TCCON00074]][[exclude-lists]]

1.2.5 Exclude Lists
^^^^^^^^^^^^^^^^^^^

Each version of a TCK includes an Exclude List contained in a `.jtx`
file. This is a list of test file URLs that identify tests which do not
have to be run for the specific version of the TCK being used. Whenever
tests are run, the JavaTest harness automatically excludes any test on
the Exclude List from being executed.

A licensee is not required to pass or run any test on the Exclude List.
The Exclude List file, `<TS_HOME``>/bin/ts.jtx`, is included in the JCA
TCK.


[NOTE]
=======================================================================

In these instructions, variables in angle brackets need to be expanded
for each platform. For example, `<TS_HOME>` becomes `$TS_HOME` on
Solaris/Linux and `%TS_HOME%` on Windows. In addition, the forward
slashes (`/`) used in all of the examples need to be replaced with
backslashes (`\`) for Windows. Finally, be sure to use the appropriate
separator for your operating system when specifying multiple path
entries (`;` on Windows, `:` on Solaris/Linux).

=======================================================================



[NOTE]
=======================================================================

You should always make sure you are using an up-to-date copy of the
Exclude List before running the JCA TCK to verify your implementation.

=======================================================================


A test might be in the Exclude List for reasons such as:

* An error in an underlying implementation API has been discovered which
does not allow the test to execute properly.
* An error in the specification that was used as the basis of the test
has been discovered.
* An error in the test itself has been discovered.
* The test fails due to a bug in the tools (such as the JavaTest
harness, for example).

In addition, all tests are run against the reference implementations.
Any tests that fail when run on a reference Java platform are put on the
Exclude List. Any test that is not specification-based, or for which the
specification is vague, may be excluded. Any test that is found to be
implementation dependent (based on a particular thread scheduling model,
based on a particular file system behavior, and so on) may be excluded.


[NOTE]
=======================================================================

Licensees are not permitted to alter or modify Exclude Lists. Changes to
an Exclude List can only be made by using the procedure described in
link:rules.html#CJAFFBHF[Section 2.3.1, "Java EE Connector Architecture
Version 1.7 TCK Test Appeals Steps."]

=======================================================================


[[GBFRR]][[TCCON00075]][[jca-tck-configuration]]

1.2.6 JCA TCK Configuration
^^^^^^^^^^^^^^^^^^^^^^^^^^^

You need to set several variables in your test environment, modify
properties in the `<TS_HOME>/bin/ts.jte` file, and then use the JavaTest
harness to configure and run the JCA tests, as described in
link:config.html#GBFVV[Chapter 4, "Setup and Configuration."]

[[GBFQW]][[TCCON00039]][[getting-started-with-the-jca-tck]]

1.3 Getting Started With the JCA TCK
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This section provides an general overview of what needs to be done to
install, set up, test, and use the JCA TCK. These steps are explained in
more detail in subsequent chapters of this guide.

1.  Make sure that the following software has been correctly installed
on the system hosting the JavaTest harness:
* Java SE 7
* Java EE 7 Web Profile RI or an implementation of the Java EE Connector
Architecture 1.7 specification
* Java EE Connector Architecture TCK Version 1.7 +

[NOTE]
=======================================================================

You should not run the standalone Java EE Connector Architecture TCK
tests with an RI that is compliant with the Java EE 7 Reference
Implementation (Classic Profile). If you plan to run with this
configuration, you must pass the Java EE Connector Architecture tests
that are bundled as part of the Java EE 7 platform's Compatibility Test
Suite (CTS).

=======================================================================

See the documentation for each of these software applications for
installation instructions. See link:install.html#GBFTP[Chapter 3,
"Installation,"] for instructions on installing the JCA TCK.
2.  Set up the JCA TCK software. +
See link:config.html#GBFVV[Chapter 4, "Setup and Configuration,"] for
details about the following steps.
1.  Set up your shell environment.
2.  Modify the required properties in the `<TS_HOME>/bin/ts.jte` file.
3.  Configure the JavaTest harness, if you are planning to run the TCK
tests through the JavaTest GUI.
3.  Test the JCA 1.7 implementation. +
Test the JCA implementation installation by running the test suite. See
link:using.html#GBFWO[Chapter 5, "Executing Tests."]


