DROP table INTEROP_CSIV2_TABLE1  !
CREATE table INTEROP_CSIV2_TABLE1 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE2  !
CREATE table INTEROP_CSIV2_TABLE2 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE3  !
CREATE table INTEROP_CSIV2_TABLE3 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE4  !
CREATE table INTEROP_CSIV2_TABLE4 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE5  !
CREATE table INTEROP_CSIV2_TABLE5 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE6  !
CREATE table INTEROP_CSIV2_TABLE6 (ID INTEGER PRIMARY KEY NOT NULL ,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE7  !
CREATE table INTEROP_CSIV2_TABLE7 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE52  !
CREATE table INTEROP_CSIV2_TABLE52 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE8  !
CREATE table INTEROP_CSIV2_TABLE8 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE53  !
CREATE table INTEROP_CSIV2_TABLE53 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE10  !
CREATE table INTEROP_CSIV2_TABLE10 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE11  !
CREATE table INTEROP_CSIV2_TABLE11 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE12  !
CREATE table INTEROP_CSIV2_TABLE12 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE13  !
CREATE table INTEROP_CSIV2_TABLE13 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE14  !
CREATE table INTEROP_CSIV2_TABLE14 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE15  !
CREATE table INTEROP_CSIV2_TABLE15 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE16  !
CREATE table INTEROP_CSIV2_TABLE16 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE17  !
CREATE table INTEROP_CSIV2_TABLE17 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE18  !
CREATE table INTEROP_CSIV2_TABLE18 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE19  !
CREATE table INTEROP_CSIV2_TABLE19 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE20  !
CREATE table INTEROP_CSIV2_TABLE20 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE21  !
CREATE table INTEROP_CSIV2_TABLE21 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE22  !
CREATE table INTEROP_CSIV2_TABLE22 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE23  !
CREATE table INTEROP_CSIV2_TABLE23 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE24  !
CREATE table INTEROP_CSIV2_TABLE24 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE25  !
CREATE table INTEROP_CSIV2_TABLE25 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE26  !
CREATE table INTEROP_CSIV2_TABLE26 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE27  !
CREATE table INTEROP_CSIV2_TABLE27 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE28  !
CREATE table INTEROP_CSIV2_TABLE28 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE29  !
CREATE table INTEROP_CSIV2_TABLE29 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE30  !
CREATE table INTEROP_CSIV2_TABLE30 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE31  !
CREATE table INTEROP_CSIV2_TABLE31 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE32  !
CREATE table INTEROP_CSIV2_TABLE32 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE33  !
CREATE table INTEROP_CSIV2_TABLE33 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE34  !
CREATE table INTEROP_CSIV2_TABLE34 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE35  !
CREATE table INTEROP_CSIV2_TABLE35 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE36  !
CREATE table INTEROP_CSIV2_TABLE36 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE37  !
CREATE table INTEROP_CSIV2_TABLE37 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE38  !
CREATE table INTEROP_CSIV2_TABLE38 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE39  !
CREATE table INTEROP_CSIV2_TABLE39 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE40  !
CREATE table INTEROP_CSIV2_TABLE40 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE41  !
CREATE table INTEROP_CSIV2_TABLE41 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25)) !

DROP table INTEROP_CSIV2_TABLE42  !
CREATE table INTEROP_CSIV2_TABLE42 (KEY_ID INTEGER PRIMARY KEY NOT NULL,BRAND_NAME  varchar(25),PRICE FLOAT) !

DROP table INTEROP_CSIV2_TABLE43  !
CREATE table INTEROP_CSIV2_TABLE43 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25),PRICE REAL) !

DROP table INTEROP_CSIV2_TABLE44  !
CREATE table INTEROP_CSIV2_TABLE44 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25),PRICE REAL) !

DROP table INTEROP_CSIV2_TABLE45  !
CREATE table INTEROP_CSIV2_TABLE45 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25),PRICE REAL) !

DROP table INTEROP_CSIV2_TABLE46  !
CREATE table INTEROP_CSIV2_TABLE46 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25),PRICE REAL) !

DROP table INTEROP_CSIV2_TABLE47  !
CREATE table INTEROP_CSIV2_TABLE47 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25),PRICE REAL) !

DROP table INTEROP_CSIV2_TABLE48  !
CREATE table INTEROP_CSIV2_TABLE48 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25),PRICE REAL) !

DROP table INTEROP_CSIV2_TABLE49  !
CREATE table INTEROP_CSIV2_TABLE49 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25),PRICE REAL) !

DROP table INTEROP_CSIV2_TABLE50  !
CREATE table INTEROP_CSIV2_TABLE50 (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25),PRICE REAL) !

DROP table INTEROP_COSNAMINGNOSSL_TABLE  !
CREATE table INTEROP_COSNAMINGNOSSL_TABLE (ID INTEGER PRIMARY KEY NOT NULL,NAME  varchar(25),PRICE float) !
