type=page
status=published
title=Installation
next=config.html
prev=rules.html
~~~~~~
Installation
============

[[TCJRS00004]][[GBFTP]]


[[installation]]
3 Installation
--------------

This chapter explains how to install the Java API for RESTful Web
Services TCK 2.1 (JAX-RS TCK) software.

After installing the software according to the instructions in this
chapter, proceed to link:config.html#GBFVV[Chapter 4, "Setup and
Configuration,"] for instructions on configuring your test environment.

[[GBFUD]][[TCJRS00047]][[obtaining-the-jax-rs-2.1-reference-implementation-jersey-2.26]]

3.1 Obtaining the JAX-RS 2.1 Reference Implementation (Jersey 2.26)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[GBFTS]][[TCJRS00048]][[installing-the-software]]

3.2 Installing the Software
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Before you can run the JAX-RS TCK tests, you must install and set up the
following software components:

* Java EE 8 RI or, at a minimum, a Web server with a Servlet container
* Java SE 8
* JAX-RS 2.1 RI, which is Jersey 2.26
* JAX-RS TCK version 2.1, which includes:

** JDOM 1.0

** Apache Commons HTTP Client 3.1

** Apache Ant 1.8.4

** Apache Commons Logging 1.1.1

** Apache Commons Codec 1.3
* The JAX-RS 2.1 Vendor Implementation (VI)

1.  Install the Java SE 8 software, if it is not already installed. +
Download and install the Java SE 8 software from
`http://www.oracle.com/technetwork/java/javase/downloads/index.html`.
Refer to the installation instructions that accompany the software for
additional information.
2.  Install the JAX-RS TCK 2.1 software.
1.  Copy or download the JAX-RS TCK software to your local system. 
2.  Use the `unzip` command to extract the bundle in the directory of
your choice: +
[source,oac_no_warn]
----
unzip jaxrstck-2.1_<date>.zip
----
This creates the `jaxrstck` directory. The
install_directory`/``jaxrstck` directory is the test suite home,
`<TS_HOME>`.
3.  Install the Java EE 8 RI software (the servlet Web container used
for running the JAX-RS TCK with the JAX-RS 2.1 RI), if it is not already
installed. +
Download and install the Servlet Web container with the JAX-RS 2.1 RI
used for running the JAX-RS TCK 2.1, represented by the Java EE 8 RI.
This software can be obtained from the Java Licensee Engineering Web
site. Refer to any installation instructions that accompany the software
for additional information.
4.  Install the JAX-RS 2.1 Reference Implementation. +
The Reference Implementation is used to validate your initial
configuration and setup of the JAX-RS TCK 2.1 tests, which are explained
further in link:config.html#GBFVV[Chapter 4, "Setup and Configuration."]
5.  Install a Web server on which the JAX-RS TCK test applications can
be published for testing the VI.
6.  Install the JAX-RS Vendor Implementation (VI) to be tested. +
Follow the installation instructions for the particular VI under test.


