type=page
status=published
title=Preface
next=intro.html
prev=title.html
~~~~~~
Preface
=======

[[TCJRS00001]][[GBFTI]]


[[preface]]
Preface
-------

[NOTE]
========================================================================

The Technology Compatability Kit (TCK) documentation is part of the Java Enterprise 
Edition contribution to the Eclipse Foundation and is not intended for 
use in relation to Java Enterprise Edition or Java Licensee 
requirements. The documentation is in the process of being revised to 
reflect the new Jakarta EE branding. 
Additional changes will be made as requirements and procedures evolve 
for Jakarta EE. Where applicable, references to Java EE or Java 
Enterprise Edition should be considered references to Jakarta EE. 

Please see the Title page for additional license information.
========================================================================

This guide describes how to install, configure, and run the Technology
Compatibility Kit (TCK) that is used to test the Java API for RESTful
Web Services (JAX-RS 2.1) (JSR 370) technology.

The JAX-RS TCK is a portable, configurable automated test suite for
verifying the compatibility of a licensee's implementation of the JAX-RS
2.1 Specification (hereafter referred to as the licensee
implementation). The JAX-RS TCK uses the JavaTest harness version 4.4.1
to run the test suite


[NOTE]
=======================================================================

Note All references to specific Web URLs are given for the sake of your
convenience in locating the resources quickly. These references are
always subject to changes that are in many cases beyond the control of
the authors of this guide.

=======================================================================

[[TCJRS00034]][[GBFUS]]


[[who-should-use-this-book]]
Who Should Use This Book
~~~~~~~~~~~~~~~~~~~~~~~~

This guide is for developers of the JAX-RS 2.1 technology to assist them
in running the test suite that verifies compatibility of their
implementation of the JAX-RS 2.1 Specification.

[[TCJRS00035]][[GBFPO]]


[[before-you-read-this-book]]
Before You Read This Book
~~~~~~~~~~~~~~~~~~~~~~~~~

You should be familiar with the JAX-RS 2.1 Specification, which can be
found at `http://jcp.org/en/jsr/detail?id=370`.

Before running the tests in the JAX-RS TCK, you should familiarize
yourself with the JavaTest documentation that is included in the JAX-RS
TCK documentation bundle.

[[TCJRS00036]][[GBFWF]]


[[typographic-conventions]]
Typographic Conventions
~~~~~~~~~~~~~~~~~~~~~~~

The following table describes the typographic conventions that are used
in this book.

[width="100%",cols="15%,40%,45%",options="header",]
|=======================================================================
|Convention |Meaning |Example
|Boldface |Boldface type indicates graphical user interface elements
associated with an action, terms defined in text, or what you type,
contrasted with onscreen computer output. a|
From the File menu, select Open Project.

A cache is a copy that is stored locally.

[source,oac_no_warn]
----
machine_name% su
Password:
----

|`Monospace` |Monospace type indicates the names of files and
directories, commands within a paragraph, URLs, code in examples, text
that appears on the screen, or text that you enter. a|
Edit your `.login` file.

Use `ls` `-a` to list all files.

`machine_name% you have mail.`

|Italic |Italic type indicates book titles, emphasis, or placeholder
variables for which you supply particular values. a|
Read Chapter 6 in the User's Guide.

Do not save the file.

The command to remove a file is `rm` filename.

|=======================================================================


[[TCJRS00037]][[FWBSD]]


[[shell-prompts-in-command-examples]]
Shell Prompts in Command Examples
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The following table shows the default UNIX system prompt and superuser
prompt for the C shell, Bourne shell, and Korn shell.

[width="100%",cols="50%,50%",options="header",]
|=====================================================
|Shell |Prompt
|C shell |`machine_name%`
|C shell for superuser |`machine_name#`
|Bourne shell and Korn shell |`$` +
|Bourne shell and Korn shell for superuser |`#` +
|Bash shell |`shell_name-shell_version$`
|Bash shell for superuser |`shell_name-shell_version#`
|=====================================================



