= Jakarta EE TCK Distribution

This distribution contains the Jakarta EE TCK ${project.version}

* LICENSE.adoc - Eclipse Foundation Technology Compatibility Kit License
* artifacts - the TCK test artifacts
* bin - The root configuration and script directory
* guides - The user guides for the Platform TCK and bundled TCKs.
* javadoc - The javadoc for the TCK porting APIs and common code
* sql - The SQL scripts for setting up various databases for the TCK
* src - the source for the TCK tests

== Getting Started
Open the guides/Jakarta-Platform-TCK-Users-Guide.pdf and follow the instructions to get started.

== Sample Runners
You can find sample maven test runners in the platform-tck repository at:
https://github.com/jakartaee/platform-tck/tree/main/glassfish-runner

Each runner targets a specific platform TCK test artifact.

== Release Note Highlights

The Jakarta EE TCK release has been ported to use Arquillian and Junit 5 as the test framework. The technology test artifacts have been split up into individual test artifacts that can be access from Maven Central. Details for the various release are highlighted below.

=== 11.0.0-M5
* The distribution includes an artifacts/artifacts-bom-11.0.0-*.pom bom type file that can be used to import the TCK artifacts into your project.
* The distribution includes an artifacts/artifacts-sums.txt that provides the SHA1 and MD5 checksums for the TCK artifacts as they exist in the staging repository or Maven Central. This can be used to double check the integrity of the artifacts.

