= Jakarta EE TCK Distribution

This distribution contains the Jakarta EE TCK ${project.version}

* LICENSE.adoc - Eclipse Foundation Technology Compatibility Kit License
* artifacts - the TCK test artifacts
* bin - The root configuration and script directory
* guides - The user guides for the Platform TCK and bundled TCKs.
* javadoc - The javadoc for the TCK porting APIs and common code
* sql - The SQL scripts for setting up various databases for the TCK
* src - the source for the TCK tests

== Getting Started
Open the guides/Jakarta-Platform-TCK-Users-Guide.pdf and follow the instructions to get started.

== Sample Runners
You can find sample maven test runners in the platform-tck repository at:
https://github.com/jakartaee/platform-tck/tree/main/glassfish-runner

Each runner targets a specific platform TCK test artifact.

== Release Note Highlights

The Jakarta EE TCK release has been ported to use Arquillian and Junit 5 as the test framework. The technology test artifacts have been split up into individual test artifacts that can be access from Maven Central. Details for the various release are highlighted below.

=== 11.0.3
* Address https://github.com/jakartaee/platform-tck/issues/2614
* Address https://github.com/jakartaee/persistence/issues/982

=== 11.0.2
* Update jakarta.tck.arquillian.* to 11.1.2
* Upgrade the parent POM from 2.0.0-M1 to 2.0.0.
* Switch to use jakarta.tck:common:11.1.1-M2
* Allow the Chrome driver to be overridden with a system property
* Update sun-web.xml files to have the new context roots
* Fix non-portable context root in web scope and standalone ClientTest
* Fix non-portable context root in ClientTest
* Address Platform TCK challenge for ee.jakarta.tck.persistence.core.annotations.mapkeyenumerated.ClientPmservletTest.elementCollectionTest
* use jakarta.tck:common:11.1.1-M2
* Address Platform TCK challenge for lockTransactionRequiredException tests in ee.jakarta.tck.persistence.core.entityManager2
* [jakartaee/persistence#714] TCK should not try declare generator with same name multiple times
* Correct conditions checked for in WebVehicleRunner when producing test failure message
* TCK Challenge: com.sun.ts.tests.assembly.classpath tests are invalid -- no longer testing intended function
* Address TCK challenge 2497 by excluding ee.jakarta.tck.persistence.core.metamodelapi.identifiabletype.Client*#getDeclaredSingularAttributes()
* Cancel async work in NPE test scenarios
* Reapply "https://github.com/jakartaee/platform-tck/issues/2523 exclude jakarta.tck:smoke-tests from being deployed to sonatype"
* Convert EJB vehicle test from proxy to standard
* Fixes for ejb30 bb.session porting errors (1)
* Fix Assembly app construction issues
* Allow bindings to be added to appclient jars
* Fix EJB wrappers for AppClient Tests
* Add Missing Class to persistence.ee.packaging.ejb.resource_local war module
* Remove @Transactional from Persistence Vehicles
* Remove fragile debug code from ejb30.assembly.initorder.appclientejb.Client
* Move Authentication (jaspic) from KEYWORD_WEB_FULL_OPTIONAL_TECHS to KEYWORD_WEB as Authentication is required for Web Profile
* TCK Challenge: EJB Vehicle tests aren't running in EJBs #2411
* Fix for ejb30.misc.moduleName.twowars
* Fixes for JDBC Challenge - 2414
* Fixes for ejb30 bb.session porting errors
* [2372] Use the correct NamingEnumeration in the loop when printing the java:app namespace. 

_1) `com.sun.ts.tests.ejb30.bb.session.stateless.annotation.enventry.Client` changed bean name from "ejb/EnvEntrySetterBean" to "EnvEntrySetterBean" (and similar for two other beans). A vendor specific (GlassFish) deployment descriptor which is provided for convenience and not part of the TCK requirements was not updated for this name change. Vendors using this deployment descriptor have to compensate, e.g. by using an `ArchiveProcessor` to remove the old descriptor and add an updated descriptor file._

=== 11.0.0
* Add web/platform tags to WebSocket and CDI/Persistence tests
* Document additional runner requirements for ee.jakarta.tck.persistence.ee.cdi package tests
* Add WebSocket TCK to Intro section of Platform/Web Profile TCK
* Update the jakarta.jakartaee-bom.version to the staged 11.0.0
* Update to jakarta.tck:common:11.0.0
* Update to jakarta.tck:signaturetest:11.0.0
* Update jakarta.tck.arquillian.* to 11.0.0
* User guide updates

=== 11.0.0-RC1
* Bump arquillian.version from 1.9.2.Final to 1.9.3.Final
* Bump org.jboss.weld.se:weld-se-core from 5.0.0.SP2 to 6.0.1.Final
* Bump jakarta.tck:sigtest-maven-plugin from 2.2 to 2.6
* Update to jakarta.tck:signaturetest:11.0.0-RC8
* Use the jakarta bom for api versions
* Remove technologies from Platform TCK user guide that were removed for EE 11
* Remove XML Binding technology from Platform TCK user guide
* Update to jakarta.tck:common:11.0.0-RC7
* Update jakarta.tck.arquillian.* to 11.0.0-RC3


=== 11.0.0-M11
* Update the jakarta.jakartaee-bom.version to 11.0.0-RC1 to fix transitive dependency issues
* Increase 1-second Calendar Timers
* Cleanup versions by introducing consistent version properties
* Use the jakarta bom for api versions in jakarta.tck:common
* Add jakarta.tck:signaturevalidation artifact to release and bom
* Userguide updates
* Bump jakarta.tck.arquillian.version from 11.0.0-M1 to 11.0.0-RC1
* Update the TCK Troubleshooting documentation
* Add a section on generating a client cert to user guide
* Fix resource inclusion in TCK jars
* Remove SQL DDL files that have become unused
* Update the default value of the porting.ts.url.class.1 property
* Remove the old template source files as they have been reified


=== 11.0.0-M7
* Various test fixes
* Restructure user guide locations
* Update jakarta.tck:common to 11.0.0-RC5
* Make the jakarta.tck:artifacts-bom a proper release artifact

=== 11.0.0-M6
* Add a VerifyHashes.java program to validate the MD5 hashes of the artifacts in the distribution.
* Changed the jakarta.tck:websocket-tck-platform-tests version to 11.0.0-x


=== 11.0.0-M5
* The distribution includes an artifacts/artifacts-bom-11.0.0-*.pom bom type file that can be used to import the TCK artifacts into your project.
* The distribution includes an artifacts/artifacts-sums.txt that provides the SHA1 and MD5 checksums for the TCK artifacts as they exist in the staging repository or Maven Central. This can be used to double check the integrity of the artifacts.

== Excluded Tests

The following tests are annotated as disabled due to exclusions:

include::EXCLUDES.adoc[]
