type=page
status=published
title=Setup and Configuration
next=using.html
prev=install.html
~~~~~~
include::attributes.conf[]
Setup and Configuration
=======================

[[GBFVV]]


[[setup-and-configuration]]
4 Setup and Configuration
-------------------------

This chapter describes how to set up the {TechnologyShortName} TCK and
JavaTest harness software. Before proceeding with the instructions in
this chapter, be sure to install all required software, as described in
link:install.html#GBFTP[Chapter 3, "Installation."]

After completing the instructions in this chapter, proceed to
link:using.html#GBFWO[Chapter 5, "Executing Tests,"] for instructions on
running the {TechnologyShortName} TCK.

This chapter includes the following topics:

* link:#GBFVU[Modifying the ts_env and ts_env.bat Files]
* link:#GCLHU[Modifying the ts.jte File]
* link:#GBFWG[Using the JavaTest Harness Configuration GUI]
* link:#GBFUY[Special Set-Up Instructions]

include::config.inc[]

[[GBFWG]][[using-the-javatest-harness-configuration-gui]]

4.3 Using the JavaTest Harness Configuration GUI
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

You can use the JavaTest harness GUI to modify general test settings and
to quickly get started with the default {TechnologyShortName} TCK test
environment.  This section covers the following topics:

* link:#GBFVA[Configuration GUI Overview]
* link:#GBFVD[Starting the Configuration GUI]
* link:#GBFVX[To Configure the JavaTest Harness to Run the
{TechnologyShortName} TCK Tests]
* link:#GBFUU[Modifying the Default Test Configuration]
* link:#GCLJG[The Configuration Interview]


[NOTE]
=======================================================================

It is only necessary to proceed with this section if you want to run the
JavaTest harness in GUI mode. If you plan to run the JavaTest harness in
command-line mode, skip the remainder of this chapter, and continue with
link:using.html#GBFWO[Chapter 5, "Executing Tests."]

=======================================================================


[[GBFVA]][[configuration-gui-overview]]

4.3.1 Configuration GUI Overview
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In order for the JavaTest harness to execute the test suite, it requires
information about how your computing environment is configured. The
JavaTest harness requires two types of configuration information:

* Test environment: This is data used by the tests. For example, the
path to the Java runtime, how to start the product being tested, network
resources, and other information required by the tests in order to run.
This information does not change frequently and usually stays constant
from test run to test run.
* Test parameters: This is information used by the JavaTest harness to
run the tests. Test parameters are values used by the JavaTest harness
that determine which tests in the test suite are run, how the tests
should be run, and where the test reports are stored. This information
often changes from test run to test run.

The first time you run the JavaTest harness software, you are asked to
specify the test suite and work directory that you want to use. (These
parameters can be changed later from within the JavaTest harness GUI.)

Once the JavaTest harness GUI is displayed, whenever you choose Start,
then Run Tests to begin a test run, the JavaTest harness determines
whether all of the required configuration information has been supplied:

* If the test environment and parameters have been completely
configured, the test run starts immediately.
* If any required configuration information is missing, the
configuration editor displays a series of questions asking you the
necessary information. This is called the configuration interview. When
you have entered the configuration data, you are asked if you wish to
proceed with running the test.

[[GBFVD]][[starting-the-configuration-gui]]

4.3.2 Starting the Configuration GUI
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Before you start the JavaTest harness software, you must have a valid
test suite and Java SE {SEversion} installed on your system.

The {TechnologyShortName} TCK includes an Ant script that is used to execute the
JavaTest harness from the `<TS_HOME>` directory. Using this Ant script
to start the JavaTest harness is part of the procedure described in
link:#GBFVX[Section 4.5.3, "To Configure the JavaTest Harness to Run the
TCK Tests."]

When you execute the JavaTest harness software for the first time, the
JavaTest harness displays a Welcome dialog box that guides you through
the initial startup configuration.

* If it is able to open a test suite, the JavaTest harness displays a
Welcome to JavaTest dialog box that guides you through the process of
either opening an existing work directory or creating a new work
directory as described in the JavaTest online help.
* If the JavaTest harness is unable to open a test suite, it displays a
Welcome to JavaTest dialog box that guides you through the process of
opening both a test suite and a work directory as described in the
JavaTest documentation.

After you specify a work directory, you can use the Test Manager to
configure and run tests as described in link:#GBFVX[Section 4.5.3, "To
Configure the JavaTest Harness to Run the TCK Tests."]

[[GBFVX]][[to-configure-the-javatest-harness-to-run-the-tck-tests]]

4.3.3 To Configure the JavaTest Harness to Run the TCK Tests
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The answers you give to some of the configuration interview questions
are specific to your site. For example, the name of the host on which
the JavaTest harness is running. Other configuration parameters can be
set however you wish. For example, where you want test report files to
be stored.

Note that you only need to complete all these steps the first time you
start the JavaTest test harness. After you complete these steps, you can
either run all of the tests by completing the steps in
link:using.html#GBFUZ[Section 5.1, "Starting JavaTest,"] or run a subset
of the tests by completing the steps in link:using.html#GBFWM[Section
5.2, "Running a Subset of the Tests."]

1.  Change to the `<TS_HOME>/bin` directory and start the JavaTest test
harness: +
`cd <TS_HOME>/bin` +
`ant gui`
2.  From the File menu, click Open Quick Start Wizard. +
The Welcome screen displays.
3.  Select Start a new test run, and then click Next. +
You are prompted to create a new configuration or use a configuration
template.
4.  Select Create a new configuration, and then click Next. +
You are prompted to select a test suite.
5.  Accept the default suite (`<TS_HOME>/src`), and then click Next. +
You are prompted to specify a work directory to use to store your test
results.
6.  Type a work directory name or use the Browse button to select a work
directory, and then click Next. +
You are prompted to start the configuration editor or start a test run.
At this point, the {TechnologyShortName} TCK is configured to run the
default test suite.
7.  Deselect the Start the configuration editor option, and then click
Finish.
8.  Click Run Tests, then click Start. +
The JavaTest harness starts running the tests.
9.  To reconfigure the JavaTest test harness, do one of the following:
* Click Configuration, then click New Configuration.
* Click Configuration, then click Change Configuration.
10. Click Report, and then click Create Report.
11. Specify the directory in which the JavaTest test harness will write
the report, and then click OK. +
A report is created, and you are asked whether you want to view it.
12. Click Yes to view the report.

[[GBFUU]][[modifying-the-default-test-configuration]]

4.3.4 Modifying the Default Test Configuration
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The JavaTest GUI enables you to configure numerous test options. These
options are divided into two general dialog box groups:

* Group 1: Available from the JavaTest Configure/Change Configuration
submenus, the following options are displayed in a tabbed dialog box:

** Tests to Run

** Exclude List

** Keywords

** Prior Status

** Test Environment

** Concurrency

** Timeout Factor
* Group 2: Available from the JavaTest Configure/Change
Configuration/Other Values submenu, or by pressing Ctrl+E, the following
options are displayed in a paged dialog box:

** Environment Files

** Test Environment

** Specify Tests to Run

** Specify an Exclude List

Note that there is some overlap between the functions in these two
dialog boxes; for those functions use the dialog box that is most
convenient for you. Please refer to the JavaTest Harness documentation
or the online help for complete information about these various options.

[[GCLJG]][[configuration-interview]]

4.3.5 Configuration Interview
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The answers you give to some of the configuration interview questions are specific to your
site. For example, the name of the host on which the JavaTest harness is running. Other
configuration parameters can be set however you wish. For example, where you want test
report files to be stored.

To configure the JavaTest harness to run the JAXR TCK tests, complete the following steps.
Note that you only need to complete these steps the first time you start the JavaTest test
harness. After you complete these steps, you can either run all of the tests by completing the
steps in Section 5.2 “Using the JAXR TCK to Test a Product” or run a subset of the tests by
completing the steps in Section 5.2.1 “Running a Subset of the Tests.”

1.  Change to the <TS_HOME>/bin directory and start the JavaTest test harness:
----
cd <TS_HOME>/bin
ts
----

2.  The Welcome screen displays. From the *File* menu, select *Open Test Suite*. Within the
file dialog, traverse the following directories: *com --> sun --> ts*. Highlight tests and
click *Open*.

3.  From the *File* menu, select *New Work Dir*, enter the name of the directory to which the
JavaTest test harness will write temporary files (/tmp/JTwork, for example), and press
the *New Work Dir* button when you are done.
Otherwise, From the *File* menu, select *Open Work Dir* to open an existing work
directory.

4.  Pull down *Configuration* and select *Configuration Editor*. The Welcome screen
displays. Press the *Next Question* button (right arrow). You are prompted to select which
tests to run. Accept the default setting (jaxr) and press the *Next Question* button.

[NOTE]
====================================================================================
Do not run the Parameter Editor before you run the Configuration Editor or you will
lose all the default settings.
====================================================================================

5.  You are asked if you want to specify an exclude list. Accept the default (yes) and press
the *Next Question* button.

6.  Verify the default location of the exclude list and press the *Next Question* button.

7.  You are prompted for the location of the environment files. Accept the default file
location and press the *Next Question* button.

8.  You are prompted to specify a test environment. Select either `ts_unix` or `ts_win32`
and press the *Next Question* button.

9.  You are prompted to specify a directory into which reports will be written. Accept the
default (/tmp/JTreport) or enter a new directory location and press the *Next
Question* button.

10. You are prompted to create the directory. Accept the default answer (yes) and press the
*Next Question* button.

11. The Congratulations screen displays. Press the *Finished* button (check mark).


[[GBFUY]][[special-set-up-instructions]]

4.4 Special Set-Up Instructions
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Starting Your Registry
^^^^^^^^^^^^^^^^^^^^^^

If you are using the UDDI registry that comes with the Java Web Services Developer
Pack, complete the following steps:

1.  Run the Tomcat startup script.
2.  Run the Xindice startup script.

  [NOTE]
  ===========================================================================================
  If you are using the IBM, HP, or Microsoft UDDI registry, you need not complete these steps.
  ============================================================================================
