.  Install or get access to a UDDI V2-compliant registry. +
To use a UDDI V2 registry from IBM or Microsoft, you need to go to
their sites and register.  When you register, you will get your own
username and password. +
To get a username to use with the IBM registry, go to
http://www.ibm.com/ services/uddi and click on the beta v2 register
button. Scroll down and you will see a place to get a username and
password. +
To get a username for the Microsoft UDDI registry, go to http://
uddi.rte.microsoft.com and click register. You need to use Internet
Explorer V5.0 or higher as your browser for this procedure. +
When you modify the ts.jte file, as described in Section 4.2, you need
to specify the publish and query urls for the registry that you will be
using.
