.  Install the UDDI registry that comes with the Web Services Developer
Pack, download the Web Services Developer Pack software from the Java
Software web site and install. This installs the UDDI V2 registry. The
username and password for the default account are “testuser” and
“testuser.” See the installation instructions that accompany the
software for JAXR 1.0 Technology Compatibility Kit User’s Guide •
June 2002 additional information about installing the software. You
will also need to create a second account. See the “Adding New Users
to the Registry” section in the Java Web Services Tutorial for
information about creating this account.
