* Install a UDDI registry server. You may install the UDDI registry that comes with the Web Services Developer
Pack, download the Web Services Developer Pack software from the Java
Software web site and install https://www.oracle.com/technetwork/java/webservicespack-jsp-140788.html[Web Services Downloads]. 
This installs the UDDI V2 registry. The
username and password for the default account are “testuser” and
“testuser.” See the installation instructions that accompany the
software in this guide.

* You will also need to create a second account. See the “Adding New Users
to the Registry” section in the Java Web Services Tutorial (see the link above) for
information about creating this account.
