type=page
status=published
title=Setup and Configuration
next=using.html
prev=install.html
~~~~~~
Setup and Configuration
=======================

[[TCJSP00005]][[GBFVV]]


[[setup-and-configuration]]
4 Setup and Configuration
-------------------------

This chapter describes how to set up the JavaServer Pages TCK and
JavaTest harness software. Before proceeding with the instructions in
this chapter, be sure to install all required software, as described in
link:install.html#GBFTP[Chapter 3, "Installation."]

After completing the instructions in this chapter, proceed to
link:using.html#GBFWO[Chapter 5, "Executing Tests,"] for instructions on
running the JavaServer Pages TCK.

This chapter includes the following topics:

* link:#GBFVU[Configuring Your Environment to Run the JSP TCK]
* link:#GCFQK[Preparing the WAR Files for Deployment]
* link:#GCRVD[Custom Deployment Handlers]
* link:#GCRWX[Deploying the JSP TCK Tests]

[[GBFVU]][[TCJSP00042]][[configuring-your-environment-to-run-the-jsp-tck]]

4.1 Configuring Your Environment to Run the JSP TCK
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This section describes how to configure the JSP TCK for your
environment. After configuring your environment, continue with the
instructions in link:using.html#GBFWO[Chapter 5, "Executing Tests."]


[NOTE]
=======================================================================

In these instructions, variables in angle brackets need to be expanded
for each platform. For example, `<TS_HOME>` becomes `$TS_HOME` on
Solaris/Linux and `%TS_HOME%` on Windows. In addition, the forward
slashes (`/`) used in all of the examples need to be replaced with
backslashes (`\`) for Windows. Finally, be sure to use the appropriate
separator for your operating system when specifying multiple path
entries (`;` on Windows, `:` on Solaris/Linux).

=======================================================================


1.  Set the following environment variables in your shell environment:
1.  `JAVA_HOME` to the directory in which Java SE 7 is installed
2.  `JAVAEE_HOME` to the installation directory of the Web server to
which the JSP TCK 2.3 tests are to be deployed. +
For example, to deploy the JSP TCK tests to theJava EE 7 RI, you would
set this variable to the directory in which the Java EE 7 RI was
installed.
3.  `TS_HOME` to the directory in which the JSP TCK 2.3 software is
installed
4.  `PATH` to include the `<TS_HOME>/bin` , `<JAVA_HOME>/bin`, and
`<TS_HOME>/tools/ant/bin` directories
5.  Unset set `ANT_HOME` in your environment, if it is set.
2.  Edit your `<TS_HOME>/bin/ts.jte` file and set the following
properties:
1.  `webServerHost` to the name of the host of the target web container.
2.  `webServerPort` to the port number to which the container is bound.
3.  `webServerHome` to the installation directory of the container.
4.  `web.deployment.handler` to an Ant file that contains at least a
single target named `deploy`. +
When `ant deploy` is invoked, this target will be invoked to handle the
deployment of the web applications to the target server. To use a custom
handler, copy the handler to the `<TS_HOME>/bin/deploy` directory and
provide only the filename as the property value. +
The JSP TCK includes the following handlers:
* `noop`: No deployment; default setting
* `glassfish`: Deploy to the Java EE 7 server
* `jwsdp`: Deploy to a server running the Java Web Services Developers
Pack or to a Tomcat server +
See link:#GCRVD[Section 4.3, "Custom Deployment Handlers,"] for
information about creating your own deployment handler and setting the
`web.deployment.handler` property to use that handler.
5.  `jspservlet.classes` to the path to the Servlet and JSP API classes
that are used for building. +
The `ts.jte` file includes examples that show how to set the classes
properties for GlassFish 4 servers.
6.  `jstl.classes` to the path to the JavaServer Pages Standard Tag
Library (JSTL) JAR files.
7.  `report.dir` to the default directory in which JavaTest creates a
test report for the most recent test run. +
This property is a required property for the TCK Ant targets; it must be
set. To disable reporting, set the `report.dir` property to `"none"`.
8.  `work.dir` to the default directory in which JavaTest writes
temporary files that are created during test execution. +
This property is required for the TCK Ant targets.
9.  When the signature tests are run, the `sigTestClasspath` property
must be set to a list of JAR files and directories which contain the
Java EE and Java SE classes. +
Paths must be separated by the appropriate path separator ("`;`" on
Windows, "`:`" on Solaris/Linux).
10. `porting.ts.url.class.1` to the class names of your porting class
implementations. +
By default, the property settings point to the JSP TCK RI-specific
classes.
3.  Provide your own implementation of the porting package interface
provided with the JSP TCK. +
The porting package interface, `TSURLInterface.java`, obtains URL
strings for web resources in an implementation-specific manner. API
documentation for the `TSURLInterface.java` porting package interface is
available in the JSP TCK documentation bundle.

[[GCFQK]][[TCJSP00043]][[preparing-the-war-files-for-deployment]]

4.2 Preparing the WAR Files for Deployment
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Complete this step only if you intend to package a JSP implementation in
the WAR files, thereby overriding the default JSP implementation for the
application server under test. This procedure adds to and rebuilds the
JSP TCK WAR files.

1.  Copy one or more of the JAR files required by the JSP implementation
that will replace the application server's default JSP implementation to
the `<TS_HOME>/weblib` directory. +
This JAR file (or files) must contain all of the TLDs (located in the
`META-INF` directory of the archive) for the tag libraries, as defined
by the JSP specification and any additional support JAR files upon which
the JSP implementation is dependent.
2.  Change to the `<TS_HOME>/src/com/sun/ts/tests` directory and run
`ant build` to package the web archives. +
This adds one or more JAR files from the `<TS_HOME>/weblib` directory to
each of the WAR files.

[[GCRVD]][[TCJSP00044]][[custom-deployment-handlers]]

4.3 Custom Deployment Handlers
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Deployment handlers are used to deploy and undeploy the WAR files that
contain the tests to be run during the certification process. A
deployment handler is an Ant build file that contains at least the
required targets listed in link:#BABFAHFE[Table 4-1].

[[sthref8]][[BABFAHFE]]

Table 4-1 Required Deployment Handler Targets

[width="100%",cols="26%,74%",options="header",]
|=======================================================================
|Required Ant Task |Description
|`-deploy` |Deploys an archive or any archive from the current working
directory and its children directories.

|`-undeploy` |Undeploys a deployed archive or any deployed archive from
the current working directory and its children directories.

|`-deploy.all` |Deploys all archives.

|`-undeploy.all` |Undeploys all deployed archives.
|=======================================================================


The JavaServer Pages TCK provides three deployment handlers:

* `<TS_HOME>/bin/xml/impl/none/deploy.xml`
* `<TS_HOME>/bin/xml/impl/glassfish/deploy.xml`
* `<TS_HOME>/bin/xml/impl/tomcat/deploy.xml`

The `deploy.xml` files in each of these directories are used to control
deployment to a specific container (no deployment, deployment to the
GlassFish Web container, deployment to the Tomcat Web container) denoted
by the name of the directory in which each `deploy.xml` file resides.
The primary `build.xml` file in the `<TS_HOME>/bin` directory has a
target to invoke any of the required targets (`-deploy`, `-undeploy`,
`-deploy.all`, `-undeploy.all`).

[[GJCEK]][[TCJSP00070]][[to-create-a-custom-deployment-handler]]

4.3.1 To Create a Custom Deployment Handler
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To deploy tests to another JSP 2.3 implementation, you must create a
custom handler.

1.  [[BABDFGGI]] +
Create a new directory in the `<TS_HOME>/bin/impl` directory tree. +
For example, create the `<TS_HOME>/bin/impl/`my_deployment_handler
directory.
2.  Copy the `deploy.xml` file from the `<TS_HOME>/bin/xml/impl/none`
directory to the directory that you created.
3.  Modify the required targets in the `deploy.xml` file. +
This is what the `deploy.xml` file for the "none" deployment handler
looks like. +
[source,oac_no_warn]
----
<project name="No-op Deployment" default="deploy">

  <!-- No-op deployment target -->
  <target name="-deploy">
      <echo message="No deploy target implemented for this deliverable"/>
  </target>

  <target name="-undeploy">
      <echo message="No undeploy target implemented for this deliverable"/>
  </target>

  <target name="-deploy.all">
      <echo message="No deploy target implemented for this deliverable"/>
  </target>

  <target name="-undeploy.all">
      <echo message="No undeploy target implemented for this deliverable"/>
  </target>

</project>
----
Although this example just echoes messages, it does include the four
required Ant targets (`-deploy`,`-undeploy`, `-deploy.all`,
`-undeploy.all`) that your custom `deploy.xml` file must contain. With
this as your starting point, look at the required targets in the
`deploy.xml` files in the `tomcat` and `glassfish` directories for
guidance as you create the same targets for the Web container in which
you will run your implementation of JavaServer Pages 2.3.
4.  Set the `impl.vi.deploy.dir` property in the `ts.jte` file to the
name of the directory, my_deployment_handler, that you created in step
link:#BABDFGGI[1]. +
The required Ant targets in your `deploy.xml` file can be called from
anywhere in the `<TS_HOME>/src` directory. The `-deploy.all` and
`-undeploy.all` targets can also be called from the `<TS_HOME>/bin`
directory.

[[GCRWX]][[TCJSP00045]][[deploying-the-jsp-tck-tests]]

4.4 Deploying the JSP TCK Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

To deploy the JSP TCK tests to the Java EE 7 platform, perform the
following steps.

1.  Make sure that the Web server to which you will deploy the JSP TCK
tests is running.
2.  Change to the `<TS_HOME>/bin` directory.
3.  Execute the `ant deploy.all` command. +
All of the WAR files containing the JSP TCK tests have been deployed.
Follow the instructions in link:using.html#GBFUZ[Section 5.1, "Using the
GUI for TCK Test Execution,"] or link:using.html#GJCIW[Section 5.2,
"Using the Command-Line for TCK Test Execution,"] to run the tests you
just deployed.


