///////////////////////////////////////////////////////////////////////
NOTE TO WRITERS:
Steps to install the Java EE Reference Implementation.
For standalone technologies, no server may be required, and the
below lines can be removed.

This is used in install.adoc in section 3.2.
///////////////////////////////////////////////////////////////////////

.  Install the Jakarta EE 9 Compatible Platform software (the servlet Web container used
for running the {TechnologyShortName} TCK with the
{TechnologyShortName} {TechnologyVersion} Compatible Implementation), if it is not already
installed. +
Download and install the Servlet Web container with the
{TechnologyShortName} {TechnologyVersion} Compatible Implementation used for running the
{TechnologyShortName} TCK {TechnologyVersion}, represented by the Jakarta EE 9 Compatible Platform.
This software can be obtained from the link:{TechnologyRIURL}[Eclipse GlassFish 6] web page. Refer to any installation instructions that accompany the software
for additional information.
