///////////////////////////////////////////////////////////////////////
NOTE TO WRITERS:
Include the following text if this technology uses the rebuild.adoc
appendix.
///////////////////////////////////////////////////////////////////////

As explained in link:rebuild.html#GCLIZ[Appendix B, "Packaging the
Test Applications in Servlet-Compliant WAR
Files With VI-Specific Information,"] the {TechnologyShortName} TCK
introduces the concept of repackaging the TCK tests.
