type=page
status=published
title=Debugging Test Problems
next=faq.html
prev=using.html
~~~~~~
Debugging Test Problems
=======================

[[TCJSE00007]][[GBFUV]]


[[debugging-test-problems]]
6 Debugging Test Problems
-------------------------

There are a number of reasons that tests can fail to execute properly.
This chapter provides some approaches to help you deal with these
failures.


[NOTE]
=======================================================================

The instructions assume that you have installed and configured your test
environment as described in link:install.html#GBFTP[Chapter 3,
"Installation"] and link:config.html#GBFVV[Chapter 4, "Setup and
Configuration,"] respectively.

=======================================================================


[[GBFYP]][[TCJSE00047]][[overview]]

6.1 Overview
~~~~~~~~~~~~

The goal of a test run is for all tests, which are not filtered out, to
pass. If a test run includes tests with errors or failing results, you
must troubleshoot and correct the cause to satisfactorily complete the
test run.

* Errors: Tests with errors could not be executed. These errors usually
occur because the test environment is not properly configured.
* Failures: Tests that fail were executed but had failing results.

The Test Manager GUI provides you with a number of tools for effectively
troubleshooting a test run. See the JavaTest User's Guide and JavaTest
online help for detailed descriptions of the GUI tools described in this
chapter. Ant test execution tasks provide command-line users with
immediate test execution feedback to the display. Available JTR report
files and log files can also help command-line users troubleshoot test
run problems.

For every test run, the JavaTest harness creates a set of report files
in the reports directory, which you specified by setting the
`report.dir` property in the `ts.jte` file. The report files contain
information about the test description, environment, messages,
properties used by the test, status of the test, and test result. After
a test run is completed, the JavaTest harness writes HTML reports for
the test run. You can view these files in the JavaTest ReportBrowser
when running in GUI mode, or in the Web browser of your choice outside
the JavaTest interface. To see all of the HTML report files, enter the
URL of the `report.html` file. This file is the root file that links to
all of the other HTML reports.

The JavaTest harness also creates a `summary.txt` file in the report
directory that you can open in any text editor. The `summary.txt` file
contains a list of all tests that were run, their test results, and
their status messages.

The work directory, which you specified by setting the `work.dir`
property in the `ts.jte` file, contains several files that were
deposited there during test execution: `harness.trace`, `log.txt`,
`lastRun.txt`, and `testsuite`. Most of these files provide information
about the harness and environment in which the tests were executed.


[NOTE]
=======================================================================

You can set `harness.log.traceflag=true` in `<TS_HOME>/bin/ts.jte` to
get more debugging information.

=======================================================================


If a large number of tests failed, you should read
link:#GBFYF[Recognizing Configuration Failures] to see if a
configuration issue is the cause of the failures.

[[GJCYT]][[TCJSE00048]][[debugging-test-results-with-the-javatest-gui]]

6.2 Debugging Test Results with the JavaTest GUI
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The following sections describe features of the JavaTest GUI that enable
you to view and analyze the results of your test runs.

[[GJCZI]][[TCJSE00069]][[using-the-test-tree-in-the-gui]]

6.2.1 Using the Test Tree in the GUI
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Use the test tree in the JavaTest GUI to identify specific folders and
tests that had errors or failing results. Color codes are used to
indicate status as follows:

* Green: Passed
* Blue: Test Error
* Red: Failed to pass test
* White: Test not run
* Gray: Test filtered out (not run)

[[GJCYY]][[TCJSE00070]][[displaying-folder-information-in-the-gui]]

6.2.2 Displaying Folder Information in the GUI
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Click a folder in the test tree in the JavaTest GUI to display its tabs.

Choose the Error and the Failed tabs to view the lists of all tests in
and under a folder that were not successfully run. You can double-click
a test in the lists to view its test information.

[[GJCZZ]][[TCJSE00071]][[displaying-test-information-in-the-gui]]

6.2.3 Displaying Test Information in the GUI
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To display information about a test in the JavaTest GUI, click its icon
in the test tree or double-click its name in a folder status tab. The
tab contains detailed information about the test run and, at the bottom
of the window, a brief status message identifying the type of failure or
error. This message may be sufficient for you to identify the cause of
the error or failure.

If you need more information to identify the cause of the error or
failure, use the following tabs listed in order of importance:

* Test Run Messages contains a Message list and a Message section that
display the messages produced during the test run.
* Test Run Details contains a two-column table of name/value pairs
recorded when the test was run.
* Configuration contains a two-column table of the test environment
name/value pairs derived from the configuration data actually used to
run the test.

[[GJCIB]][[TCJSE00072]][[creating-and-viewing-test-reports-in-gui-mode]]

6.2.4 Creating and Viewing Test Reports in GUI Mode
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This section explains how to use the GUI to create and view report
files.

[[GBFVH]][[TCJSE00023]][[to-create-a-test-report]]

6.2.4.1 To Create a Test Report
+++++++++++++++++++++++++++++++

1.  From the JavaTest main menu, click Report, and then click Create
Report. +
You are prompted to specify a directory to use for your test reports.
The default location is `/tmp/JTreport` or whatever was specified by the
`report.dir` property in the `ts.jte` file.
2.  Specify the directory you want to use for your reports, and then
click OK. +
Use the Filter list to specify whether you want to generate reports for
the current configuration, for all tests, or for a custom set of tests. +
You are asked whether you want to view report now.
3.  Click Yes to display the new report in the JavaTest ReportBrowser.

[[GBFVO]][[TCJSE00024]][[to-view-an-existing-report]]

6.2.4.2 To View an Existing Report
++++++++++++++++++++++++++++++++++

1.  From the JavaTest main menu, click Report, then click Open Report. +
You are prompted to specify the directory containing the report you want
to open.
2.  Select the report directory you want to open, and then click Open. +
The selected report set is opened in the JavaTest ReportBrowser.

[[GJCYI]][[TCJSE00049]][[creating-and-viewing-report-and-log-files-using-ant]]

6.3 Creating and Viewing Report and Log Files Using Ant
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This section explains how to use Ant to create and view report files.

[[GJCXH]][[TCJSE00073]][[to-create-a-test-report-1]]

6.3.1 To Create A Test Report
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To create a report from the command line at a desired location:

[source,oac_no_warn]
----
ant report -Dreport.dir="report_dir"
----

Reports for the last test run will be written to the directory you
specify.

If you do not specify a directory, reports will be written to the
location specified by the `report.dir` property in the `ts.jte` file.

[[GJDIZ]][[TCJSE00074]][[to-view-a-test-report]]

6.3.2 To View a Test Report
^^^^^^^^^^^^^^^^^^^^^^^^^^^

1.  Change to the report directory you that you specified from the
command line or set in the `ts.jte` file.
2.  Start the Web/Application browser of your choice from that directory
or browse to that directory.
3.  View the `report.html` file.

[[GJDHF]][[TCJSE00075]][[to-examine-log-files]]

6.3.3 To Examine Log Files
^^^^^^^^^^^^^^^^^^^^^^^^^^

1.  Change to the work directory you that you set in the `ts.jte` file.
2.  Look in the `harness.trace`, `log.txt`, `lastRun.txt`, and
`testsuite` files to see if configuration issues related to the test
environment or the test harness were the cause of the test failures.

[[GBFYF]][[TCJSE00050]][[recognizing-configuration-failures]]

6.4 Recognizing Configuration Failures
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Configuration failures are easily recognized because many tests fail the
same way. When all your tests begin to fail, you may want to stop the
run immediately and start viewing individual test output. However, in
the case of full-scale launching problems where no tests are actually
processed, report files are usually not created (though sometimes a
small `harness.trace` file in the report directory is written).


