///////////////////////////////////////////////////////////////////////
NOTE TO WRITERS:
This is a list of software required in addition to the TCK and the RI.
For many Jakarta EE APIs, the Jakarta EE RI will be required, as described below.
For standalone technologies, no other software may be required, and the
below line can be removed.

This is used in intro.adoc in section 1.3 and install.adoc in section 3.2.
///////////////////////////////////////////////////////////////////////

* A Jakarta EE 10 CI (for example {TechnologyRI}) or, at a minimum, a Web server with a Servlet 6.0 container
