type=page
status=published
title=Technology Compatibility Kit User's Guide for Java API for WebSocket 1.1, Release 1.1 for Jakarta EE
next=TCKpreface.html
prev=toc.html
~~~~~~
Technology Compatibility Kit User's Guide for Java API for WebSocket 1.1, Release 1.1 for Jakarta EE
====================================================================================================

[[oracle]]
Eclipse Foundation™
-------------------

Technology Compatibility Kit User's Guide for Java API for WebSocket 1.1

Release 1.1 for Jakarta EE

September 2017

[[sthref1]]

'''''

Technology Compatibility Kit User's Guide for Java API for WebSocket
1.1, Release 1.1 for Jakarta EE


Copyright © 2014, 2017 Oracle and/or its affiliates. All rights
reserved.

Primary Author:

This program and the accompanying materials are made available under the terms of the Eclipse Public License v. 2.0, which is available at http://www.eclipse.org/legal/epl-2.0.

SPDX-License-Identifier: EPL-2.0

Oracle and Java are registered trademarks of Oracle and/or its affiliates. Other names may be trademarks of their respective owners.

Intel and Intel Xeon are trademarks or registered trademarks of Intel Corporation. All SPARC trademarks are used under license and are trademarks or registered trademarks of SPARC International, Inc. AMD, Opteron, the AMD logo, and the AMD Opteron logo are trademarks or registered trademarks of Advanced Micro Devices. UNIX is a registered trademark of The Open Group.


