.  Install the Jakarta EE {JakartaEEVersion} CI software (the servlet Web container used
for running the {TechnologyShortName} TCK with the
{TechnologyShortName} {TechnologyVersion} CI), if it is not already
installed. +
Download and install the Servlet Web container with the
{TechnologyShortName} {TechnologyVersion} CI used for running the
{TechnologyShortName} TCK {TechnologyVersion}, represented by a Jakarta
EE {JakartaEEVersion} CI.
You are free to us any CI that is certified. The folloiwng are some examples you can choose from:
* If you wish to use {TechnologyRI} you may obtain it from {TechnologyRIURL}
* If you wish to use Eclipse GlassFish 6.0 you may obtain it from https://projects.eclipse.org/projects/ee4j.glassfish