** `javax.faces`

** `javax.faces.application`

** `javax.faces.bean`

** `javax.faces.component`

** `javax.faces.component.behavior`

** `javax.faces.component.html`

** `javax.faces.component.visit`

** `javax.faces.context`

** `javax.faces.convert`

** `javax.faces.el`

** `javax.faces.event`

** `javax.faces.lifecycle`

** `javax.faces.model`

** `javax.faces.render`

** `javax.faces.validator`

** `javax.faces.view`

** `javax.faces.view.facelets`

** `javax.faces.webapp`