** `jakarta.faces`

** `jakarta.faces.application`

** `jakarta.faces.bean`

** `jakarta.faces.component`

** `jakarta.faces.component.behavior`

** `jakarta.faces.component.html`

** `jakarta.faces.component.visit`

** `jakarta.faces.context`

** `jakarta.faces.convert`

** `jakarta.faces.el`

** `jakarta.faces.event`

** `jakarta.faces.lifecycle`

** `jakarta.faces.model`

** `jakarta.faces.render`

** `jakarta.faces.validator`

** `jakarta.faces.view`

** `jakarta.faces.view.facelets`

** `jakarta.faces.webapp`