.  Install the Java EE 8 RI software (the servlet Web container used
for running the {TechnologyShortName} TCK with the
{TechnologyShortName} {TechnologyVersion} CI), if it is not already
installed. +
Download and install the Servlet Web container with the
{TechnologyShortName} {TechnologyVersion} RI used for running the
{TechnologyShortName} TCK {TechnologyVersion}, represented by the Jakarta
EE 8 CI (For example, Eclise GlassFish 5.1).
You may obtain {TechnologyRI} from {TechnologyRIURL}.
