/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 2002 International Business Machines Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.xmlnamemappingtest;

public interface XMLNameMappingTest extends java.rmi.Remote {
  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.xmlnamemappingtest.EyeColor echoEyeColor(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.xmlnamemappingtest.EyeColor inputEyeColor)
      throws java.rmi.RemoteException;

  public com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.xmlnamemappingtest.SoapStruct echoSoapStruct(
      com.sun.ts.tests.jaxrpc.ee.w2j.rpc.encoded.xmlnamemappingtest.SoapStruct inputSoapStruct)
      throws java.rmi.RemoteException;

  public void _null() throws java.rmi.RemoteException;

  public void _true() throws java.rmi.RemoteException;

  public void _false() throws java.rmi.RemoteException;

  public void _abstract() throws java.rmi.RemoteException;

  public void _boolean() throws java.rmi.RemoteException;

  public void _break() throws java.rmi.RemoteException;

  public void _byte() throws java.rmi.RemoteException;

  public void _case() throws java.rmi.RemoteException;

  public void _catch() throws java.rmi.RemoteException;

  public void _char() throws java.rmi.RemoteException;

  public void _class() throws java.rmi.RemoteException;

  public void _const() throws java.rmi.RemoteException;

  public void _continue() throws java.rmi.RemoteException;

  public void _default() throws java.rmi.RemoteException;

  public void _do() throws java.rmi.RemoteException;

  public void _double() throws java.rmi.RemoteException;

  public void _else() throws java.rmi.RemoteException;

  public void _extends() throws java.rmi.RemoteException;

  public void _final() throws java.rmi.RemoteException;

  public void _finally() throws java.rmi.RemoteException;

  public void _float() throws java.rmi.RemoteException;

  public void _for() throws java.rmi.RemoteException;

  public void _goto() throws java.rmi.RemoteException;

  public void _if() throws java.rmi.RemoteException;

  public void _implements() throws java.rmi.RemoteException;

  public void _import() throws java.rmi.RemoteException;

  public void _instanceof() throws java.rmi.RemoteException;

  public void _int() throws java.rmi.RemoteException;

  public void _interface() throws java.rmi.RemoteException;

  public void _long() throws java.rmi.RemoteException;

  public void _native() throws java.rmi.RemoteException;

  public void _new() throws java.rmi.RemoteException;

  public void _package() throws java.rmi.RemoteException;

  public void _private() throws java.rmi.RemoteException;

  public void _protected() throws java.rmi.RemoteException;

  public void _public() throws java.rmi.RemoteException;

  public void _return() throws java.rmi.RemoteException;

  public void _short() throws java.rmi.RemoteException;

  public void _static() throws java.rmi.RemoteException;

  public void _super() throws java.rmi.RemoteException;

  public void _switch() throws java.rmi.RemoteException;

  public void _synchronized() throws java.rmi.RemoteException;

  public void _this() throws java.rmi.RemoteException;

  public void _throw() throws java.rmi.RemoteException;

  public void _throws() throws java.rmi.RemoteException;

  public void _transient() throws java.rmi.RemoteException;

  public void _try() throws java.rmi.RemoteException;

  public void _void() throws java.rmi.RemoteException;

  public void _volatile() throws java.rmi.RemoteException;

  public void _while() throws java.rmi.RemoteException;
}
