/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 2002 International Business Machines Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.sun.ts.tests.webservices.wsdlImport.http.nested3;

public class GetLastTradePrice {
  private java.lang.String tickerSymbol;

  public GetLastTradePrice() {
  }

  public GetLastTradePrice(java.lang.String tickerSymbol) {
    this.tickerSymbol = tickerSymbol;
  }

  public java.lang.String getTickerSymbol() {
    return tickerSymbol;
  }

  public void setTickerSymbol(java.lang.String tickerSymbol) {
    this.tickerSymbol = tickerSymbol;
  }
}
