/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build EA2-R41)

package com.sun.ts.tests.jaxrpc.ee.wsi.rpc.literal.holdertest;

public class Book {
  protected java.lang.String author;

  protected java.lang.String title;

  protected int isbn;

  public Book() {
  }

  public Book(java.lang.String author, java.lang.String title, int isbn) {
    this.author = author;
    this.title = title;
    this.isbn = isbn;
  }

  public java.lang.String getAuthor() {
    return author;
  }

  public void setAuthor(java.lang.String author) {
    this.author = author;
  }

  public java.lang.String getTitle() {
    return title;
  }

  public void setTitle(java.lang.String title) {
    this.title = title;
  }

  public int getIsbn() {
    return isbn;
  }

  public void setIsbn(int isbn) {
    this.isbn = isbn;
  }
}
