
#ALTER TABLE COMPLEXPK_TABLE1 drop foreign key FKFOR_LINEITEMS !
#ALTER TABLE COMPLEXPK_LINEITEM_TABLE1 drop foreign key FKFOR_ID !

ALTER TABLE PHONEEJB_TABLE drop foreign key FK_FOR_ADDRESSEJB_TABLE !

ALTER TABLE ALIASEJB_TABLE drop foreign key FK1_FOR_CUSTOMEREJB_TABLE !

ALTER TABLE ALIASEJB_TABLE drop foreign key FK2_FOR_CUSTOMEREJB_TABLE !

ALTER TABLE FKS_FOR_ALIAS_CUSTOMER drop foreign key FK_FOR_CUSTOMEREJB_TABLE !

ALTER TABLE FKS_FOR_ALIAS_CUSTOMER drop foreign key FK_FOR_ALIASEJB_TABLE !

ALTER TABLE CREDITCARDEJB_TABLE drop foreign key FK3_FOR_CUSTOMEREJB_TABLE !

ALTER TABLE CREDITCARDEJB_TABLE drop foreign key FK_FOR_ORDEREJB_TABLE !

ALTER TABLE ORDEREJB_TABLE drop foreign key FK4_FOR_CUSTOMEREJB_TABLE !

ALTER TABLE ORDEREJB_TABLE drop foreign key FK0_FOR_LINEITEMEJB_TABLE !

ALTER TABLE LINEITEMEJB_TABLE drop foreign key FK_FOR_PRODUCTEJB_TABLE !

ALTER TABLE LINEITEMEJB_TABLE drop foreign key FK1_FOR_ORDEREJB_TABLE !

ALTER TABLE ADDRESSEJB_TABLE drop foreign key FK5_FOR_CUSTOMEREJB_TABLE !

ALTER TABLE ADDRESSEJB_TABLE drop foreign key FK6_FOR_CUSTOMEREJB_TABLE !

ALTER TABLE BEANEJB_1X1_BI_BTOB drop foreign key FK1_FOR_AEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_BTOB drop foreign key FK2_FOR_AEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_BTOB drop foreign key FK1_FOR_BEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_BTOB drop foreign key FK2_FOR_BEJB_1X1_BI_BTOB !

ALTER TABLE BEJB_1X1_BI_BTOB drop foreign key FK_FOR_AEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_CASCADE drop foreign key FK1_FOR_AEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_BI_CASCADE drop foreign key FK2_FOR_AEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_BI_CASCADE drop foreign key FK1_FOR_BEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_BI_CASCADE drop foreign key FK2_FOR_BEJB_1X1_BI_CASCADE !

ALTER TABLE BEJB_1X1_BI_CASCADE drop foreign key FK_FOR_AEJB_1X1_BI_CASCADE !

ALTER TABLE TABLER5_DELETE drop foreign key FK1_FOR_TABLER6_DELETE_ID !

ALTER TABLE TABLER5_DELETE drop foreign key FK2_FOR_TABLER6_DELETE_ID !

ALTER TABLE TABLER5_DELETE drop foreign key FK1_FOR_TABLER7_DELETE_ID !

ALTER TABLE TABLER5_DELETE drop foreign key FK2_FOR_TABLER7_DELETE_ID !

ALTER TABLE TABLER7_DELETE drop foreign key FK_FOR_TABLER6_DELETE_ID !

ALTER TABLE BEANEJB_1X1_UNI_BTOB drop foreign key FK1_FOR_AEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1X1_UNI_BTOB drop foreign key FK2_FOR_AEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1X1_UNI_BTOB drop foreign key FK1_FOR_BEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1X1_UNI_BTOB drop foreign key FK2_FOR_BEJB_1X1_UNI_BTOB !

ALTER TABLE BEJB_1X1_UNI_BTOB drop foreign key FK_FOR_AEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK1_FOR_AEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK2_FOR_AEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK1_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK2_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK3_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK4_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEJB_1XM_BI_BTOB drop foreign key FK_FOR_AEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_CASCADE drop foreign key FK1_FOR_AEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_CASCADE drop foreign key FK2_FOR_AEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_CASCADE drop foreign key FK1_FOR_BEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_CASCADE drop foreign key FK2_FOR_BEJB_1XM_BI_CASCADE !

ALTER TABLE BEJB_1XM_BI_CASCADE drop foreign key FK_FOR_AEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_DELETE drop foreign key FK1_FOR_AEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_BI_DELETE drop foreign key FK2_FOR_AEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_BI_DELETE drop foreign key FK1_FOR_BEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_BI_DELETE drop foreign key FK2_FOR_BEJB_1XM_BI_DELETE !

ALTER TABLE BEJB_1XM_BI_DELETE drop foreign key FK_FOR_AEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK1_FOR_AEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK2_FOR_AEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK1_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK2_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK3_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK4_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEJB_1XM_UNI_BTOB drop foreign key FK_FOR_AEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK1_FOR_AEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK2_FOR_AEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK1_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK2_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK3_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK4_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEJB_MX1_UNI_BTOB drop foreign key FK_FOR_AEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK1_FOR_AEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK2_FOR_AEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK1_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK2_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK3_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK4_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEJB_MX1_UNI_DELETE drop foreign key FK_FOR_AEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK1_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK2_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK3_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK4_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK1_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK2_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK3_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK4_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE FKEYS_MXM_BI_BTOB drop foreign key FK_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE FKEYS_MXM_BI_BTOB drop foreign key FK_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK1_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK2_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK3_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK4_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK1_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK2_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK3_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK4_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE FKEYS_MXM_BI_DELETE drop foreign key FK_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE FKEYS_MXM_BI_DELETE drop foreign key FK_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK1_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK2_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK3_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK4_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK1_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK2_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK3_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK4_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE FKEYS_MXM_UNI_BTOB drop foreign key FK_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE FKEYS_MXM_UNI_BTOB drop foreign key FK_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE FKS_ALIASNOOP_CUSTNOOP  drop foreign key FK2_FOR_ALIASEJB_TABLE !

ALTER TABLE FKS_ALIASNOOP_CUSTNOOP  drop foreign key FK8_FOR_CUSTOMEREJB_TABLE !

ALTER TABLE SPOUSEEJB_TABLE drop foreign key FK7_FOR_CUSTOMEREJB_TABLE !

ALTER TABLE SPOUSEEJB_TABLE drop foreign key FK_FOR_INFOEJB_TABLE !

ALTER TABLE INFOEJB_TABLE drop foreign key FK_FOR_SPOUSEEJB_TABLE !

ALTER TABLE COMPLEXPK_TABLE1 drop foreign key FK_FOR_LINEITEMS !

ALTER TABLE COMPLEXPK_LINEITEM_TABLE1 drop foreign key FK_FOR_ID !

ALTER TABLE EMPLOYEEEJB drop foreign key FK_MANAGER !

ALTER TABLE EMPLOYEEEJB drop foreign key FK_DEPARTMENT !

drop table COMMON_TABLE !
create table COMMON_TABLE(ID INTEGER, BRANDNAME  varchar(25), PRICE  REAL, constraint COMMON_TABLE1 primary key(ID)) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table COMMON_TABLE2 !
create table COMMON_TABLE2(ID INTEGER , BRANDNAME  varchar(25), PRICE  REAL, constraint COMMON_TABLE2 primary key(ID)) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table COMMON_TABLE3 !
create table COMMON_TABLE3(ID INTEGER , BRANDNAME  varchar(25), PRICE  REAL, constraint COMMON_TABLE3 primary key(ID)) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table LOCALACCESSTEST_TABLE1  !
create table LOCALACCESSTEST_TABLE1( id  INTEGER, name  varchar(25), value  REAL, constraint LOCALACCESSTEST_TABLE1 primary key(id)) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table EBACCESSTEST_TABLE2  !
create table EBACCESSTEST_TABLE2( id  INTEGER, name  varchar(25), value REAL, constraint EBACCESSTEST_TABLE2 primary key(id))  ENGINE=innoDB DEFAULT CHARSET=latin1!   

drop table MDBACCESSTEST_TABLE1 CASCADE !
create table MDBACCESSTEST_TABLE1( id  INTEGER, name  varchar(25), value  REAL, constraint MDBACCESSTEST_TABLE1 primary key(id)) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table MDBTACCESSTEST_TABLE1 CASCADE !
create table MDBTACCESSTEST_TABLE1( id  INTEGER, name  varchar(25), value  REAL, constraint MDBTACCESSTEST_TABLE1 primary key(id)) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table SBACCESSTEST_TABLE1 CASCADE !
create table SBACCESSTEST_TABLE1( id  INTEGER, name  varchar(25), value  REAL, constraint SBACCESSTEST_TABLE1 primary key(id)) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table ENTITY_BEAN_TABLE1  !
create table ENTITY_BEAN_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint ENTITY_BEAN_TABLE1 primary key(KEY_ID)) ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table ADDRESSEJB_TABLE  !
create TABLE ADDRESSEJB_TABLE (id VARCHAR(255) PRIMARY KEY, street VARCHAR(255), city VARCHAR(255), state VARCHAR(255), zip VARCHAR(255), FK5_FOR_CUSTOMEREJB_TABLE VARCHAR(255), FK6_FOR_CUSTOMEREJB_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
        
drop table PHONEEJB_TABLE  !
create TABLE PHONEEJB_TABLE (id VARCHAR(255) PRIMARY KEY, area VARCHAR(255), phone_number VARCHAR(255), FK_FOR_ADDRESSEJB_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
        
drop table CUSTOMEREJB_TABLE  !
create TABLE CUSTOMEREJB_TABLE (id VARCHAR(255) PRIMARY KEY, name VARCHAR(255) , country blob) ENGINE=innoDB DEFAULT CHARSET=latin1!
         
drop table ALIASEJB_TABLE  !
create TABLE ALIASEJB_TABLE (id VARCHAR(255) PRIMARY KEY, alias VARCHAR(255), FK1_FOR_CUSTOMEREJB_TABLE  VARCHAR(255), FK2_FOR_CUSTOMEREJB_TABLE  VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
         
drop table FKS_FOR_ALIAS_CUSTOMER  !
create TABLE FKS_FOR_ALIAS_CUSTOMER ( FK_FOR_CUSTOMEREJB_TABLE VARCHAR(255) , FK_FOR_ALIASEJB_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table FKS_ALIASNOOP_CUSTNOOP !
create TABLE FKS_ALIASNOOP_CUSTNOOP( FK8_FOR_CUSTOMEREJB_TABLE VARCHAR(255) , FK2_FOR_ALIASEJB_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CREDITCARDEJB_TABLE  !
create TABLE CREDITCARDEJB_TABLE (id VARCHAR(255) PRIMARY KEY, type VARCHAR(255), expires VARCHAR(255), approved NUMERIC, creditcard_number VARCHAR(255), balance DOUBLE  PRECISION, FK3_FOR_CUSTOMEREJB_TABLE VARCHAR(255), FK_FOR_ORDEREJB_TABLE VARCHAR(255) ) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table ORDEREJB_TABLE  !
create TABLE  ORDEREJB_TABLE (id VARCHAR(255) PRIMARY KEY, totalPrice float , FK4_FOR_CUSTOMEREJB_TABLE VARCHAR(255), FK0_FOR_LINEITEMEJB_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
 
drop table PRODUCTEJB_TABLE  !
create TABLE PRODUCTEJB_TABLE (id VARCHAR(255) PRIMARY KEY, name VARCHAR(255), price float, quantity integer, pnum integer ) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table SPOUSEEJB_TABLE !
create TABLE SPOUSEEJB_TABLE (ID VARCHAR(255) PRIMARY KEY,  FIRSTNAME VARCHAR(255), MAIDENNAME VARCHAR(255), LASTNAME VARCHAR(255), SOCSECNUM VARCHAR(255), FK7_FOR_CUSTOMEREJB_TABLE VARCHAR(255), FK_FOR_INFOEJB_TABLE VARCHAR(255) ) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table INFOEJB_TABLE !
create TABLE INFOEJB_TABLE (ID VARCHAR(255) PRIMARY KEY, INFOSTREET VARCHAR(255), INFOCITY VARCHAR(255), INFOSTATE VARCHAR(255), INFOZIP VARCHAR(255), FK_FOR_SPOUSEEJB_TABLE VARCHAR(255) ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table LINEITEMEJB_TABLE  !
create TABLE LINEITEMEJB_TABLE (id VARCHAR(255) PRIMARY KEY, quantity integer, FK_FOR_PRODUCTEJB_TABLE VARCHAR(255), FK1_FOR_ORDEREJB_TABLE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
         
ALTER TABLE PHONEEJB_TABLE add ( constraint FK_FOR_ADDRESSEJB_TABLE Foreign Key (FK_FOR_ADDRESSEJB_TABLE) references ADDRESSEJB_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE ALIASEJB_TABLE add ( constraint FK1_FOR_CUSTOMEREJB_TABLE Foreign Key (FK1_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE ALIASEJB_TABLE add ( constraint FK2_FOR_CUSTOMEREJB_TABLE Foreign Key (FK2_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE FKS_FOR_ALIAS_CUSTOMER  add ( constraint FK_FOR_CUSTOMEREJB_TABLE Foreign Key (FK_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE FKS_FOR_ALIAS_CUSTOMER  add ( constraint FK_FOR_ALIASEJB_TABLE Foreign Key (FK_FOR_ALIASEJB_TABLE) references ALIASEJB_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE FKS_ALIASNOOP_CUSTNOOP  add ( constraint FK2_FOR_ALIASEJB_TABLE Foreign Key (FK2_FOR_ALIASEJB_TABLE) references ALIASEJB_TABLE(id) ON DELETE CASCADE)!

ALTER TABLE FKS_ALIASNOOP_CUSTNOOP  add (constraint FK8_FOR_CUSTOMEREJB_TABLE Foreign Key (FK8_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(id) ON DELETE CASCADE)!

ALTER TABLE CREDITCARDEJB_TABLE add ( constraint FK3_FOR_CUSTOMEREJB_TABLE Foreign Key (FK3_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE CREDITCARDEJB_TABLE add ( constraint FK_FOR_ORDEREJB_TABLE Foreign Key (FK_FOR_ORDEREJB_TABLE) references ORDEREJB_TABLE(id) ON DELETE CASCADE ) !
       
ALTER TABLE ORDEREJB_TABLE add ( constraint FK4_FOR_CUSTOMEREJB_TABLE Foreign Key (FK4_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE ORDEREJB_TABLE add ( constraint FK0_FOR_LINEITEMEJB_TABLE Foreign Key (FK0_FOR_LINEITEMEJB_TABLE) references LINEITEMEJB_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE LINEITEMEJB_TABLE add ( constraint FK_FOR_PRODUCTEJB_TABLE Foreign Key (FK_FOR_PRODUCTEJB_TABLE) references PRODUCTEJB_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE LINEITEMEJB_TABLE add ( constraint FK1_FOR_ORDEREJB_TABLE Foreign Key (FK1_FOR_ORDEREJB_TABLE) references ORDEREJB_TABLE(id) ON DELETE CASCADE ) !
 
ALTER TABLE ADDRESSEJB_TABLE add ( constraint FK5_FOR_CUSTOMEREJB_TABLE Foreign Key (FK5_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE ADDRESSEJB_TABLE add ( constraint FK6_FOR_CUSTOMEREJB_TABLE Foreign Key (FK6_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(id) ON DELETE CASCADE ) !
   
ALTER TABLE SPOUSEEJB_TABLE add (constraint FK7_FOR_CUSTOMEREJB_TABLE Foreign Key(FK7_FOR_CUSTOMEREJB_TABLE) references CUSTOMEREJB_TABLE(ID) ON DELETE CASCADE) ! 

ALTER TABLE SPOUSEEJB_TABLE add (constraint FK_FOR_INFOEJB_TABLE Foreign Key (FK_FOR_INFOEJB_TABLE) references INFOEJB_TABLE(ID) ON DELETE CASCADE) !

ALTER TABLE INFOEJB_TABLE add (constraint FK_FOR_SPOUSEEJB_TABLE Foreign Key (FK_FOR_SPOUSEEJB_TABLE) references SPOUSEEJB_TABLE(ID) ON DELETE CASCADE) !

drop table EJBQL_TABLE1  !
create table EJBQL_TABLE1 ( ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBQL_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EJBQL_TABLE2  !
create table EJBQL_TABLE2 ( ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBQL_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EJBQL_TABLE3  !
create table EJBQL_TABLE3 ( ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBQL_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_ALLOWEDM_TABLE1  !
create table CMP20_ALLOWEDM_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ALLOWEDM_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_CLIENTVIEW_TABLE1  !
create table CMP20_CLIENTVIEW_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_CLIENTVIEW_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table COMPLEXPK_TABLE1  !
create table COMPLEXPK_TABLE1( ID INTEGER, BRANDNAME varchar(25), PRICE REAL, PRODUCT BLOB, FK_FOR_LINEITEMS varchar(25) , constraint  COMPLEXPK_TABLE1 primary key(ID,BRANDNAME))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop  table COMPLEXPK_LINEITEM_TABLE1  !
create table COMPLEXPK_LINEITEM_TABLE1(ID varchar(25), QUANTITY INTEGER, FK_FOR_ID INTEGER, FK_FOR_BRANDNAME varchar(25), constraint COMPLEXPK_LINEITEM_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE COMPLEXPK_TABLE1 add (constraint FK_FOR_LINEITEMS  Foreign Key (FK_FOR_LINEITEMS) references COMPLEXPK_LINEITEM_TABLE1(ID) ON DELETE CASCADE) !

ALTER TABLE COMPLEXPK_LINEITEM_TABLE1 add (constraint FK_FOR_ID Foreign Key (FK_FOR_ID, FK_FOR_BRANDNAME) references COMPLEXPK_TABLE1(ID,BRANDNAME) ON DELETE CASCADE ) !


drop table CMP20_ENTITYCMP_TABLE1  !
create table CMP20_ENTITYCMP_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, B BLOB, constraint CMP20_ENTITYCMP_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop  table CMP20_ENTITY_CTX_TABLE1  !
create TABLE CMP20_ENTITY_CTX_TABLE1 (KEY_ID VARCHAR(255) NOT NULL, BRAND_NAME VARCHAR(255) , CONSTRAINT CMP20_ENTITY_CTX_TABLE1 primary key (KEY_ID) )  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_HANDLE_TABLE1  !
create table CMP20_HANDLE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_HANDLE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_HOMEM_TABLE1  !
create table CMP20_HOMEM_TABLE1 ( NAME VARCHAR(255), STATE VARCHAR(255), CODE VARCHAR(255), ZIP INTEGER, ID INTEGER, EXPIRES VARCHAR(255), STREET VARCHAR(255), CARDBALANCE double precision, CITY VARCHAR(255), HOMEPHONE VARCHAR(255), WORKPHONE  VARCHAR(255), LASTNAME VARCHAR(255), PAYMENTTYPE VARCHAR(255), CREDITCARDNUMBER VARCHAR(255), ACCOUNTNUMBER VARCHAR(255), MIDDLENAME VARCHAR(255), FIRSTNAME VARCHAR(255), CONSTRAINT CMP20_HOMEM_TABLE1 PRIMARY KEY(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_MULTI_CLIENT_TABLE1  !
create table CMP20_MULTI_CLIENT_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_MULTI_CLIENT_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_NON_REENTRANT_TABLE1  !
create table CMP20_NON_REENTRANT_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_NON_REENTRANT_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_REENTRANT_TABLE1  !
create table CMP20_REENTRANT_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_REENTRANT_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table UNKNOWNPK_TABLE1  !
create table UNKNOWNPK_TABLE1(MIDDLENAME VARCHAR(255), LASTNAME VARCHAR(255), FIRSTNAME VARCHAR(255), STREET VARCHAR(255), CITY VARCHAR(255), STATE VARCHAR(255), ZIP VARCHAR(255), ACCOUNTNUMBER VARCHAR(255), ABC NUMERIC(29) NOT NULL, constraint UNKNOWNPK_TABLE1 primary key(ABC))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table ALLOWEDMETHODS_TABLE0  !
create table ALLOWEDMETHODS_TABLE0( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint allowedmethods_Table0 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP_CLIENTVIEW_TABLE1  !
create table CMP_CLIENTVIEW_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  FLOAT, constraint CMP_CLIENTVIEW_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP_COMPLEXPK_TABLE1  !
create table CMP_COMPLEXPK_TABLE1 (ID  INTEGER, BRAND_NAME  varchar(25), PRICE REAL,PRODUCT  blob, FK_FOR_LINEITEMS varchar(25), constraint CMP_COMPLEXPK_TABLE1 primary key(ID,BRAND_NAME))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP_ENTITY_BEAN_TABLE1  !
create table CMP_ENTITY_BEAN_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP_ENTITY_BEAN_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP_ENTITY_CTX_TABLE1  !
create table CMP_ENTITY_CTX_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP_ENTITY_CTX_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP_HANDLE_TABLE1  !
create table CMP_HANDLE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP_HANDLE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP_MULTI_CLIENT_TABLE1  !
create table CMP_MULTI_CLIENT_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP_MULTI_CLIENT_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP_NON_ENTRANT_TABLE1  !
create table CMP_NON_ENTRANT_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP_NON_ENTRANT_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP_REENTRANT_TABLE1  !
create table CMP_REENTRANT_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP_REENTRANT_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table LRAPITEST_TABLE1  !
create table LRAPITEST_TABLE1 (id  INTEGER,name  varchar(25),value  REAL, constraint LRAPITEST_TABLE1  primary key(id))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table LRAPITEST_TABLE2  !
create table LRAPITEST_TABLE2(id  INTEGER,name  varchar(25),value REAL, constraint LRAPITEST_TABLE2 primary key(id))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table LRAPITEST_TABLE3  !
create table LRAPITEST_TABLE3(id  INTEGER,name  varchar(25),value REAL,constraint LRAPITEST_TABLE3 primary key(id))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_BMP_ARGSEMANTICS_TABLE1  !
create table CMP20_BMP_ARGSEMANTICS_TABLE1 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP20BMPARGSEMANTICSTABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_BMP_ARGSEMANTICS_TABLE2  !
create table CMP20_BMP_ARGSEMANTICS_TABLE2 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP20BMPARGSEMANTICSTABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_BMP_ARGSEMANTICS_TABLE3  !
create table CMP20_BMP_ARGSEMANTICS_TABLE3 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP20BMPARGSEMANTICSTABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_BMP_ARGSEMANTICS_TAB1  !
create table CMP20_BMP_ARGSEMANTICS_TAB1 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP20BMPARGSEMANTICSTAB1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_BMP_ARGSEMANTICS_TAB2  !
create table CMP20_BMP_ARGSEMANTICS_TAB2 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP20BMPARGSEMANTICSTAB2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_BMP_ARGSEMANTICS_TAB3  !
create table CMP20_BMP_ARGSEMANTICS_TAB3 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP20BMPARGSEMANTICSTAB3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_ARG_SEMANTICS_TABLE1  !
create table CMP20_ARG_SEMANTICS_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ARG_SEMANTICS_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ARG_SEMANTICS_TABLE2  !
create table CMP20_ARG_SEMANTICS_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ARG_SEMANTICS_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ARG_SEMANTICS_TABLE3  !
create table CMP20_ARG_SEMANTICS_TABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ARG_SEMANTICS_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ARG_SEMANTICS_TABLE4  !
create table CMP20_ARG_SEMANTICS_TABLE4 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ARG_SEMANTICS_TABLE4 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1 !  

drop table CMP20_ARG_SEMANTICS_TABLE5  !
create table CMP20_ARG_SEMANTICS_TABLE5 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ARG_SEMANTICS_TABLE5 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ARG_SEMANTICS_TABLE6  !
create table CMP20_ARG_SEMANTICS_TABLE6 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ARG_SEMANTICS_TABLE6 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ARG_SEMANTICS_TABLE7  !
create table CMP20_ARG_SEMANTICS_TABLE7 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ARG_SEMANTICS_TABLE7 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ARG_SEMANTICS_TABLE8  !
create table CMP20_ARG_SEMANTICS_TABLE8 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ARG_SEMANTICS_TABLE8 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1 !  

drop table CMP20_SFUL_ARGSEMANTICS_TAB1  !
create table CMP20_SFUL_ARGSEMANTICS_TAB1 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP20SFULARGSEMANTICSTAB1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_SFUL_ARGSEMANTICS_TAB2  !
create table CMP20_SFUL_ARGSEMANTICS_TAB2 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP20SFULARGSEMANTICSTAB2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_SFUL_ARGSEMANTICS_TAB3  !
create table CMP20_SFUL_ARGSEMANTICS_TAB3 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP20SFULARGSEMANTICSTAB3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_SSL_ARGSEMANTICS_TAB1  !
create table CMP20_SSL_ARGSEMANTICS_TAB1 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP20SSLARGSEMANTICSTAB1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_SSL_ARGSEMANTICS_TAB2  !
create table CMP20_SSL_ARGSEMANTICS_TAB2 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP20SSLARGSEMANTICSTAB2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_SSL_ARGSEMANTICS_TAB3  !
create table CMP20_SSL_ARGSEMANTICS_TAB3 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP20SSLARGSEMANTICSTAB3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table COMPAT_ENTITYCMP_TABLE1  !
create table COMPAT_ENTITYCMP_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint COMPAT_ENTITYCMP_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table TX_NOT_TABLE3  !
create table TX_NOT_TABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint TX_NOT_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table TX_NOT_TABLE4  !
create table TX_NOT_TABLE4 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint TX_NOT_TABLE4 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

   
drop table CMP20_INTERNAL_TABLE1  !
create table CMP20_INTERNAL_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_INTERNAL_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_INTERNAL_TABLE2  !
create table CMP20_INTERNAL_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_INTERNAL_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_EXTERNAL_TABLE1  !
create table CMP20_EXTERNAL_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_EXTERNAL_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_EXTERNAL_TABLE2  !
create table CMP20_EXTERNAL_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_EXTERNAL_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_BMP_INTERNAL_TABLE1  !
create table CMP20_BMP_INTERNAL_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_BMP_INTERNAL_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_BMP_INTERNAL_TABLE2  !
create table CMP20_BMP_INTERNAL_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_BMP_INTERNAL_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_BMP_EXTERNAL_TABLE1  !
create table CMP20_BMP_EXTERNAL_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_BMP_EXTERNAL_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_BMP_EXTERNAL_TABLE2  !
create table CMP20_BMP_EXTERNAL_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_BMP_EXTERNAL_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table COMPAT11_TABLE1  !
create table COMPAT11_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint COMPAT11_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CASESENS_TABLE1  !
create table CASESENS_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CASESENS_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CASESENS_TABLE2  !
create table CASESENS_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CASESENS_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CASESENS_TABLE3  !
create table CASESENS_TABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CASESENS_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!  

drop table EJBLINK_SCOPE11_TABLE1  !
create table EJBLINK_SCOPE11_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBLINK_SCOPE11_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EJBLINK_SCOPE11_TABLE2  !
create table EJBLINK_SCOPE11_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBLINK_SCOPE11_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table EJBLINK1_SCOPE11_TABLE1  !
create table EJBLINK1_SCOPE11_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBLINK1_SCOPE11_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table EJBLINKCMP11INTERNALTABLE1  !
create table EJBLINKCMP11INTERNALTABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBLINKCMP11INTERNALTAB1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EJBLINKCMP11INTERNALTABLE2  !
create table EJBLINKCMP11INTERNALTABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBLINKCMP11INTERNALTAB2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EJBLINKCMP11INTERNALTABLE3  !
create table EJBLINKCMP11INTERNALTABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBLINKCMP11INTERNALTAB3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EJBLINKCMP11EXTERNALTABLE1  !
create table EJBLINKCMP11EXTERNALTABLE1( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBLINKCMP11EXTERNALTABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EJBLINKCMP11EXTERNALTABLE2  !
create table EJBLINKCMP11EXTERNALTABLE2( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBLINKCMP11EXTERNALTABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CASEBEANCMP11INTERNALTABLE1  !
create table CASEBEANCMP11INTERNALTABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CASEBEANCMP11INTERNALTABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CASEBEANCMP11INTERNALTABLE2  !
create table CASEBEANCMP11INTERNALTABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CASEBEANCMP11INTERNALTABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CASEBEANCMP11INTERNALTABLE3  !
create table CASEBEANCMP11INTERNALTABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CASEBEANCMP11INTERNALTABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP11_EJBREF_SCOPE_TABLE1  !
create table CMP11_EJBREF_SCOPE_TABLE1( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_EJBREF_SCOPE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_EJBREF_SCOPE_TABLE2  !
create table CMP11_EJBREF_SCOPE_TABLE2( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_EJBREF_SCOPE_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_EJBREF_SCOPE_TABLE3  !
create table CMP11_EJBREF_SCOPE_TABLE3( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_EJBREF_SCOPE_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_EJBREF_SCOPE_TABLE4  !
create table CMP11_EJBREF_SCOPE_TABLE4( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_EJBREF_SCOPE_TABLE4 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_EJBREF_SCOPE_TABLE5  !
create table CMP11_EJBREF_SCOPE_TABLE5( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_EJBREF_SCOPE_TABLE5 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!  

drop table CMP11_CYRANO_SCOPE_TABLE1  !
create table CMP11_CYRANO_SCOPE_TABLE1( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_CYRANO_SCOPE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_EJBREF_SINGLE_TABLE1  !
create table CMP11_EJBREF_SINGLE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_EJBREF_SINGLE_TABLE1  primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_EJBREF_SINGLE_TABLE2  !
create table CMP11_EJBREF_SINGLE_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_EJBREF_SINGLE_TABLE2  primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_EJBREF_SINGLE_TABLE3  !
create table CMP11_EJBREF_SINGLE_TABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_EJBREF_SINGLE_TABLE3  primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP11_EJBREF_SINGLE_TABLE4  !
create table CMP11_EJBREF_SINGLE_TABLE4 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_EJBREF_SINGLE_TABLE4  primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_EJBREF_SINGLE_TABLE5  !
create table CMP11_EJBREF_SINGLE_TABLE5 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_EJBREF_SINGLE_TABLE5  primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table ENV_CASEBEAN_TABLE1  !
create table ENV_CASEBEAN_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint ENV_CASEBEAN_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table ENV_CASEBEAN_SCOPE_TABLE1  !
create table ENV_CASEBEAN_SCOPE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint ENV_CASEBEAN_SCOPE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table ENV_CASEBEAN_SCOPE_TABLE2  !
create table ENV_CASEBEAN_SCOPE_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint ENV_CASEBEAN_SCOPE_TABLE2  primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table ENV_CASEBEAN_SCOPE_TABLE3  !
create table ENV_CASEBEAN_SCOPE_TABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint ENV_CASEBEAN_SCOPE_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table ENV_CASEBEAN_SCOPE_TABLE4  !
create table ENV_CASEBEAN_SCOPE_TABLE4 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint ENV_CASEBEAN_SCOPE_TABLE4 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP11_ENV_SINGLE_TABLE1  !
create table CMP11_ENV_SINGLE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_ENV_SINGLE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_ENV_SINGLE_TABLE2  !
create table CMP11_ENV_SINGLE_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_ENV_SINGLE_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_ENV_SINGLE_TABLE3  !
create table CMP11_ENV_SINGLE_TABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_ENV_SINGLE_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_ENV_SINGLE_TABLE4  !
create table CMP11_ENV_SINGLE_TABLE4 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_ENV_SINGLE_TABLE4 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_ENV_SINGLE_TABLE5  !
create table CMP11_ENV_SINGLE_TABLE5 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_ENV_SINGLE_TABLE5 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_ENV_SINGLE_TABLE6  !
create table CMP11_ENV_SINGLE_TABLE6 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_ENV_SINGLE_TABLE6 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_ENV_SINGLE_TABLE7  !
create table CMP11_ENV_SINGLE_TABLE7 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_ENV_SINGLE_TABLE7 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_ENV_SINGLE_TABLE8  !
create table CMP11_ENV_SINGLE_TABLE8 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_ENV_SINGLE_TABLE8 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_ENV_SINGLE_TABLE9  !
create table CMP11_ENV_SINGLE_TABLE9 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_ENV_SINGLE_TABLE9 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_ENV_SINGLE_TABLE10  !
create table CMP11_ENV_SINGLE_TABLE10 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_ENV_SINGLE_TABLE10 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP11_STYLE1_TABLE1  !
create table CMP11_STYLE1_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_STYLE1_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_STYLE1_TABLE2  !
create table CMP11_STYLE1_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_STYLE1_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP11_STYLE2_TABLE1  !
create table CMP11_STYLE2_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_STYLE2_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP11_STYLE3_TABLE1  !
create table CMP11_STYLE3_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_STYLE3_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP11PK_TABLE1  !
create table CMP11PK_TABLE1 ( cmpID varchar(25), cmpBrandName  varchar(25), cmpPrice float, constraint CMP11PK_TABLE1 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11PK_TABLE2  !
create table CMP11PK_TABLE2 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP11PK_TABLE2 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11PK_TABLE3  !
create table CMP11PK_TABLE3 ( cmpID float(3,1), cmpBrandName  varchar(25), cmpPrice float, constraint CMP11PK_TABLE3 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11PK_TABLE4  !
create table CMP11PK_TABLE4( pmIDInteger INTEGER, pmIDString  varchar(25), pmIDFloat  float(3,1), CMPBRANDNAME VARCHAR(25), CMPPRICE float, constraint CMP11PK_TABLE4  primary key(pmIDInteger,pmIDString,pmIDFloat))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_RESREF_CASESENS_TABLE1  !
create table CMP11_RESREF_CASESENS_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_RESREF_CASESENS_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP11_RESREF_CASESENS_TABLE2  !
create table CMP11_RESREF_CASESENS_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_RESREF_CASESENS_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_RESREF_CASESENS_TABLE3  !
create table CMP11_RESREF_CASESENS_TABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_RESREF_CASESENS_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table RESREF_SINGLE_TABLE1  !
create table RESREF_SINGLE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint RESREF_SINGLE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1 !  

drop table CMP11_DEP_SINGLE_TABLE1  !
create table CMP11_DEP_SINGLE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP11_DEP_SINGLE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table DEPCMP20ELINCASESENSTABLE1  !
create table DEPCMP20ELINCASESENSTABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint DEPCMP20ELINCASESENSTAB1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table DEPCMP20ELINCASESENSTABLE2  !
create table DEPCMP20ELINCASESENSTABLE2( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint DEPCMP20ELINCASESENSTAB2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table DEPCMP20ELINCASESENSTABLE3  !
create table DEPCMP20ELINCASESENSTABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint DEPCMP20ELINCASESENSTAB3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_EJBLINK_SCOPE_TABLE1  !
create table CMP20_EJBLINK_SCOPE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_EJBLINK_SCOPE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_EJBLINK_SCOPE_TABLE2  !
create table CMP20_EJBLINK_SCOPE_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_EJBLINK_SCOPE_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_EJBLINK_SCOPE2_TABLE1  !
create table CMP20_EJBLINK_SCOPE2_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_EJBLINK_SCOPE2_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_EJBLINK_SINGLE_TABLE1  !
create table CMP20_EJBLINK_SINGLE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_EJBLINK_SINGLE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_EJBLINK_SINGLE_TABLE2  !
create table CMP20_EJBLINK_SINGLE_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_EJBLINK_SINGLE_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_EJBLINK_SINGLE_TABLE3  !
create table CMP20_EJBLINK_SINGLE_TABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_EJBLINK_SINGLE_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_EJBLINK_SINGLE_TABLE4  !
create table CMP20_EJBLINK_SINGLE_TABLE4 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_EJBLINK_SINGLE_TABLE4 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_EJBLINK_SINGLE_TABLE5  !
create table CMP20_EJBLINK_SINGLE_TABLE5 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_EJBLINK_SINGLE_TABLE5 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table DEPCMP20EREFCASESENSTABLE1  !
create table DEPCMP20EREFCASESENSTABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint DEPCMP20EREFCASESENSTABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table DEPCMP20EREFCASESENSTABLE2  !
create table DEPCMP20EREFCASESENSTABLE2( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint DEPCMP20EREFCASESENSTABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table DEPCMP20EREFCASESENSTABLE3  !
create table DEPCMP20EREFCASESENSTABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint DEPCMP20EREFCASESENSTABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table EJBREF_SCOPE_TABLE1  !
create table EJBREF_SCOPE_TABLE1( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBREF_SCOPE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EJBREF_SCOPE_TABLE2  !
create table EJBREF_SCOPE_TABLE2( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBREF_SCOPE_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EJBREF_SCOPE_TABLE3  !
create table EJBREF_SCOPE_TABLE3( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBREF_SCOPE_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EJBREF_SCOPE_TABLE4  !
create table EJBREF_SCOPE_TABLE4( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBREF_SCOPE_TABLE4 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EJBREF_SCOPE_TABLE5  !
create table EJBREF_SCOPE_TABLE5( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBREF_SCOPE_TABLE5 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!  

drop table EJBREF_SCOPE1_TABLE1  !
create table EJBREF_SCOPE1_TABLE1( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EJBREF_SCOPE1_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20INTERNAL_TABLE1  !
create table CMP20INTERNAL_TABLE1 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20INTERNAL_TABLE1 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20INTERNAL_TABLE2  !
create table CMP20INTERNAL_TABLE2 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20INTERNAL_TABLE2 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20INTERNAL_TABLE3  !
create table CMP20INTERNAL_TABLE3 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20INTERNAL_TABLE3 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20EXTERNAL_TABLE1  !
create table CMP20EXTERNAL_TABLE1 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20EXTERNAL_TABLE1 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20EXTERNAL_TABLE2  !
create table CMP20EXTERNAL_TABLE2 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20EXTERNAL_TABLE2 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_ENV_CASEBEAN_TABLE1  !
create table CMP20_ENV_CASEBEAN_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ENV_CASEBEAN_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table BEAN1_TABLE1  !
create table BEAN1_TABLE1 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint BEAN1_TABLE1 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEAN2_TABLE2  !
create table BEAN2_TABLE2 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint BEAN2_TABLE2 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table MULTJAR_BEAN1_TABLE1  !
create table MULTJAR_BEAN1_TABLE1( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint MULTJAR_BEAN1_TABLE1 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table MULTJAR1_BEAN1_TABLE1  !
create table MULTJAR1_BEAN1_TABLE1( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint MULTJAR1_BEAN1_TABLE1 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_ENV_SINGLE_TABLE1  !
create table CMP20_ENV_SINGLE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ENV_SINGLE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ENV_SINGLE_TABLE2  !
create table CMP20_ENV_SINGLE_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ENV_SINGLE_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ENV_SINGLE_TABLE3  !
create table CMP20_ENV_SINGLE_TABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ENV_SINGLE_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ENV_SINGLE_TABLE4  !
create table CMP20_ENV_SINGLE_TABLE4 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ENV_SINGLE_TABLE4 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ENV_SINGLE_TABLE5  !
create table CMP20_ENV_SINGLE_TABLE5 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ENV_SINGLE_TABLE5 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ENV_SINGLE_TABLE6  !
create table CMP20_ENV_SINGLE_TABLE6 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ENV_SINGLE_TABLE6 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!


drop table CMP20_ENV_SINGLE_TABLE7  !
create table CMP20_ENV_SINGLE_TABLE7 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ENV_SINGLE_TABLE7 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ENV_SINGLE_TABLE8  !
create table CMP20_ENV_SINGLE_TABLE8 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ENV_SINGLE_TABLE8 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ENV_SINGLE_TABLE9  !
create table CMP20_ENV_SINGLE_TABLE9 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ENV_SINGLE_TABLE9 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_ENV_SINGLE_TABLE10  !
create table CMP20_ENV_SINGLE_TABLE10 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_ENV_SINGLE_TABLE10 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table DEP_CMP20_SEC_STYLE1_TABLE1  !
create table DEP_CMP20_SEC_STYLE1_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint DEP_CMP20_SEC_STYLE1_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table DEP_CMP20_SEC_STYLE1_TABLE2  !
create table DEP_CMP20_SEC_STYLE1_TABLE2( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint DEP_CMP20_SEC_STYLE1_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_SEC_STYLE_TABLE1  !
create table CMP20_SEC_STYLE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_SEC_STYLE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

   
drop table CMP20_SEC_STYLE_TABLE2  !
create table CMP20_SEC_STYLE_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_SEC_STYLE_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

   
drop table CMP20_DEP_PKEY_TABLE1  !
create table CMP20_DEP_PKEY_TABLE1( KEY_ID  numeric, BRAND_NAME  varchar(25), PRICE  float, constraint CMP20_DEP_PKEY_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_DEP_PKEY_TABLE2  !
create table CMP20_DEP_PKEY_TABLE2( KEY_ID  FLOAT(3,1), BRAND_NAME  varchar(25), PRICE  float, constraint CMP20_DEP_PKEY_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_DEP_PKEY_TABLE3  !
create table CMP20_DEP_PKEY_TABLE3( KEY_ID varchar(50), BRAND_NAME  varchar(25), PRICE  float, constraint CMP20_DEP_PKEY_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_DEP_PKEY_TABLE4  !
create table CMP20_DEP_PKEY_TABLE4( pmIDInteger INTEGER, pmIDString  varchar(25), pmIDFloat  float(3,1), BRANDNAME VARCHAR(25), PRICE float, constraint CMP20_DEP_PKEY_TABLE4 primary key(pmIDInteger,pmIDString,pmIDFloat))  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table CMP20_RESREF_CSENS_TABLE1  !
create table CMP20_RESREF_CSENS_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_RESREF_CSENS_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

   
drop table CMP20_RESREF_SCOPE_TABLE1  !
create table CMP20_RESREF_SCOPE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_RESREF_SCOPE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_RESREF_SCOPE_TABLE2  !
create table CMP20_RESREF_SCOPE_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_RESREF_SCOPE_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_RESREF_SINGLE_TABLE1  !
create table CMP20_RESREF_SINGLE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_RESREF_SINGLE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_DEP_SINGLE_TABLE1  !
create table CMP20_DEP_SINGLE_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_DEP_SINGLE_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_MDB_EJBLINK_TABLE1  !
create table CMP20_MDB_EJBLINK_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_MDB_EJBLINK_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_MDB_EJBLINK_TABLE2  !
create table CMP20_MDB_EJBLINK_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_MDB_EJBLINK_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!


   
drop table CMP20_MDB_EJBLINK_TABLE3  !
create table CMP20_MDB_EJBLINK_TABLE3 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_MDB_EJBLINK_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_MDB_EJBLINK_TABLE4  !
create table CMP20_MDB_EJBLINK_TABLE4 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint CMP20_MDB_EJBLINK_TABLE4 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

   
drop table CMP20_MDB_INTERNAL_TABLE1  !
create table CMP20_MDB_INTERNAL_TABLE1 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20_MDB_INTERNAL_TABLE1 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_MDB_INTERNAL_TABLE2  !
create table CMP20_MDB_INTERNAL_TABLE2 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20_MDB_INTERNAL_TABLE2 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_MDB_EXTERNAL_TABLE1  !
create table CMP20_MDB_EXTERNAL_TABLE1 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20_MDB_EXTERNAL_TABLE1 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_MDB_EXTERNAL_TABLE2  !
create table CMP20_MDB_EXTERNAL_TABLE2 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20_MDB_EXTERNAL_TABLE2 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

   
drop table CMP20_MDBT_EJBLINK_TABLE1  !
create table CMP20_MDBT_EJBLINK_TABLE1 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20_MDBT_EJBLINK_TABLE1 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_MDBT_EJBLINK_TABLE2  !
create table CMP20_MDBT_EJBLINK_TABLE2 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20_MDBT_EJBLINK_TABLE2 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_MDBT_EJBLINK_TABLE3  !
create table CMP20_MDBT_EJBLINK_TABLE3 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20_MDBT_EJBLINK_TABLE3 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_MDBT_EJBLINK_TABLE4  !
create table CMP20_MDBT_EJBLINK_TABLE4 ( cmpID INTEGER, cmpBrandName  varchar(25), cmpPrice float, constraint CMP20_MDBT_EJBLINK_TABLE4 primary key(cmpID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_DEPSSF_EJBLINK_TABLE1  !
create table CMP20_DEPSSF_EJBLINK_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_DEPSSF_EJBLINK_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_DEPSSF_EJBLINK_TABLE2  !
create table CMP20_DEPSSF_EJBLINK_TABLE2 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_DEPSSF_EJBLINK_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_DEPSSF_EJBLINK_TABLE3  !
create table CMP20_DEPSSF_EJBLINK_TABLE3 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_DEPSSF_EJBLINK_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_DEPSSF_EJBLINK_TABLE4  !
create table CMP20_DEPSSF_EJBLINK_TABLE4 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_DEPSSF_EJBLINK_TABLE4 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP11_STATEFUL_TABLE1  !
create table CMP11_STATEFUL_TABLE1 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP11_STATEFUL_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_STATEFUL_TABLE2  !
create table CMP11_STATEFUL_TABLE2 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP11_STATEFUL_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP11_STATEFUL_TABLE3  !
create table CMP11_STATEFUL_TABLE3 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP11_STATEFUL_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP11_STATEFUL_TABLE4  !
create table CMP11_STATEFUL_TABLE4 ( ID  INTEGER, BRANDNAME  varchar(25), PRICE  FLOAT, constraint CMP11_STATEFUL_TABLE4 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_DEPSSL_EJBLINK_TABLE1  !
create table CMP20_DEPSSL_EJBLINK_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_DEPSSL_EJBLINK_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_DEPSSL_EJBLINK_TABLE2  !
create table CMP20_DEPSSL_EJBLINK_TABLE2 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_DEPSSL_EJBLINK_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

   
drop table CMP20_DEPSSL_EJBLINK_TABLE3  !
create table CMP20_DEPSSL_EJBLINK_TABLE3 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_DEPSSL_EJBLINK_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_DEPSSL_EJBLINK_TABLE4  !
create table CMP20_DEPSSL_EJBLINK_TABLE4 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_DEPSSL_EJBLINK_TABLE4 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_DEPSSL_EJBREF_TABLE1  !
create table CMP20_DEPSSL_EJBREF_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_DEPSSL_EJBREF_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_DEPSSL_EJBREF_TABLE2  !
create table CMP20_DEPSSL_EJBREF_TABLE2 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_DEPSSL_EJBREF_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

   
drop table CMP20_DEPSSL_EJBREF_TABLE3  !
create table CMP20_DEPSSL_EJBREF_TABLE3 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_DEPSSL_EJBREF_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_DEPSSL_EJBREF_TABLE4  !
create table CMP20_DEPSSL_EJBREF_TABLE4 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_DEPSSL_EJBREF_TABLE4 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_EE_TX_MANDATORY_TABLE1  !
create table CMP20_EE_TX_MANDATORY_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  FLOAT, constraint CMP20_EE_TX_MANDATORY_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_EE_TX_MANDATORY_TABLE2  !
create table CMP20_EE_TX_MANDATORY_TABLE2 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  FLOAT, constraint CMP20_EE_TX_MANDATORY_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_EE_TX_MANDATORY_TABLE4  !
create table CMP20_EE_TX_MANDATORY_TABLE4 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  FLOAT, constraint CMP20_EE_TX_MANDATORY_TABLE4 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
 
drop table EE_TX_COMMON_TABLE1  !
create table EE_TX_COMMON_TABLE1 ( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EE_TX_COMMON_TABLE1 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EE_TX_COMMON_TABLE2  !
create table EE_TX_COMMON_TABLE2( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EE_TX_COMMON_TABLE2 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table EE_TX_COMMON_TABLE3  !
create table EE_TX_COMMON_TABLE3( KEY_ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint EE_TX_COMMON_TABLE3 primary key(KEY_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table BEANEJB_1X1_BI_BTOB  !
create TABLE BEANEJB_1X1_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1X1_BI_BTOB VARCHAR(255), FK2_FOR_AEJB_1X1_BI_BTOB VARCHAR(255), FK1_FOR_BEJB_1X1_BI_BTOB VARCHAR(255), FK2_FOR_BEJB_1X1_BI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1X1_BI_BTOB  !
create TABLE  AEJB_1X1_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1X1_BI_BTOB  !
create TABLE BEJB_1X1_BI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1X1_BI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1X1_BI_BTOB add ( constraint FK1_FOR_AEJB_1X1_BI_BTOB Foreign Key (FK1_FOR_AEJB_1X1_BI_BTOB) references AEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_BI_BTOB add ( constraint FK2_FOR_AEJB_1X1_BI_BTOB Foreign Key (FK2_FOR_AEJB_1X1_BI_BTOB) references AEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_BI_BTOB add ( constraint FK1_FOR_BEJB_1X1_BI_BTOB Foreign Key (FK1_FOR_BEJB_1X1_BI_BTOB) references BEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_BI_BTOB add ( constraint FK2_FOR_BEJB_1X1_BI_BTOB Foreign Key (FK2_FOR_BEJB_1X1_BI_BTOB) references BEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEJB_1X1_BI_BTOB add ( constraint FK_FOR_AEJB_1X1_BI_BTOB Foreign Key (FK_FOR_AEJB_1X1_BI_BTOB) references AEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !
   
drop table BEANEJB_1X1_BI_CASCADE  !
create TABLE BEANEJB_1X1_BI_CASCADE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255), FK2_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255), FK1_FOR_BEJB_1X1_BI_CASCADE VARCHAR(255), FK2_FOR_BEJB_1X1_BI_CASCADE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1X1_BI_CASCADE  !
create TABLE  AEJB_1X1_BI_CASCADE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1X1_BI_CASCADE  !
create TABLE BEJB_1X1_BI_CASCADE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1X1_BI_CASCADE add ( constraint FK1_FOR_AEJB_1X1_BI_CASCADE Foreign Key (FK1_FOR_AEJB_1X1_BI_CASCADE) references AEJB_1X1_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add ( constraint FK2_FOR_AEJB_1X1_BI_CASCADE Foreign Key (FK2_FOR_AEJB_1X1_BI_CASCADE) references AEJB_1X1_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add ( constraint FK1_FOR_BEJB_1X1_BI_CASCADE Foreign Key (FK1_FOR_BEJB_1X1_BI_CASCADE) references BEJB_1X1_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add ( constraint FK2_FOR_BEJB_1X1_BI_CASCADE Foreign Key (FK2_FOR_BEJB_1X1_BI_CASCADE) references BEJB_1X1_BI_CASCADE(id)) !


ALTER TABLE BEJB_1X1_BI_CASCADE add ( constraint FK_FOR_AEJB_1X1_BI_CASCADE Foreign Key (FK_FOR_AEJB_1X1_BI_CASCADE) references AEJB_1X1_BI_CASCADE(id)) !
   
drop table TABLER5_DELETE  !
create TABLE TABLER5_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_TABLER6_DELETE_ID VARCHAR(255), FK2_FOR_TABLER6_DELETE_ID VARCHAR(255), FK1_FOR_TABLER7_DELETE_ID VARCHAR(255), FK2_FOR_TABLER7_DELETE_ID VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table TABLER6_DELETE  !
create TABLE  TABLER6_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    

drop table TABLER7_DELETE  !
create TABLE TABLER7_DELETE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_TABLER6_DELETE_ID VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE TABLER5_DELETE add ( constraint FK1_FOR_TABLER6_DELETE_ID Foreign Key (FK1_FOR_TABLER6_DELETE_ID) references TABLER6_DELETE(id)) !

ALTER TABLE TABLER5_DELETE add ( constraint FK2_FOR_TABLER6_DELETE_ID Foreign Key (FK2_FOR_TABLER6_DELETE_ID) references TABLER6_DELETE(id)) !

ALTER TABLE TABLER5_DELETE add ( constraint FK1_FOR_TABLER7_DELETE_ID Foreign Key (FK1_FOR_TABLER7_DELETE_ID) references TABLER7_DELETE(id)) !

ALTER TABLE TABLER5_DELETE add ( constraint FK2_FOR_TABLER7_DELETE_ID Foreign Key (FK2_FOR_TABLER7_DELETE_ID) references TABLER7_DELETE(id)) !


ALTER TABLE TABLER7_DELETE add ( constraint FK_FOR_TABLER6_DELETE_ID Foreign Key (FK_FOR_TABLER6_DELETE_ID) references TABLER6_DELETE(id)) !
   
drop table BEANEJB_1X1_UNI_BTOB  !
create TABLE BEANEJB_1X1_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255), FK2_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255), FK1_FOR_BEJB_1X1_UNI_BTOB VARCHAR(255), FK2_FOR_BEJB_1X1_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1X1_UNI_BTOB  !
create TABLE  AEJB_1X1_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1X1_UNI_BTOB  !
create TABLE BEJB_1X1_UNI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1X1_UNI_BTOB add ( constraint FK1_FOR_AEJB_1X1_UNI_BTOB Foreign Key (FK1_FOR_AEJB_1X1_UNI_BTOB) references AEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_UNI_BTOB add ( constraint FK2_FOR_AEJB_1X1_UNI_BTOB Foreign Key (FK2_FOR_AEJB_1X1_UNI_BTOB) references AEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_UNI_BTOB add ( constraint FK1_FOR_BEJB_1X1_UNI_BTOB Foreign Key (FK1_FOR_BEJB_1X1_UNI_BTOB) references BEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_UNI_BTOB add ( constraint FK2_FOR_BEJB_1X1_UNI_BTOB Foreign Key (FK2_FOR_BEJB_1X1_UNI_BTOB) references BEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEJB_1X1_UNI_BTOB add ( constraint FK_FOR_AEJB_1X1_UNI_BTOB Foreign Key (FK_FOR_AEJB_1X1_UNI_BTOB) references AEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !

drop table BEANEJB_1XM_BI_BTOB  !
create TABLE BEANEJB_1XM_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1XM_BI_BTOB VARCHAR(255), FK2_FOR_AEJB_1XM_BI_BTOB VARCHAR(255), FK1_FOR_BEJB_1XM_BI_BTOB VARCHAR(255), FK2_FOR_BEJB_1XM_BI_BTOB VARCHAR(255), FK3_FOR_BEJB_1XM_BI_BTOB VARCHAR(255), FK4_FOR_BEJB_1XM_BI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1XM_BI_BTOB  !
create TABLE  AEJB_1XM_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEJB_1XM_BI_BTOB  !
create TABLE BEJB_1XM_BI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1XM_BI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
     

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK1_FOR_AEJB_1XM_BI_BTOB Foreign Key (FK1_FOR_AEJB_1XM_BI_BTOB) references AEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK2_FOR_AEJB_1XM_BI_BTOB Foreign Key (FK2_FOR_AEJB_1XM_BI_BTOB) references AEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK1_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK1_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK2_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK2_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK3_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK3_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK4_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK4_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEJB_1XM_BI_BTOB add ( constraint FK_FOR_AEJB_1XM_BI_BTOB Foreign Key (FK_FOR_AEJB_1XM_BI_BTOB) references AEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !
   
drop table BEANEJB_1XM_BI_CASCADE  !
create TABLE BEANEJB_1XM_BI_CASCADE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255), FK2_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255), FK1_FOR_BEJB_1XM_BI_CASCADE VARCHAR(255), FK2_FOR_BEJB_1XM_BI_CASCADE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1XM_BI_CASCADE  !
create TABLE  AEJB_1XM_BI_CASCADE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1XM_BI_CASCADE  !
create TABLE BEJB_1XM_BI_CASCADE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
     

ALTER TABLE BEANEJB_1XM_BI_CASCADE add ( constraint FK1_FOR_AEJB_1XM_BI_CASCADE Foreign Key (FK1_FOR_AEJB_1XM_BI_CASCADE) references AEJB_1XM_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1XM_BI_CASCADE add ( constraint FK2_FOR_AEJB_1XM_BI_CASCADE Foreign Key (FK2_FOR_AEJB_1XM_BI_CASCADE) references AEJB_1XM_BI_CASCADE(id)) !



ALTER TABLE BEANEJB_1XM_BI_CASCADE add ( constraint FK1_FOR_BEJB_1XM_BI_CASCADE Foreign Key (FK1_FOR_BEJB_1XM_BI_CASCADE) references BEJB_1XM_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1XM_BI_CASCADE add ( constraint FK2_FOR_BEJB_1XM_BI_CASCADE Foreign Key (FK2_FOR_BEJB_1XM_BI_CASCADE) references BEJB_1XM_BI_CASCADE(id)) !

ALTER TABLE BEJB_1XM_BI_CASCADE add ( constraint FK_FOR_AEJB_1XM_BI_CASCADE Foreign Key (FK_FOR_AEJB_1XM_BI_CASCADE) references AEJB_1XM_BI_CASCADE(id)) !
   
drop table BEANEJB_1XM_BI_DELETE  !
create TABLE BEANEJB_1XM_BI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1XM_BI_DELETE VARCHAR(255), FK2_FOR_AEJB_1XM_BI_DELETE VARCHAR(255), FK1_FOR_BEJB_1XM_BI_DELETE VARCHAR(255), FK2_FOR_BEJB_1XM_BI_DELETE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_1XM_BI_DELETE  !
create TABLE  AEJB_1XM_BI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEJB_1XM_BI_DELETE  !
create TABLE BEJB_1XM_BI_DELETE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1XM_BI_DELETE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1XM_BI_DELETE add ( constraint FK1_FOR_AEJB_1XM_BI_DELETE Foreign Key (FK1_FOR_AEJB_1XM_BI_DELETE) references AEJB_1XM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_1XM_BI_DELETE add ( constraint FK2_FOR_AEJB_1XM_BI_DELETE Foreign Key (FK2_FOR_AEJB_1XM_BI_DELETE) references AEJB_1XM_BI_DELETE(id)) !


ALTER TABLE BEANEJB_1XM_BI_DELETE add ( constraint FK1_FOR_BEJB_1XM_BI_DELETE Foreign Key (FK1_FOR_BEJB_1XM_BI_DELETE) references BEJB_1XM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_1XM_BI_DELETE add ( constraint FK2_FOR_BEJB_1XM_BI_DELETE Foreign Key (FK2_FOR_BEJB_1XM_BI_DELETE) references BEJB_1XM_BI_DELETE(id)) !


ALTER TABLE BEJB_1XM_BI_DELETE add ( constraint FK_FOR_AEJB_1XM_BI_DELETE Foreign Key (FK_FOR_AEJB_1XM_BI_DELETE) references AEJB_1XM_BI_DELETE(id)) !
   
drop table BEANEJB_1XM_UNI_BTOB  !
create TABLE BEANEJB_1XM_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255), FK2_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255), FK1_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255), FK2_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255), FK3_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255), FK4_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_1XM_UNI_BTOB  !
create TABLE  AEJB_1XM_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1XM_UNI_BTOB  !
create TABLE BEJB_1XM_UNI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK1_FOR_AEJB_1XM_UNI_BTOB Foreign Key (FK1_FOR_AEJB_1XM_UNI_BTOB) references AEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK2_FOR_AEJB_1XM_UNI_BTOB Foreign Key (FK2_FOR_AEJB_1XM_UNI_BTOB) references AEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK1_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK1_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK2_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK2_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK3_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK3_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK4_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK4_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEJB_1XM_UNI_BTOB add ( constraint FK_FOR_AEJB_1XM_UNI_BTOB Foreign Key (FK_FOR_AEJB_1XM_UNI_BTOB) references AEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !
   
drop table BEANEJB_MX1_UNI_BTOB  !
create TABLE BEANEJB_MX1_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255), FK2_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255), FK1_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255), FK2_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255), FK3_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255), FK4_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_MX1_UNI_BTOB  !
create TABLE  AEJB_MX1_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEJB_MX1_UNI_BTOB  !
create TABLE BEJB_MX1_UNI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK1_FOR_AEJB_MX1_UNI_BTOB Foreign Key (FK1_FOR_AEJB_MX1_UNI_BTOB) references AEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK2_FOR_AEJB_MX1_UNI_BTOB Foreign Key (FK2_FOR_AEJB_MX1_UNI_BTOB) references AEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK1_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK1_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK2_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK2_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK3_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK3_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK4_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK4_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEJB_MX1_UNI_BTOB add ( constraint FK_FOR_AEJB_MX1_UNI_BTOB Foreign Key (FK_FOR_AEJB_MX1_UNI_BTOB) references AEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

drop table BEANEJB_MX1_UNI_DELETE  !
create TABLE BEANEJB_MX1_UNI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255) , FK2_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255) , FK1_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK2_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK3_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK4_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_MX1_UNI_DELETE  !
create TABLE  AEJB_MX1_UNI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_MX1_UNI_DELETE  !
create TABLE BEJB_MX1_UNI_DELETE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK1_FOR_AEJB_MX1_UNI_DELETE Foreign Key (FK1_FOR_AEJB_MX1_UNI_DELETE) references AEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK2_FOR_AEJB_MX1_UNI_DELETE Foreign Key (FK2_FOR_AEJB_MX1_UNI_DELETE) references AEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK1_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK1_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK2_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK2_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(id)) !


ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK3_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK3_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK4_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK4_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEJB_MX1_UNI_DELETE add ( constraint FK_FOR_AEJB_MX1_UNI_DELETE Foreign Key (FK_FOR_AEJB_MX1_UNI_DELETE) references AEJB_MX1_UNI_DELETE(id)) !
   
drop table BEANEJB_MXM_BI_BTOB  !
create TABLE BEANEJB_MXM_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK2_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK3_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK4_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK1_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK2_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK3_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK4_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_MXM_BI_BTOB  !
create TABLE  AEJB_MXM_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_MXM_BI_BTOB  !
create TABLE BEJB_MXM_BI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table FKEYS_MXM_BI_BTOB  !
create TABLE FKEYS_MXM_BI_BTOB ( FK_FOR_AEJB_MXM_BI_BTOB  VARCHAR(255), FK_FOR_BEJB_MXM_BI_BTOB  VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!    

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK1_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK1_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK2_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK2_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK3_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK3_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK4_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK4_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK1_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK1_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK2_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK2_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK3_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK3_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK4_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK4_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE FKEYS_MXM_BI_BTOB add ( constraint FK_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE FKEYS_MXM_BI_BTOB add ( constraint FK_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !
   
drop table BEANEJB_MXM_BI_DELETE  !
create TABLE BEANEJB_MXM_BI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK2_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK3_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK4_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK1_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK2_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK3_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK4_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_MXM_BI_DELETE  !
create TABLE  AEJB_MXM_BI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_MXM_BI_DELETE  !
create TABLE BEJB_MXM_BI_DELETE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL )  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table FKEYS_MXM_BI_DELETE  !
create TABLE FKEYS_MXM_BI_DELETE ( FK_FOR_AEJB_MXM_BI_DELETE  VARCHAR(255), FK_FOR_BEJB_MXM_BI_DELETE  VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!    

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK1_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK1_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK2_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK2_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK3_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK3_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK4_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK4_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !


ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK1_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK1_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK2_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK2_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK3_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK3_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK4_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK4_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !

ALTER TABLE FKEYS_MXM_BI_DELETE add ( constraint FK_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !

ALTER TABLE FKEYS_MXM_BI_DELETE add ( constraint FK_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !
   
drop table BEANEJB_MXM_UNI_BTOB  !
create TABLE BEANEJB_MXM_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK2_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK3_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK4_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK1_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK2_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK3_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK4_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_MXM_UNI_BTOB  !
create TABLE  AEJB_MXM_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEJB_MXM_UNI_BTOB  !
create TABLE BEJB_MXM_UNI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table FKEYS_MXM_UNI_BTOB  !
create TABLE FKEYS_MXM_UNI_BTOB ( FK_FOR_AEJB_MXM_UNI_BTOB  VARCHAR(255), FK_FOR_BEJB_MXM_UNI_BTOB  VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK1_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK1_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK2_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK2_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK3_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK3_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK4_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK4_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK1_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK1_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK2_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK2_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK3_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK3_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK4_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK4_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE FKEYS_MXM_UNI_BTOB add ( constraint FK_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE FKEYS_MXM_UNI_BTOB add ( constraint FK_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !
   
drop table CMP20_LSECP_TABLE1  !
create table CMP20_LSECP_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_LSECP_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_LSECP_TABLE2  !
create table CMP20_LSECP_TABLE2  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_LSECP_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_LSECP_TABLE3  !
create table CMP20_LSECP_TABLE3  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_LSECP_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_LSECR_TABLE1  !
create table CMP20_LSECR_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_LSECR_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_LSECR_TABLE2  !
create table CMP20_LSECR_TABLE2  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_LSECR_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_LSECR_TABLE3  !
create table CMP20_LSECR_TABLE3  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_LSECR_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_SEC_TABLE1  !
create table CMP20_SEC_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_SEC_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_SEC_TABLE2  !
create table CMP20_SEC_TABLE2  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_SEC_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_SECP_TABLE1  !
create table CMP20_SECP_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_SECP_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_SECP_TABLE2  !
create table CMP20_SECP_TABLE2  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_SECP_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_SECP_TABLE3  !
create table CMP20_SECP_TABLE3  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_SECP_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

   
drop table CMP_SEC_TABLE1  !
create table CMP_SEC_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP_SEC_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP_SEC_TABLE2  !
create table CMP_SEC_TABLE2  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP_SEC_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP_SECP_TABLE1  !
create table CMP_SECP_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP_SECP_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP_SECP_TABLE2  !
create table CMP_SECP_TABLE2  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP_SECP_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP_SECP_TABLE3  !
create table CMP_SECP_TABLE3  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP_SECP_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table CMP20_SECRASP_TABLE1  !
create table CMP20_SECRASP_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_SECRASP_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_SECRASP_TABLE2  !
create table CMP20_SECRASP_TABLE2  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_SECRASP_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_SECRASP_TABLE3  !
create table CMP20_SECRASP_TABLE3  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP20_SECRASP_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP_SECRASP_TABLE1  !
create table CMP_SECRASP_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP_SECRASP_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP_SECRASP_TABLE2  !
create table CMP_SECRASP_TABLE2  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP_SECRASP_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP_SECRASP_TABLE3  !
create table CMP_SECRASP_TABLE3  ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint CMP_SECRASP_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table TXRN_CMP_TABLE1  !
create table TXRN_CMP_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint TXRN_CMP_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table TXR_CMP_TABLE1  !
create table TXR_CMP_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint TXR_CMP_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table TXR_BMCMP_TABLE1  !
create table TXR_BMCMP_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint TXR_BMCMP_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table TXR_BMCMP_TABLE2  !
create table TXR_BMCMP_TABLE2 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint TXR_BMCMP_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
   
drop table TXR_PMCMP_TABLE1  !
create table TXR_PMCMP_TABLE1 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint TXR_PMCMP_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table TXR_PMCMP_TABLE2  !
create table TXR_PMCMP_TABLE2 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint TXR_PMCMP_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table TXR_PMCMP_TABLE3  !
create table TXR_PMCMP_TABLE3 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint TXR_PMCMP_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table TXR_PMCMP_TABLE4  !
create table TXR_PMCMP_TABLE4 ( ID INTEGER, Brand_Name  varchar(25), Price float, constraint TXR_PMCMP_TABLE4 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!


drop table TIMER_TABLE1  !
create TABLE TIMER_TABLE1 (KEY_ID INTEGER NOT NULL,  BRAND_NAME VARCHAR(255), PRICE REAL NOT NULL, CONSTRAINT TIMER_TABLE1 PRIMARY KEY (KEY_ID) )  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table TIMER_FLAGSTORE  !
create TABLE TIMER_FLAGSTORE (KEY_ID INTEGER NOT NULL, BRAND_NAME VARCHAR(255) , PRICE REAL NOT NULL , REQUIRESNEWACCESSED SMALLINT NOT NULL, REQUIREDACCESSED SMALLINT NOT NULL , CONSTRAINT TIMER_FLAGSTORE PRIMARY KEY (KEY_ID) )  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_JACC_TABLE1  !
create TABLE CMP20_JACC_TABLE1 (ARG1 VARCHAR(255) NOT NULL, ARG2 INTEGER NOT NULL,  ARG3 INTEGER NOT NULL, CONSTRAINT CMP20_JACC_TABLE1 PRIMARY KEY (ARG1,ARG2,ARG3) )  ENGINE=innoDB DEFAULT CHARSET=latin1!


drop table CMP20_APPCLIENT_TABLE1  !
create table CMP20_APPCLIENT_TABLE1( id  INTEGER, brandname  varchar(25), price  float, constraint CMP20_APPCLIENT_TABLE1 primary key(id))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_APPCLIENT_TABLE2  !
create table CMP20_APPCLIENT_TABLE2( id  INTEGER, brandname  varchar(25), price  float, constraint CMP20_APPCLIENT_TABLE2 primary key(id))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_APPCLIENT_TABLE3  !
create table CMP20_APPCLIENT_TABLE3( id  INTEGER, brandname  varchar(25), price  float, constraint CMP20_APPCLIENT_TABLE3 primary key(id))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CMP20_APPCLIENT_TABLE4  !
create table CMP20_APPCLIENT_TABLE4( id  INTEGER, brandname  varchar(25), price  float, constraint CMP20_APPCLIENT_TABLE4 primary key(id))  ENGINE=innoDB DEFAULT CHARSET=latin1!


drop table SERVLET_DEPLOY_TABLE3  !
create table SERVLET_DEPLOY_TABLE3 ( ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint SERVLET_DEPLOY_TABLE3 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table SERVLET_DEPLOY_TABLE4  !
create table SERVLET_DEPLOY_TABLE4 ( ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint SERVLET_DEPLOY_TABLE4 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
  
drop table SERVLET_DEPLOY_TABLE1  !
create table SERVLET_DEPLOY_TABLE1 ( ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint SERVLET_DEPLOY_TABLE1 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table SERVLET_DEPLOY_TABLE2  !
create table SERVLET_DEPLOY_TABLE2 ( ID  INTEGER, BRAND_NAME  varchar(25), PRICE  REAL, constraint SERVLET_DEPLOY_TABLE2 primary key(ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop TABLE EMPLOYEEEJB  !
create TABLE EMPLOYEEEJB (HIREDATE DATE NULL, ID INTEGER NOT NULL, FIRSTNAME VARCHAR(256) NULL, SALARY REAL NOT NULL, LASTNAME VARCHAR(256) NULL, EMPLOYEEEJB_ID INTEGER NULL, DEPARTMENTEJB_ID INTEGER NULL, CONSTRAINT PK_EMPLOYEEEJB PRIMARY KEY (ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!
 
drop TABLE DEPARTMENTEJB  !
create TABLE DEPARTMENTEJB (NAME VARCHAR(256) NULL, ID INTEGER NOT NULL, CONSTRAINT PK_DEPARTMENTEJB PRIMARY KEY (ID))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE EMPLOYEEEJB ADD CONSTRAINT FK_MANAGER FOREIGN KEY (EMPLOYEEEJB_ID) REFERENCES EMPLOYEEEJB (ID) !
ALTER TABLE EMPLOYEEEJB ADD CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEPARTMENTEJB_ID) REFERENCES DEPARTMENTEJB (ID) !

